### ISSUE TITLE
training upstrean *and* castom downstream task using pretrained upstream model (mockingjay)

### ISSUE THREAD

**Issue by OG-algo** [s3prl/s3prl#101]
Hi,
I would like to train the pre-trained Mockingjay upstream with a custom downstream task and a custom loss function. I don't see any instructions on how to do it in the readme.

pre-trained Mockingjay model is: states-1000000.ckpt
downloaded from 'https://www.dropbox.com/s/7f9z6dzc7oix6qv/states-1000000.ckpt?dl=0'

I tried to train the following model with no success:

```
class Model(nn.Module):
    def __init__(self, modelPath, device=None, **kwargs):
        super(Model, self).__init__()

        # init attributes
        if device is None:
            self.device = "cuda" if torch.cuda.is_available() else "cpu"
        else:
            self.device = device

        try:
            self.Upstream_local = getattr(importlib.import_module('hubconf'), 'mockingjay_local')
            self.MJ = self.Upstream_local(ckpt=modelPath).to(self.device)
        except:
            raise ValueError(f'The path {modelPath} is not a valid checkpoint!')

        # self.Upstream = getattr(importlib.import_module('hubconf'), 'mockingjay_default')
        # self.dimMatchTech = self.__getDimMatch__(dimMatch='mean')
        self.fc1 = nn.Linear(1536, 1536).to(self.device)
        self.fc2 = nn.Linear(1536, 1536).to(self.device)
        # self.lstm = nn.LSTM(3, 1)
        # self.upstream_model = self.Upstream(refresh=refreshModel).to(device)
        # self.upstream_model = self.Upstream(refresh=True)

    def forward(self, x):

        # upstream:
        x = self.MJ(x)
        x = x[0]

        x = self.time_pool(x)

        x = self.fc1(x)
        x = self.fc2(x)

        return x

    def time_pool(self, x):
        mean, std = torch.mean(x, dim=0), torch.std(x, dim=0)
        return torch.cat((mean, std), dim=0)
 
```

my loss function:

```
     def triplet_loss(self, distances, anchors, positives, negatives):
        """Compute triplet loss
        Parameters
        ----------
        distances : torch.Tensor
            Condensed matrix of pairwise distances.
        anchors, positives, negatives : list of int
            Triplets indices.
        Returns
        -------
        loss : torch.Tensor
            Triplet loss.
        """

        # estimate total number of embeddings from pdist shape
        n = int(0.5 * (1 + np.sqrt(1 + 8 * len(distances))))

        # convert indices from squared matrix
        # to condensed matrix referential
        pos = self.to_condensed(n, anchors, positives)
        neg = self.to_condensed(n, anchors, negatives)

        # compute raw triplet loss (no margin, no clamping)
        # the lower, the better
        delta = distances[pos] - distances[neg]

        # clamp triplet loss
        if self.clamp == "positive":
            loss = torch.clamp(delta + self.margin_, min=0)

        elif self.clamp == "softmargin":
            loss = torch.log1p(torch.exp(delta))

        elif self.clamp == "sigmoid":
            # TODO. tune this "10" hyperparameter
            # TODO. log-sigmoid
            loss = torch.sigmoid(10 * (delta + self.margin_))

        return loss
```

can you please help me and all of us want to take advantage of your amazing work through this example on how to use custom downstream?

Thanks

**Comment by andi611** [comment]
Hi,

What did you mean by "no success"?
Did you run into any error, or did the model doesn't fit the loss?

If you want to dock your downstream task with our toolkit, please take a look at [downstream/example](https://github.com/s3prl/s3prl/tree/master/downstream/example).
You can easily integrate your downstream model and loss function with the provided example interface.

Andy

**Comment by OG-algo** [comment]
I run into an error trying to train the Model:

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1536, 1536]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

as you see my downstream model is pretty simple.

looking at downstream/example:
1. cant see where I put my downstream model
2. where I put my loss function
3. how I use my own data
4. how I run it (using pycharm)

thanks

**Comment by andi611** [comment]
> I run into an error trying to train the Model:

> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1536, 1536]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

I think this is an error from your code. 
I've never seen this error before.

> looking at downstream/example:
> 1. cant see where I put my downstream model
> 2. where I put my loss function
> 3. how I use my own data
> 4. how I run it (using pycharm)

1. in `model.py`
2. in `expert.py` at this [line](https://github.com/s3prl/s3prl/blob/6d2327bc6c6ccdd3e21c9c2e7b932b2952667a8e/downstream/example/expert.py#L51)
3. you need to modify `dataset.py`
4. after the above integration, you can run it with command line: 
```bash
python run_downstream.py -m train -d name_of_your_downstream -u mockingjay_local -k path_to_mockingjay_ckpt/states-100000.ckpt -n ExpName
```
or with upstream fine-tuning:
```bash
python run_downstream.py -f -m train -d name_of_your_downstream -u mockingjay_local -k path_to_mockingjay_ckpt/states-100000.ckpt -n ExpName
```
where `name_of_your_downstream` is the directory name placed under `downstream/`.
You only have to modify the four files `model.py`, `expert.py`, `dataset.py`, and `config.yaml`. 
You don't have to change anything in `run_downstream.py`.

**Comment by OG-algo** [comment]
thank you.

"I think this is an error from your code.
I've never seen this error before."

using "Upstream_local" model output as used in my reference code should work with pytorch autograd and .backword?

**Comment by OG-algo** [comment]
Thank you.
I will try working with the written code first (as shown above).

I will consider the later option for my next project :)

I will update soon for the sake of this thread

**Comment by OG-algo** [comment]
sorry for the delay, it worked! :)
