### ISSUE TITLE
Research: emotion CNNSelfAttention architecture

### ISSUE THREAD

**Issue by johndmendonca** [s3prl/s3prl#107]
Hi guys,

I'm getting really good results using the CNNSelfAttention architecture of downstream/emotion on a paralinguistic task when compared to a typical CNN architecture:

https://github.com/s3prl/s3prl/blob/bdf12449227cba0bc5510e4a5cb792b7a8e3c309/downstream/emotion/model.py#L49

I was wondering the idea behind the architecture itself, namely the peculiar addition of the AvgPooling1D at the start. Do you have any paper you can point or was this unpublished work?

**Comment by tzuhsien** [comment]
Hi, 
I am not sure whether there is any paper using this architecture. 
The main idea of using AveragePooling1D is for downsampling. 
Emotion recognition considers the whole utterance, so very detailed local information is not needed.
Also, downsampling help to avoid over-fitting and to make the model use global information.

**Comment by fatma010** [comment]
Hi,

Not directly gives answer for your question @johndmendonca but https://arxiv.org/pdf/2102.04097.pdf maybe gives idea

**Comment by johndmendonca** [comment]
Thank you both!
