### ISSUE TITLE
Support for XLSR-53

### ISSUE THREAD

**Issue by unilight** [s3prl/s3prl#109]
Hi, thanks for the nice work!
I am just wondering if there's any plan on supporting XLSR-53, the multilingual pre-trained wav2vec 2.0 model?
Thank you!

**Comment by leo19941227** [comment]
Hi,

Thanks!
Yes this will be supported soon, hopefully one or two days later.

**Comment by leo19941227** [comment]
Hi, sorry for the late.
I am adding this now.

**Comment by leo19941227** [comment]
Hi,

You can now use `-u` wav2vec2_xlsr` to use the multilingual version.
Thanks for your patient!
