### ISSUE TITLE
ASR test

### ISSUE THREAD

**Issue by liu-x-p** [s3prl/s3prl#110]
Hi, I want to test the performance on ASR, and I followed the instructions in the former vision of your code, which used the pytorch-kaldi toolkit. But when loading the pretrained model, it reported that `ModuleNotFoundError: No module named 'optimizers'`.
What should I do if i want to test the  ASR performance?
Looking forward to your reply.

**Comment by andi611** [comment]
Hi,

You can find our latest ASR implementation [here](https://github.com/s3prl/s3prl/tree/develop/downstream#asr-automatic-speech-recognition).
We will soon merge this branch into master.

I hope this helps!

Andy

**Comment by liu-x-p** [comment]
Thank you for your help!
