### ISSUE TITLE
Support for PPG extractor

### ISSUE THREAD

**Issue by unilight** [s3prl/s3prl#112]
Hi, I have been reading this paper lately (https://arxiv.org/abs/2104.02901), and in section 3.2 it was claimed that they extracted PPG using this repo, but I cannot find it. Is it a feature not yet released, or am I missing anything? Much thanks for any instructions!

**Comment by leo19941227** [comment]
Hi,

Yes the Timit PPG is registered as a upstream in this repository.
The name of the upstream is `timit_posteriorgram`. You can either use `-u timit_posteriorgram` in `run_downstream.py` or follow the [torch.hub usage pattern](https://github.com/s3prl/s3prl/tree/master/upstream#1-for-all-interface).
