### ISSUE TITLE
Reproduce MOSEI dataset result in MockingJay paper

### ISSUE THREAD

**Issue by toco2270853** [s3prl/s3prl#118]
Hello, thanks for the good code.
I'm wondering how does the sentiment classification task in MockingJay paper
is implemented. 
  In the mosei downstream, the default config use 2 class and perform
utterance-wise classification. In  Mockingjay paper, classification is done by a rnn classifier, 
so it perform frame-wise classification? how about the class number, it's 2 or 7?

**Comment by leo19941227** [comment]
Hi,

In the Mockingjay paper, we use RNN and take only the final hidden state for the utterance-wise classification, and use the class number of 2.
