### ISSUE TITLE
Wrong link to NPC

### ISSUE THREAD

**Issue by AchilleSou** [s3prl/s3prl#121]
A really simple (petty?) issue but that has been bugging me for a while.

The link on the NPC row of the upstream table brings to this page : https://github.com/iamyuanchung/Autoregressive-Predictive-Coding

But shouldn't it be this one : https://github.com/Alexander-H-Liu/NPC ? 
I could not find anything NPC related in the first repo and you seem to use the 2nd link code for your NPC model.

Awesome library, thanks for all the hard work !

**Comment by andi611** [comment]
Hi,

Thanks for pointing this out!
You are correct, We'll update it to the correct link shortly.

Sincerely,
Andy
