### ISSUE TITLE
Use own pre-trained weigths for available upstreams

### ISSUE THREAD

**Issue by AchilleSou** [s3prl/s3prl#122]
Hello team,

I would like to pre-train some upstream models with other datasets than Librispeech then fine-tune them on a downstream task (in my case ASR) . The doc is clear for the S3PRL implemented models (Mockingjay, Tera and Audio-ALBERT) but nothing is specified for all the other. 

I tried to pre-train my models with the associated libraries (fairseq for wav2vec2, NPC for NPC, ect.) then load the weights into S3PRL using the `--upstream_ckpt` arg. As I was not sure if my checkpoint was really taken into account, I tried to give it a wrong model checkpoint (that should normally raise an error) but it ended up running fine so I guess it wasn't taken into account.

There is marked that `--upstream_ckpt` should "Only set when the specified upstream need it" so I guess it's normal that it does not work except for `_local` models but then is there a way to do this ?

Thanks !

**Comment by leo19941227** [comment]
Hi!

Yes you will need to use --wav2vec2_local with --upstream_ckpt. Then you will loaded the wav2vec2 pretrained by yourself. Does this answer your question?

**Comment by AchilleSou** [comment]
Yes thanks !
