### ISSUE TITLE
How converted_aligned_phones.txt was created?

### ISSUE THREAD

**Issue by SolomidHero** [s3prl/s3prl#124]
Hi! I've got a question about phoneme classification tasks. There are `data/converted_aligned_phones.txt` file with labeled frames data for default 10 ms stride. I wonder how this values have been calculated.

In case of TIMIT it is clear that values were provided. But for librispeech data, was it some force-alignment tool?

Thank you for any guidance!

**Comment by leo19941227** [comment]
If I remember right, those aligned labels are the same set as that in the [CPC paper](https://arxiv.org/abs/1807.03748).
They released the phoneme labels used in that paper which was forced aligned with the Kaldi pretrained ASR model.

Does this answer your question?
