### ISSUE TITLE
TERA 100 hour baseline

### ISSUE THREAD

**Issue by mn7ark** [s3prl/s3prl#132]
Hi, 
  I have read paper for SUPERB benchmark, and I found that in the paper , TERA was trained with LS360 data, I'm wondering is there TERA checkpoint that follow similar training method but trained with LS100 in the default upstream(I only find one trained with fbank for 200000 step, but it use only time and frequency masking, and I'm not sure whether 200000 step is enough.), or can I get one?

**Comment by andi611** [comment]
Hi,

I think `-u tera_100hr` is what you are looking for (https://github.com/s3prl/s3prl/blob/301c8db2a32afe7bacea86f56039bd8c9be5eee5/upstream/tera/hubconf.py#L60-L65).
It is trained with LS100, with time + frequency + magnitude masking. 
Btw, 200k steps are more than enough for 100hrs of data.

Andy
