### ISSUE TITLE
input_dim in MOSEI downstream

### ISSUE THREAD

**Issue by Sreyan88** [s3prl/s3prl#133]
Hi there,

I had a question regarding the `input_dim` in MOSEI downstream task. As far as I infer the model is taking a mean across different timesteps and passing it to the linear layer for classification. However `features.mean(dim=1)` would mean BxTxD gets to BxD and D according to the Mockingjay paper is 768 whereas `input_dim` in MOSEI is 256. I am not exactly being able to locate where this 768 is converted to 256. Any help would be appreciated!

Thank You!

**Comment by andi611** [comment]
Hi,

I believe this [line](https://github.com/s3prl/s3prl/blob/a3f279e4bdee71e3366ec0ffffe92a696b0c79f3/downstream/mosei/expert.py#L64) here is what you are looking for :)
