### ISSUE TITLE
How to run hubert?

### ISSUE THREAD

**Issue by itaigat** [s3prl/s3prl#135]
Thanks for a great repository! 
Can you please elaborate about how to run hubert?

**Comment by leo19941227** [comment]
Hi,

Do you mean how to use it in the downstream tasks?
Here is an example
```
python3 run_downstream.py --mode train --upstream hubert_base --downstream asr --name HubertBaseOnASR
```
You can refer to [here](https://github.com/s3prl/s3prl/tree/master/downstream#asr-automatic-speech-recognition) for more information. Also, HuBERT has multiple variants in fairseq's release. You can refer to [here](https://github.com/s3prl/s3prl/blob/master/upstream/hubert/hubconf.py) for the available options or use `python3 run_downstream.py -h` and check all the available `UPSTREAM`
Does this answer your question?

Thanks!

**Comment by itaigat** [comment]
Thanks for the quick response. I actually meant how to train it as an upstream.

**Comment by leo19941227** [comment]
Hi,

If you mean **pretrain** it from scratch, we do not replicate the training pipeline from fairseq. You will need to use fairseq to pretrain HuBERT and wav2vec2.

**Comment by itaigat** [comment]
Thanks :)
