### ISSUE TITLE
NEED for training recipes ? 

### ISSUE THREAD

**Issue by Enescigdem** [s3prl/s3prl#136]
Hello,
I want to train my models with this toolkit. Is there any training recipe for training on our own data set? 

Thanks in advance

**Comment by andi611** [comment]
Hi, may I ask what kind of models do you wish to train?

Currently we only support several pre-training methods including: Mockinjay, TERA, and Audio ALBERT.
Their pre-training procedures can be found in the [Pretraining README](https://github.com/s3prl/s3prl/blob/master/pretrain/README.md), which can also be changed to another dataset other than LibriSpeech (with minor modifications).

I hope this clarifies your question, thanks!
Andy.

**Comment by Enescigdem** [comment]
Yes, this clarified me.
It is said that in the Mojkingjay paper: we will investigate and deploy Mockingjay representations on more downstream SLP tasks, including ASR, voice conversion, and speech translation. Is it deployed for voice conversion or asr tasks ? I mean how can I use this great model for voice conversion and speech recognition? 
Thanks a lot

**Comment by andi611** [comment]
Hi, 

We have deployed upstream models for speech recognition (ASR), please see here: [downstream/README/ASR](https://github.com/s3prl/s3prl/blob/master/downstream/README.md#asr-automatic-speech-recognition) for detailed instructions.
You can choose Mockingjay with the command `-u mockingjay`, 
or TERA (an improved version of Mockingjay) with the command `-u tera`.

In the [downstream/README](https://github.com/s3prl/s3prl/blob/master/downstream/README.md), you will also find all kinds of downstream tasks that we currently support. Unfortunately, we don't have voice conversion for now. However, you can always extract representations from Mockingjay or TERA, then do VC with your own code.

For a tutorial on upstream representation extraction, please see the [upstream/README/use-upstream-models-in-your-own-project](https://github.com/s3prl/s3prl/blob/master/upstream/README.md#use-upstream-models-in-your-own-project).
