### ISSUE TITLE
Problem with Hubert finetuning

### ISSUE THREAD

**Issue by virginiakm1988** [s3prl/s3prl#139]
Hi, 

I ran into an error when trying to fine tune hubert model.
When running `python3 run_downstream.py  -u hubert_base -d example  -m train -f`,

the code will raise error like this:
`assert self.layer_num == len(feature), f"{self.layer_num} != {len(feature)}"
AssertionError: 13 != 12`

When in finetune mode, the keys of the feature will became this:
`dict_keys(['default', '_hidden_states_info', 'hidden_states', 'last_hidden_state', 'hidden_state_0', 'hidden_state_1', 'hidden_state_2', 'hidden_state_3', 'hidden_state_4', 'hidden_state_5', 'hidden_state_6', 'hidden_state_7', 'hidden_state_8', 'hidden_state_9', 'hidden_state_10', 'hidden_state_11'])`

the hidden_state_12 is missing, therefore raise an error when doing weighted sum.

Any idea on where the issue may be?
Thanks in advance

**Comment by simpleoier** [comment]
@virginiakm1988 It is because of `layer dropout` in HuBERT model. Try this one after you load the model.
```python
hubert_model.encoder.layerdrop = 0.0
```

**Comment by virginiakm1988** [comment]
Thank you! I added it in the expert.py of HuBERT and it worked.

**Comment by jefflai108** [comment]
A follow-up question, have we done experiments on joint upstream fine-tuning with weighted layer sum? Im unsure if removing layer drop is a good idea.

**Comment by simpleoier** [comment]
That's a good point @jefflai108. It's hard to train the layer weights and fine-tune upstream at the same time. It's worthing trying on `last-layer` mode.
