### ISSUE TITLE
Error: `from torch.tensor import Tensor` with PyTorch 1.9

### ISSUE THREAD

**Issue by unilight** [s3prl/s3prl#140]
I know that the `requirements.txt` suggests using PyTorch 1.7.0, but just to let you know that there is an issue when using an advanced version like 1.9.
To reproduce: run `python run_downstream.py -m train -n test -u fbank -d example` with PyTorch 1.9 installed.
```
Traceback (most recent call last):
  File "run_downstream.py", line 16, in <module>
    from downstream.runner import Runner
  File "/mrnas02/internal/wenchin-h/Experiments/s3prl/downstream/runner.py", line 20, in <module>
    from upstream.interfaces import Featurizer
  File "/mrnas02/internal/wenchin-h/Experiments/s3prl/upstream/interfaces.py", line 8, in <module>
    from torch.tensor import Tensor
ModuleNotFoundError: No module named 'torch.tensor'
```
The same line also appears in the following files:
```
./upstream/example/expert.py
./upstream/mockingjay/expert.py
./upstream/pase/hubconf.py
./upstream/wav2vec2_hug/expert.py
```
I think we import this class only to specify the type of the arguments in the functions, right?
If so, how about `from torch import Tensor`? I tried and it worked in both PyTorch 1.7 and 1.9. Haven't tried 1.8 yet.

**Comment by leo19941227** [comment]
Thanks for reporting!
