### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lmxue** [s3prl/s3prl#155]
I followed the installation command as follows (https://github.com/s3prl/s3prl):

![image](https://user-images.githubusercontent.com/33707885/126792178-32197ce7-d303-4df0-8b7b-ee2e0b7cc103.png)

After that, when I  used upstream models,
![image](https://user-images.githubusercontent.com/33707885/126792464-b58a0241-afd9-49ec-a4d6-56e3a2c60bab.png)

 it starts to download the https://github.com/s3prl/s3prl/archive/master.zip" to .cache  directory, and after downloading, it still occurred the following errors：

![image](https://user-images.githubusercontent.com/33707885/126792635-07ed7536-bf00-4c9f-b4a3-60b791a6f40a.png)

**Comment by leo19941227** [comment]
Hey!

Thanks for reporting.
These are just warnings instead of errors.
This means some functionality might not work due to some very rare use case, but the code you paste will work correctly.

**Comment by lmxue** [comment]
> Hey!
> 
> Thanks for reporting.
> These are just warnings instead of errors.
> This means some functionality might not work due to some very rare use cases, but the code you paste will work correctly.

It says "No module named pase.." (the last line in the last figure) and other modules (I did not paste the figure). I'm confused why no modules can be found even if I have installed the modules.
