### ISSUE TITLE
Input normalization of tera and mockingjay

### ISSUE THREAD

**Issue by mn7ark** [s3prl/s3prl#156]
Hi, I found that there is a "_normalize_wav_decibel" function in the   TransformerBuilder, and I'm wondering whether mockingjay and tera always perform this operation regardless of it's training or testing phase.

**Comment by andi611** [comment]
Hi,

Yes, we apply this operation during training and testing, the target level value can be found [here](https://github.com/s3prl/s3prl/blob/c547e69199aee6c00bdd723cff04e208efa0019f/s3prl/pretrain/tera/config_model.yaml#L28).

Andy

**Comment by mn7ark** [comment]
it is very clear, thanks! I really appreciate  the quick reply
