### ISSUE TITLE
ddp pretraining

### ISSUE THREAD

**Issue by mlxu995** [s3prl/s3prl#158]
Thank you for opening such good codes.

Could I use ddp to pretrain a model?

**Comment by leo19941227** [comment]
Hey!

Sorry that the pretraining part not yet support DDP I think. The current implementation is in DP only. I am not sure whether there is a plan for upgrading to DDP. @andi611 is in charge of the pretraining part, and might give you more information :)

**Comment by andi611** [comment]
You can use data parallel by using the argument `--multi_gpu`, see [here](https://github.com/s3prl/s3prl/blob/aab5ba54ffbc2cc3aabb966e6c5b610297622787/s3prl/run_pretrain.py#L54).

However, we currently don't support DDP at the moment, but surely we can add it in the future.
