### ISSUE TITLE
Custom task - Finetune with different data ? 

### ISSUE THREAD

**Issue by Enescigdem** [s3prl/s3prl#161]
I collected part of my .wav files for training in a single directory since it is done in librispeech example.  (Is it necessary ?) 
But then, I do not know to adjust transcriptions so it gives the error below not surprisingly.

_Traceback (most recent call last):
  File "preprocess/generate_len_for_bucket.py", line 122, in <module>
    main()
  File "preprocess/generate_len_for_bucket.py", line 112, in main
    for idx, s in enumerate(SETS):
UnboundLocalError: local variable 'SETS' referenced before assignment_

What are changes which should be done for finetuning or training for any task on different data set? 
Thanks in advance

**Comment by andi611** [comment]
Hi,

I think you need to check out these [lines](https://github.com/s3prl/s3prl/blob/205cdc3abd7d56169a98557bf865230a661a06de/s3prl/preprocess/generate_len_for_bucket.py#L100-L112).
Simply make the `SETS` list accommodate your custom data directory.

Andy

**Comment by Enescigdem** [comment]
Hi,
I changed that script and also dataset.py files. I could use my own data in csv format with their paths and transcriptions for asr task. 
But I want to use this great toolkit for other tasks like zerospeech 2021 . What possible steps for a task like this ?

**Comment by andi611** [comment]
> Hi,
> I changed that script and also dataset.py files. I could use my own data in csv format with their paths and transcriptions for asr task.
> But I want to use this great toolkit for other tasks like zerospeech 2021 . What possible steps for a task like this ?
> @andi611

Hi, do you plan on using the zerospeech 2021 data for pre-train? Or do you simply want to adopt the pre-trained models to the zerospeech 2021 task? 
For the first case, I think you can do the same to the zerospeech 2021 data, and pre-train your own model like u already did.
For the second case, we do have a simple solution, please see this page [here](https://github.com/s3prl/s3prl/blob/master/s3prl/upstream/README.md#use-upstream-models-in-your-own-project).

If I'm missing your point, please do kindly provide more information ;)

Thanks,
Andy.
