### ISSUE TITLE
How to get or extract updated upstream model from a fine-tuned checkpoint with downstream model  ?

### ISSUE THREAD

**Issue by wz1988** [s3prl/s3prl#167]

**Comment by leo19941227** [comment]
Hey there, could you elaborate more about your use case?
I do not yet quite get the point. Thanks!

**Comment by wz1988** [comment]
Thanks @leo19941227 . assume that, after fine-tuning with downstream model, I had a saved "dev-best.ckpt", my understanding, this ckpt consists of both upstream and downstream model,  how can we get a "new updated upstream model" from this ckpt ?  in other words, after the fine-tuning, is there a way to separate/extract an Upstream Model again ?  Thank you !    Maybe there is a simple option during the training, severing this purpose ?

**Comment by Enescigdem** [comment]
Hi,
I ask the same issue.
After training upstream model,how to use its states-xxx.pt  for feature extraction ?

**Comment by leo19941227** [comment]
Hi @wz1988 and @Enescigdem ,

For the default setting in `run_downstream.py`, the upstream is fixed and is stateless during entire training.
So you can just use the original upstream to extract representations and feed into the trained downstream model.
In this case, since the upstream is stateless so the saved checkpoints will not have weights for upstream.
If you wish to finetune the upstream model also, you will need to run the `run_downstream.py` script with `-f` or `--upstream_trainable`.
In this case, the saved checkpoints will contained an field "Upstream" which has the finetuned weights for the upstream model.
Hope this answer your question!

**Comment by Enescigdem** [comment]
I conducted an pretrain trainining with run_pretrain.py using TERA on my own data. Should i retrain ?

**Comment by leo19941227** [comment]
So your question is about how to use the checkpoint you get from run_pretrain.py for run_downstream.py. Am I right?

**Comment by Enescigdem** [comment]
Yes you are right

**Comment by leo19941227** [comment]
You can try `run_downstream.py` with `-u tera_local -k your_pretrained_checkpoint`

**Comment by Enescigdem** [comment]
This is good but I should ask that I was planning to get features from tera and use it different way.

**Comment by leo19941227** [comment]
Cool! how about

```
from s3prl.hub import tera_local
upstream = tera_local(ckpt="your_pretrained_checkpoint")
all_hidden_states = upstream["hidden_states"]
```
Will this work for you?

**Comment by Enescigdem** [comment]
> Cool! how about
> 
> ```
> from s3prl.hub import tera_local
> upstream = tera_local(ckpt="your_pretrained_checkpoint")
> all_hidden_states = upstream["hidden_states"]
> ```
> 
> Will this work for you?

Unfortunately,it did not work then i commented here

**Comment by leo19941227** [comment]
Weird, it should work.
Can you paste the error message?

**Comment by Enescigdem** [comment]
sorry i did not use tera_local , i tried to use directly loading from checkpoint

**Comment by Enescigdem** [comment]
Traceback (most recent call last):
  File "extract.py", line 46, in <module>
    feature = extract(model=None,
  File "extract.py", line 21, in extract
    all_hidden_states = upstream["hidden_states"]
TypeError: 'UpstreamExpert' object is not subscriptable

**Comment by wz1988** [comment]
> 
> 
> Hi @wz1988 and @Enescigdem ,
> 
> For the default setting in `run_downstream.py`, the upstream is fixed and is stateless during entire training.
> So you can just use the original upstream to extract representations and feed into the trained downstream model.
> In this case, since the upstream is stateless so the saved checkpoints will not have weights for upstream.
> If you wish to finetune the upstream model also, you will need to run the `run_downstream.py` script with `-f` or `--upstream_trainable`.
> In this case, the saved checkpoints will contained an field "Upstream" which has the finetuned weights for the upstream model.
> Hope this answer your question!

@leo19941227  Thank you so much for the speedy reply.
I try to ask question differently, is that a way/script to save upstream model again from a saved check-point during fine-tuning run_downstream
 training with "--upstream_trainable` option ?  Thanks !

**Comment by leo19941227** [comment]
@wz1988 ,

Actually yes we save the finetuned upstream if `upstream_trainable`. So we will also see an `Upstream` field inside the checkpoint.

**Comment by leo19941227** [comment]
@Enescigdem,

Sorry my fault

```
from s3prl.hub import tera_local
upstream = tera_local(ckpt="your_pretrained_checkpoint")
wavs = [torch.randn(16000)]
all_hidden_states = upstream(wavs)["hidden_states"]
```

**Comment by wz1988** [comment]
> 
> 
> @wz1988 ,
> 
> Actually yes we save the finetuned upstream if `upstream_trainable`. So you will also see an `Upstream` field inside the checkpoint.

Thanks @leo19941227 , how can we separate and save the 'Upstream" model again from the jointly fine-tuned saved checkpoint ?

**Comment by andi611** [comment]
> > @wz1988 ,
> > Actually yes we save the finetuned upstream if `upstream_trainable`. So you will also see an `Upstream` field inside the checkpoint.
> 
> Thanks @leo19941227 , how can we separate and save the 'Upstream" model again from the jointly fine-tuned saved checkpoint ?

Hi @wz1988, I think you can save it at the end of the fine-tuned script like a regular `torch.nn.Module`.

**Comment by leo19941227** [comment]
This issue is the same as #75 . However I haven't come up an elegant way to support this.
I am closing this issue first and leave #75 open.
