### ISSUE TITLE
Pretraining from scratch ?

### ISSUE THREAD

**Issue by Enescigdem** [s3prl/s3prl#172]
Hi, I want to train pretraining models especially TERA. Is it possible? If so what is the GPU requirement and time?

**Comment by andi611** [comment]
Hi,

Yes, most definitely. You can change the [batch size](https://github.com/s3prl/s3prl/blob/a9b3ba906f3406c3e00aa65b08fbcefa0ea115ef/s3prl/pretrain/tera/config_runner.yaml#L19) and [gradient accumulating steps](https://github.com/s3prl/s3prl/blob/a9b3ba906f3406c3e00aa65b08fbcefa0ea115ef/s3prl/pretrain/tera/config_runner.yaml#L5) to fit the model on almost any GPU.
See the procedures [here](https://github.com/s3prl/s3prl/blob/master/s3prl/pretrain/README.md).

**Comment by Sreyan88** [comment]
Hi @andi611 ,

A question about pre-training, I have two folders train and dev with raw wav files (not libri). I want to pre-train the model from scratch. Now all I am doing is changing "libri_root" directory and creating new "file_path". 

I have gone through the code and all the processing seems generic to all kinds of datasets and the pre-training starts too. However just wanted to confirm if I am missing something and is this the right thing to do!

Thank You

**Comment by andi611** [comment]
Hi @Sreyan88,

You may also want to change the `sets: ['train-clean-100', 'train-clean-360', 'train-other-500']` in `config_runner.yaml`.
Everything else seems ok!

**Comment by Sreyan88** [comment]
Yes perfect! Thank You so much @andi611 .

**Comment by Sreyan88** [comment]
Hi @andi611 ,

Another question in your pre-training your frequency masking code goes like:

spec_masked[idx, :, chosen_intervals] = 0

What I infer this would mean that for the chosen intervals for frequency masking you would make all frames in the input. Is that right?

and, mask_label[idx, :spec_len[idx], chosen_intervals] = 1

Which would mean for loss calculation you would be considering all frames till spec_len[idx] where "idx" stands for the index of the iteration inside the batch (the training sample).

Just wanted to confirm this phenomenon because in your paper I read you have just chosen one frame for frequency masking.

Thank You!

**Comment by Sreyan88** [comment]
Hi @andi611 ,

I get an error while pre-training Tera:

RuntimeError: [enforce fail at CPUAllocator.cpp:71] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 3386880000000 bytes. Error code 12 (Cannot allocate memory)

I don't get this error while pre-training Mockingjay. I understand this is a memory allocation error but I don't see much difference in the config. Can you suggest what I ca change in TERA to reduce memory usage?

**Comment by andi611** [comment]
> Hi @andi611 ,
> 
> I get an error while pre-training Tera:
> 
> RuntimeError: [enforce fail at CPUAllocator.cpp:71] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 3386880000000 bytes. Error code 12 (Cannot allocate memory)
> 
> I don't get this error while pre-training Mockingjay. I understand this is a memory allocation error but I don't see much difference in the config. Can you suggest what I ca change in TERA to reduce memory usage?

Hi, can you provide the configs you are using? (Mockingjay and TERA) and also the memory size of your machine.

**Comment by Sreyan88** [comment]
Hi @andi611 ,

I am using default tera config which can be found at s3prl/s3prl/pretrain/tera/.

I have 96 cores and 512gb of ram. My dataset barely has 500 files.

Note: I get the same error when I try to load one of your 300hr checkpoint for pretraining, even for Mockingjay. In TERA even no checkpoint pre-training gives me that error.

**Comment by andi611** [comment]
Are you sure it is 512GB of ram? 512GB is extremely large, it should not be a problem.
A 2080Ti has 12GB of memory, and I could fit TERA on it with no problem.
You may want to try and lower the batch size, and increase the accumulated steps to fit the model on your machine.

BTW, with or without a pre-trained checkpoint is not relevant to model memory size.

**Comment by Sreyan88** [comment]
`Traceback (most recent call last):                                                                                                                                                                                   | 0/293 [00:00<?, ?it/s]
  File "run_pretrain.py", line 127, in <module>
    main()
  File "run_pretrain.py", line 122, in main
    eval('runner.train')()
  File "/speech/srayan/icassp_toxic/interspeech_toxic/pretraining/s3prl/pretrain/runner.py", line 159, in train
    for data in tqdm(dataloader, dynamic_ncols=True, desc='train'):
  File "/speech/srayan/anaconda3/envs/icassp_toxic/lib/python3.6/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/speech/srayan/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/speech/srayan/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/speech/srayan/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/speech/srayan/.local/lib/python3.6/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/speech/srayan/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/speech/srayan/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/speech/srayan/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/speech/srayan/icassp_toxic/interspeech_toxic/pretraining/s3prl/pretrain/mockingjay/dataset.py", line 160, in __getitem__
    return self._process_x_pad_batch(x_pad_batch)
  File "/speech/srayan/icassp_toxic/interspeech_toxic/pretraining/s3prl/pretrain/mockingjay/dataset.py", line 154, in _process_x_pad_batch
    return generate_masked_acoustic_model_data(feat_list, config=self.task_config)
  File "/speech/srayan/icassp_toxic/interspeech_toxic/pretraining/s3prl/pretrain/mockingjay/task.py", line 94, in generate_masked_acoustic_model_data
    attn_mask[idx, spec_len[idx]:] = 0
TypeError: slice indices must be integers or None or have an __index__ method
`

I use 2 2080Ti s. Yes I am sure about the size. With batch size of 2 I get the above error.

**Comment by andi611** [comment]
It is weird, I haven't seen this error before.
If you are using two GPUs, did u run with the `--multi_gpu` argument?

**Comment by Sreyan88** [comment]
Yes I have done that. As the above error shows it's trying to allocate 3.3TBs of ram I have no idea why :(

**Comment by Sreyan88** [comment]
Also, I am attempting to pre-train over one of your pre-trained models and it throws:

```
RuntimeError: Error(s) in loading state_dict for TransformerModel:
        size mismatch for input_representations.spec_transform.weight: copying a param with shape torch.Size([768, 80]) from checkpoint, the shape in current model is torch.Size([768, 240]).

```
I am using fbank, I don't know from where I am getting the 240 dim, could you please help me in this regards too.

**Comment by Sreyan88** [comment]
> Yes I have done that. As the above error shows it's trying to allocate 3.3TBs of ram I have no idea why :(
> 
> Here is the stack trace:
> 
> ```
> Traceback (most recent call last):                                                                                                   | 0/147 [00:00<?, ?it/s]
>   File "run_pretrain.py", line 129, in <module>
>     main()
>   File "run_pretrain.py", line 124, in main
>     eval('runner.train')()
>   File "/speech/guruprasad/interspeech_toxic/interspeech_toxic/pretraining/s3prl/pretrain/runner.py", line 162, in train
>     for data in tqdm(dataloader, dynamic_ncols=True, desc='train'):
>   File "/speech/guruprasad/espnet/tools/venv/envs/icassp_toxic/lib/python3.6/site-packages/tqdm/std.py", line 1185, in __iter__
>     for obj in iterable:
>   File "/speech/guruprasad/espnet/tools/venv/envs/icassp_toxic/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
>     data = self._next_data()
>   File "/speech/guruprasad/espnet/tools/venv/envs/icassp_toxic/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
>     return self._process_data(data)
>   File "/speech/guruprasad/espnet/tools/venv/envs/icassp_toxic/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
>     data.reraise()
>   File "/speech/guruprasad/espnet/tools/venv/envs/icassp_toxic/lib/python3.6/site-packages/torch/_utils.py", line 425, in reraise
>     raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/speech/guruprasad/espnet/tools/venv/envs/icassp_toxic/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/speech/guruprasad/espnet/tools/venv/envs/icassp_toxic/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/speech/guruprasad/espnet/tools/venv/envs/icassp_toxic/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/speech/guruprasad/interspeech_toxic/interspeech_toxic/pretraining/s3prl/pretrain/mockingjay/dataset.py", line 159, in __getitem__
>     x_pad_batch = pad_sequence(x_batch, batch_first=True)
>   File "/speech/guruprasad/espnet/tools/venv/envs/icassp_toxic/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 363, in pad_sequence
>     return torch._C._nn.pad_sequence(sequences, batch_first, padding_value)
> RuntimeError: [enforce fail at CPUAllocator.cpp:71] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 1693440000000 bytes. Error code 12 (Cannot allocate memory)
> ```

I have now tried the pre-training on 2 different machines including google colab, I get the same error.

**Comment by andi611** [comment]
> Also, I am attempting to pre-train over one of your pre-trained models and it throws:
> 
> ```
> RuntimeError: Error(s) in loading state_dict for TransformerModel:
>         size mismatch for input_representations.spec_transform.weight: copying a param with shape torch.Size([768, 80]) from checkpoint, the shape in current model is torch.Size([768, 240]).
> ```
> 
> I am using fbank, I don't know from where I am getting the 240 dim, could you please help me in this regards too.

This is because you are using a different config with different input dim than the pre-trained model.

From your error message: 
the input dim of the pre-train model is 80 (`copying a param with shape torch.Size([768, 80]) from checkpoint`),
and it looks like you've created a model with input dim of 240 (`the shape in current model is torch.Size([768, 240])`).

The 240-dim is probably from setting delta to 2, as `80-dim + delta_1 + delta_2 = 240`.

**Comment by andi611** [comment]
> Yes I have done that. As the above error shows it's trying to allocate 3.3TBs of ram I have no idea why :(

It is very strange, I have no problem running the model on a single 2080Ti.
I think you may have accidentally changed some parameter that largely affects memory usage. Can you double check and confirm that everything is identical to the master code?

And if you can paste the result of running this command in your terminal: `nvidia-smi`, it may help to solve your problem.
