### ISSUE TITLE
About Training

### ISSUE THREAD

**Issue by miyazakieiji** [s3prl/s3prl#175]
Hi, thank you for a great repository!

Does the training done in the rundownstream.py  just train the neural network of downstream task? Or is it also finetuning of specified upstream task?

I'm sorry if this is rudimentary, but please help me.

Thank you!

**Comment by miyazakieiji** [comment]
Hi, thank you for a quick response!

How can I do upstream fine tuning?

Thanks again!

**Comment by leo19941227** [comment]
Hi,

Simply add `--upstream_trainable` when running through all the task documented under the downstream folder.

**Comment by miyazakieiji** [comment]
Hi,

I missed it, it will be greathelp thanks again!
