### ISSUE TITLE
How to use a single GPU to train a downstream task

### ISSUE THREAD

**Issue by yunshenzhou** [s3prl/s3prl#176]
My GPU workstation has 4 Tesla V100 GPU. When I run s3prl/run_downstream.py, it automatically uses all 4 GPUs even if I specify one GPU. When the memory of one of the GPUs is insufficient, it reports cuda_out_of_memory.

Here's the test code. I just keep the import code for s3prl/run_downstream.py and specify one GPU, then print the number of GPUs, it says 4 instead of 1. Following is the code. It outputs 4 and the expected is 1.

`
import os
import re
import sys
import yaml
import glob
import torch
import random
import argparse
import importlib
import torchaudio
import numpy as np
from argparse import Namespace
from torch.distributed import is_initialized, get_world_size

from s3prl import hub
from s3prl import downstream
from s3prl.downstream.runner import Runner
from s3prl.utility.helper import backup, get_time_tag, hack_isinstance, is_leader_process, override

os.environ["CUDA_VISIBLE_DEVICES"]="3"
print(torch.cuda.device_count())
`

**Comment by leo19941227** [comment]
Hi!,

I think the code you show is just pointing out the available GPUs instead of what you will really utilize when running the run_downstream.py script.
So if you wish to constrain the script to use a specific GPU, maybe you can try:
```
CUDA_VISIBLE_DEVICES=2 python3 run_downstream.py ...
```
Note that the CUDA_VISIBLE_DEVICES index starts from 0.
