### ISSUE TITLE
Details of train/test split in speaker_linear_utter_libri?

### ISSUE THREAD

**Issue by jefflai108** [s3prl/s3prl#179]
hi @andi611 

I am interested in using your speaker probing on Librispeech. Could you share a bit more about the train/test split files? Are they from train-100,360,960? Are speakers from test split covered by the train split? 
thanks!

**Comment by andi611** [comment]
Hi @jefflai108,

The train/test split files is from the [CPC paper](https://arxiv.org/abs/1807.03748), they are from `train-clean-100`, and yes speakers from test split is covered by the train split, because they are all from `train-clean-100`.
You can read more about it in the mentioned CPC paper, or in the [TERA paper](https://arxiv.org/abs/2007.06028).

**Comment by jefflai108** [comment]
thanks!

**Comment by jefflai108** [comment]
Also, does it support probing a finetuned wav2vec2/hubert model?

**Comment by jefflai108** [comment]
a simple hack is to modify "model" to "model.w2v_encoder.w2v_model" in `upstream/hubert/expert.py`

**Comment by jefflai108** [comment]
@leo19941227

**Comment by leo19941227** [comment]
Oh I once support that a long time ago and remove the finetuned variants after huggingface have them all on the huggingface's hub.

**Comment by jefflai108** [comment]
oh i see, i could load the finetuned wav2vec/hubert using huggingface's hub? 
i need this anyways since im using my own checkpoints

**Comment by jefflai108** [comment]
@andi611 I have some prelim results on linear speaker probe with s3prl on pretrained/finetuned hubert's layers. I found that all layers have ~99% speaker ID acc. Suggesting that speaker info is retained even after ASR finetuning. I also see in TERA's Table 2, and MFCC/log mel get decent speaker ID acc. Does this suggest train-clean-100 is not a good dataset for probing speaker ID?

**Comment by andi611** [comment]
Hi @jefflai108, `train-clean-100` is a relatively easy set when compared to harder ones like Voxceleb, it serves best as a sanity check.
Also, we find that models tend to perform well in the `utter` setting, but weaker in the `frame` setting. Perhaps you would like to try `speaker_linear_frame_libri`? It is more discriminative and better for probing speaker ID.

**Comment by jefflai108** [comment]
sounds good @andi611 , let me try frame-level speaker ID
