### ISSUE TITLE
Bug in on-the-fly extractor?

### ISSUE THREAD

**Issue by mn7ark** [s3prl/s3prl#181]
Hi, I accidentally found that in upstream/baseline/preprocessor.py,
when input is log-mel with cmvn, after feature extraction step. zero padded
input will not return zero value frame. It seems that there is small difference between
feature and the mean of feature in cmvn block of "select_feat" function, and cause nonzero numerator. 
  Because some code count non zero frame to determine input length, I think it might be a bug.

**Comment by leo19941227** [comment]
Hey @mn7ark!

Good catch!!
Thanks for pointing out. I am fixing this.

**Comment by andi611** [comment]
Hi @leo19941227, I think we should fix this, it should not affect TERA.

Since the bucketing technique is used during the pre-training of TERA, in each batch the inputs are of the same length, as a result, zero paddings are not used.

**Comment by leo19941227** [comment]
Cool! Okay I will fix this.
