### ISSUE TITLE
Can't find data/cpc_phone/converted_aligned_phones.zip

### ISSUE THREAD

**Issue by SungFeng-Huang** [s3prl/s3prl#182]
Hi, following the downstream phone classification data preprocessing instructions, I cannot find the path mentioned at `s3prl/downstream/README.md#L773`:
```bash
cd data/cpc_phone
unzip converted_aligned_phones.zip
```
However, I do find a file with a similar name: `s3prl/downstream/phone_linear/converted_aligned_phones.txt`.
So how can I continue my data preprocessing?

**Comment by andi611** [comment]
Hi,

Sorry we forget to change the README,
as you said, the files have been moved here: https://github.com/s3prl/s3prl/tree/master/s3prl/downstream/phone_linear/data
You can simply ignore that step, as the path has already been set [here](https://github.com/s3prl/s3prl/blob/558647a69fcc84f69fa6b5524c6e999c76118f9a/s3prl/downstream/phone_linear/config.yaml#L24).

**Comment by SungFeng-Huang** [comment]
Cool. Thanks for your help!

**Comment by andi611** [comment]
The README has been updated by removing that step. https://github.com/s3prl/s3prl/commit/8e3e995dd72d368e47a5410f2f6f1aaf47fc65ab
