### ISSUE TITLE
In SUPERB, what and how the hidden states of wav2vec2 and HuBERT are weighted sumed?

### ISSUE THREAD

**Issue by jasonppy** [s3prl/s3prl#187]
The paper briefly mentioned "Since the last-layer representation is not always the best, the framework collects multiple hidden states from the pretrained model and weighted-sum them as the final representation. " I wonder how many hidden states are used and how the weights are decided?

Thanks

**Comment by leo19941227** [comment]
Hey @jasonppy ,

Thanks for the interest!
We follow the exact same place for extraction as huggingface, which includes the output of CNN and the output of each transformer block. So for wav2vec2/hubert Base, there are 13 hidden states. For wav2vec2/hubert Large, there are 25 hidden states. The weights are initialized as an uniform distribution and then trained with each downstream task.

**Comment by jasonppy** [comment]
Great, thanks for your reply.

This is done automatically in s3prl by default right?

**Comment by leo19941227** [comment]
Yes!

**Comment by jasonppy** [comment]
Great! Thanks
