### ISSUE TITLE
Errors in Mosei downstream

### ISSUE THREAD

**Issue by Sreyan88** [s3prl/s3prl#188]
Hi @andi611 ,

I try running mosei downstream but hit into several errors. I fixed one by adding :

```
def get_dataloader(self, mode):
        return eval(f'self.get_{mode}_dataloader')()
```
where it was an assert problem. The new one I face is :

```
train:   0%|                                                                                                                          | 0/34 [00:01<?, ?it/s]
Traceback (most recent call last):                                                                                                    | 0/34 [00:00<?, ?it/s]
  File "run_downstream.py", line 195, in <module>
    main()
  File "run_downstream.py", line 191, in main
    eval(f'runner.{args.mode}')()
  File "/speech/srayan/icassp_toxic/s3prl/s3prl/downstream/runner.py", line 220, in train
    records = records,
  File "/speech/srayan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got multiple values for argument 'records'
```
Amy possible solution to this?

**Comment by leo19941227** [comment]
Hi @Sreyan88 ,

I think MOSEI is no longer maintained since the person working on this task in our lab is not working on this anymore.
But please feel free to open PR to fix it. Many thanks!

**Comment by Sreyan88** [comment]
Hi @leo19941227 ,

Yes I have figured out the error, will open a PR in the next few days. Thank You!

**Comment by bagustris** [comment]
Hi @Sreyan88,

If you didn't open a PR yet, I would like to request you to add a little information on how to obtain the dataset. You can add it to [`utility/README.txt`](https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/mosei/utility/README.txt). Also, it will be great if you could adding the steps like in IEMOCAP as shown [here](https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/docs/superb.md#er-emotion-recognition).


Thanks in advance!

**Comment by Sreyan88** [comment]
This code contains a line or two custom for my work, however a diff would easily tell you the lines that need to be changed. I will raise a PR by the end of next week. Thank You!

**Comment by bagustris** [comment]
Thanks! @Sreyan88 

It works by modifying your code for reading files to the original version.


    filename = row.FileName + '.wav' --> filename = row.file + '_' + str(row.index) + '.wav'


Looking forward to have your PR.
