### ISSUE TITLE
Huggingface processor is super slow if used on-the-fly

### ISSUE THREAD

**Issue by leo19941227** [s3prl/s3prl#190]
The time for HF processor to pad a batch of waveform is even longer than model forward (even for wav2vec2 Large), since its padding mechanism is generic (for many sequential model) and spend some time unnecessary for waveform.
However the current s3prl framework wish to preprocess waveform on-the-fly.
We should have a faster wav2vec2 feature extractor ourselves which align with HF version.

**Comment by bagustris** [comment]
Hi @leo19941227 

Sorry for not reporting benchmarking time in my previous PR. I think you are right. Although I didn't get double computation time, I inspect that HF slower than s3prl. Here is my benchmarking using Unix `time` command on wav2vec2.0 base.

~~~
# Using S3PRL wav2vec
time python run_downstream.py -d emotion -m train -u wav2vec2_base_960
real    18m52.723s
user    17m51.576s
sys     1m38.763s

# Using HF processor
time python run_downstream.py -d emotion -m train -u wav2vec2_hug_base_960
real    22m31.056s
user    5m40.813s
sys     2m1.184s

# Changing processor to Wav2Vec2FeatureExtractor
time python run_downstream.py -d emotion -m train -u wav2vec2_hug_base_960_feat
real    26m31.555s
user    5m41.884s
sys     2m1.094s

# Using HF AutoFeatureExtractor
time python run_downstream.py -d emotion -m train -u wav2vec2_hug_base_960_featA
real    28m2.829s
user    5m39.233s
sys     2m3.910s
~~~

At first, I supposed that changing `processor` to `FeatureExtractor` will make it faster, but It didn't. 

Btw, If we can raise this issue to upstream HF, and they can improve it, it will be very convenient in future to embed new upstream from HF to S3PRL.

**Comment by leo19941227** [comment]
I am closing this issue since in our new design we are enabling a flexible feature extraction for each task dataset so naturally supports to plug HF Processor into each task dataset and don't force everything to be done at the model forward. Hence, this issue is avoided.
