### ISSUE TITLE
Pre-extracted representations for SUPERB benchmark

### ISSUE THREAD

**Issue by leo19941227** [s3prl/s3prl#191]
When the pretrained upstream goes larger and larger, it come become more and more unrealistic to do representation inference on-the-fly. Might need to find a way to support caching representations. So that the pipeline become:

1. Extract features for a specific dataset
2. Train the downstream task with extracted features

Note that this new function should be backward-compatible with on-the-fly features extraction, and also the system bottleneck will move from GPU speed to IO speed. The following should be well-examined before starting to implement this function:

1. How slow will it be to load pre-extracted representations in dataloader.

**Comment by jasonppy** [comment]
I'm very curious about what file you will use to store the extracted data, which might lead to different trade off between space and speed

**Comment by leo19941227** [comment]
I think this proposal will not have the recent progress. Hence is closing it first. Please feel free to re-open it if you have any good idea! Any contribution is welcomed :)
