### ISSUE TITLE
FileNotFoundError when running Speaker Diarization task in SUPERB

### ISSUE THREAD

**Issue by jasonppy** [s3prl/s3prl#193]
Hi,

I followed the instructions to simulate Libri2Mix Data for Diarization here https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/README.md, but then running training command would throw an error:

```
Traceback (most recent call last):
  File "run_downstream.py", line 202, in <module>
    main()
  File "run_downstream.py", line 198, in main
    eval(f'runner.{args.mode}')()
  File "/home/pyp/s3prl/s3prl/downstream/runner.py", line 202, in train
    dataloader = self.downstream.model.get_dataloader('train')
  File "/home/pyp/s3prl/s3prl/downstream/diarization/expert.py", line 87, in get_dataloader
    dataset = DiarizationDataset(
  File "/home/pyp/s3prl/s3prl/downstream/diarization/dataset.py", line 94, in __init__
    self.data = KaldiData(self.data_dir)
  File "/home/pyp/s3prl/s3prl/downstream/diarization/dataset.py", line 245, in __init__
    self.utt2spk = self._load_utt2spk(os.path.join(self.data_dir, "utt2spk"))
  File "/home/pyp/s3prl/s3prl/downstream/diarization/dataset.py", line 331, in _load_utt2spk
    lines = [line.strip().split(None, 1) for line in open(utt2spk_file)]
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/Libri2Mix/train/utt2spk'
```

I think I might need to change the dirs in ./downstream/diarization/config.yaml
```bash
train_dir: /app/data/Libri2Mix/train
dev_dir: /app/data/Libri2Mix/dev
test_dir: /app/data/Libri2Mix/test
```

But I don't know what them should be, because I couldn't find folder with name "Libri2Mix/train/utt2spk" anywhere in the generated data. The folder of the generated data looks like:

```bash
    Libri2Mix
    ├──Libri2Mix/
         ├──wav16k/
              ├──max/
                  ├──dev/
                  ├──metadata/
                  ├──test/
                  ├──train-100/
                  ├──train-360/   
    LibriSpeech
    wham_noise
```

Thank you!

**Comment by leo19941227** [comment]
Hey @jasonppy ,

Thanks you very much for pointing out. This is indeed a documentation bug after a recent PR.
For the original value you can follow [this link](https://github.com/s3prl/s3prl/blame/eb6c88b41e756329900a10b5d4fff361a4e4d3fd/s3prl/downstream/diarization/config.yaml). I will fix this ASAP.

**Comment by jasonppy** [comment]
Solved, Thx!

**Comment by jordanfranklin1** [comment]
Hi @jasonppy. I ran into a similar bug. Would you be able to help me with this?

**Comment by jasonppy** [comment]
> Hi @jasonppy. I ran into a similar bug. Would you be able to help me with this?

change the below entries at `downstream/diarization/config.yaml' to the following
```yaml
loaderrc:
    ......
    train_dir: ./downstream/diarization/data/train
    dev_dir: ./downstream/diarization/data/dev
    test_dir: ./downstream/diarization/data/test
```
