### ISSUE TITLE
SID: test mode of speaker identification doesn't output accuracy

### ISSUE THREAD

**Issue by jasonppy** [s3prl/s3prl#196]
Hi,

running speaker identification test command doesn't give accuracy as a scalar, I think it output the predictions in the folder where the model is saved.

Consider the test mode of all other tasks print the numbers directly, would you consider also make this one print the number?

thx!

**Comment by leo19941227** [comment]
Wow you are right! Thanks for the suggestion. I missed to do this for SID.
