### ISSUE TITLE
Requirements for finetuning on new data for the downstream ASR?

### ISSUE THREAD

**Issue by ashishBT** [s3prl/s3prl#199]
I have trained the **hubert_large_ll60k** model for **asr** with _LibriSpeech_ data. 
I am using following code to fine-tune the trained model using some new data.

```python
python3 run_downstream.py \
-m train \
-n HUBERT_LARGE_LL60K \
-u hubert_large_ll60k \
-d asr \
-o "config.downstream_expert.datarc.libri_root='/content/drive/My Drive/Colab Notebooks/Dataset/LibriSpeech',,config.downstream_expert.datarc.bucket_file='/content/drive/My Drive/Colab Notebooks/SUPERB/s3prl/data/len_for_bucket'" \
-e result/downstream/HUBERT_LARGE_LL60K/ckpts/states-200000.ckpt
```

I am getting following error:
`RuntimeError: Error(s) in loading state_dict for DownstreamExpert:
   size mismatch for model.linear.weight: copying a param with shape torch.Size([32, 2048]) from checkpoint, the shape in current model is torch.Size([40, 2048]).
   size mismatch for model.linear.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([40]).
`
I understand the main cause from this issue #123 

My trained model has the following symbols 
- `'<s>', '<pad>', '</s>', '<unk>', '|', 'E', 'T', 'A', 'O', 'N', 'I', 'H', 'S', 'R', 'D', 'L', 'U', 'M', 'C', 'W', 'F', 'Y', 'G', 'P', 'B', 'V', 'K', "'", 'X', 'J', 'Q', 'Z'` 

while my new dataset has these symbols 
- `'<s>', '<pad>', '</s>', '<unk>', '|', 'E', 'I', 'R', 'A', 'N', 'O', 'S', 'T', 'H', 'U', 'M', 'P', 'L', 'F', 'C', 'Y', 'D', 'G', 'V', 'W', 'K', '.', 'B', '@', 'X', 'Z', 'Q', 'J', '1', 'madeupword0000', 'madeupword0001', 'madeupword0002', 'madeupword0003', 'madeupword0004', 'madeupword0005'` 

How do I fine-tune this model using the trained checkpoints for new data?

**Comment by leo19941227** [comment]
Hey! You will first need to normalize your new datasets' transcriptions into only the symbols in [this dictionary file](https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/asr/char.dict).
