### ISSUE TITLE
The model rewrite in config is not reflected

### ISSUE THREAD

**Issue by miyazakieiji** [s3prl/s3prl#200]
Hi, thank you for a great repository!

I'm running a downstream task in ER.
I wanted to change the neural network CNNselfAttention to FCN, so I ran the following, but the network doesn't seem to have changed. It is reflected in the config*.yaml in /result/downstream/ExpName.　But the training results are the same as the default (CNNSelfattention)

・The code I ran
python3 run_downstream.py -n ExpName -m train -u fbank -d emotion -c downstream/emotion/config.yaml 
-o "config.downstream_expert.modelrc.DeepModel.model_type='FCN'"

Excuse me, how can I change this to FCN?

**Comment by leo19941227** [comment]
Hey!

You should also change the `modelrc.select` :)

```
python3 run_downstream.py -n ExpName -m train -u fbank -d emotion -c downstream/emotion/config.yaml
-o config.downstream_expert.modelrc.select=DeepModel,,config.downstream_expert.modelrc.DeepModel.model_type=FCN
```

**Comment by miyazakieiji** [comment]
Thanks for the quick reply!

I tried to run the code you gave me, but I got the following error. Is there anything else I need to do?


~/a/s3prl/s3prl master !4 ?1 ❯ python3 run_downstream.py -n ExpName -m train -u fbank -d emotion -c downstream/emotion/config.yaml -o config.downstream_expert.modelrc.select=DeepModel,,config.downstream_expert.modelrc.DeepModel.model_type=FCN

################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################
[hubconf] can not import .upstream.pase.hubconf: No module named 'pase'... Pass.
[Runner] - Start a new experiment
[Override] - config.downstream_expert.modelrc.select = DeepModel
[Override] - config.downstream_expert.modelrc.DeepModel.model_type = FCN
[Featurizer for <class 's3prl.upstream.baseline.expert.UpstreamExpert'>] - The input upstream is only for initialization and not saved in this nn.Module
[Expert] - using the testing fold: "fold1". Ps. Use -o config.downstream_expert.datarc.test_fold=fold2 to change test_fold in config.
[Expert] - Training path: /homes/e-miyazaki/amdhome/IEMOCAP_full_release/meta_data/Session1/train_meta_data_exc.json
[Expert] - Testing path: /homes/e-miyazaki/amdhome/IEMOCAP_full_release/meta_data/Session1/test_meta_data_exc.json
Traceback (most recent call last):
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/run_downstream.py", line 195, in <module>
    main()
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/run_downstream.py", line 190, in main
    runner = Runner(args, config)
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/runner.py", line 47, in __init__
    self.downstream = self._get_downstream()
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/runner.py", line 112, in _get_downstream
    model = Downstream(
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/emotion/expert.py", line 53, in __init__
    model_cls = eval(self.modelrc['select'])
  File "<string>", line 1, in <module>
NameError: name 'DeepModel' is not defined

**Comment by leo19941227** [comment]
Can you try adding

```
from .model import *
```

in the emotion/expert.py's top import area?

**Comment by miyazakieiji** [comment]
I got the following error, what should I do?

~/a/s3prl/s3prl master !4 ?1 ❯ python3 run_downstream.py -n ExpName -m train -u fbank -d emotion -c downstream/emotion/config.yaml -o config.downstream_expert.modelrc.select=DeepModel,,config.downstream_expert.modelrc.DeepModel.model_type=FCN

################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################

[hubconf] can not import .upstream.pase.hubconf: No module named 'pase'... Pass.
Traceback (most recent call last):
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/run_downstream.py", line 15, in <module>
    from s3prl import hub
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/hub.py", line 11, in <module>
    _module = _importlib.import_module(_module_name, package=__package__)
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/anaconda3/envs/intern2021_re/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/__init__.py", line 10, in <module>
    _module = _importlib.import_module(_module_name, package=__package__)
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/anaconda3/envs/intern2021_re/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/emotion/expert.py", line 14, in <module>
    from .model import *
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/emotion/model.py", line 6, in <module>
    from downstream.model import UtteranceLevel_Linear, AttentivePooling, MeanPooling
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/__init__.py", line 10, in <module>
    _module = _importlib.import_module(_module_name, package=__package__)
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/anaconda3/envs/intern2021_re/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/emotion/expert.py", line 14, in <module>
    from .model import *
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/emotion/model.py", line 6, in <module>
    from downstream.model import UtteranceLevel_Linear, AttentivePooling, MeanPooling
ImportError: cannot import name 'UtteranceLevel_Linear' from 'downstream.model' (/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/model.py)

**Comment by leo19941227** [comment]
Hey I think the commit solve the problem. Please feel free to re-open it if you find it not.

**Comment by leo19941227** [comment]
I think the latest commit solve this issue. The DeepModel's interface is a little bit out-of-date. I upgrade it and I think both `CNNSelfAttention` and `FCN` and `DeepNet` work now. Please feel free to re-open the issue if this does not work for you :)

**Comment by miyazakieiji** [comment]
I'm sorry again and again.
I had to redo it with the latest one.
I got the following error, what should I do?

~/amdhome/s3prl/s3prl master ❯ python3 run_downstream.py -n ExpName -m train -u fbank -d emotion -c downstream/emotion/config.yaml -o config.downstream_expert.modelrc.select=DeepModel,,config.downstream_expert.modelrc.DeepModel.model_type=FCN

################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################

[hubconf] can not import .upstream.pase.hubconf: No module named 'pase'... Pass.
[Runner] - Start a new experiment
[Override] - config.downstream_expert.modelrc.select = DeepModel
[Override] - config.downstream_expert.modelrc.DeepModel.model_type = FCN
Traceback (most recent call last):
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/run_downstream.py", line 215, in <module>
    main()
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/run_downstream.py", line 210, in main
    runner = Runner(args, config)
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/runner.py", line 50, in __init__
    self.upstream = self._get_upstream()
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/runner.py", line 106, in _get_upstream
    return self._init_model(
  File "/amd/storage09/data1/PJ/ASR/users/e-miyazaki/s3prl/s3prl/downstream/runner.py", line 65, in _init_model
    assert hasattr(model, interface)
AssertionError

**Comment by leo19941227** [comment]
No, this is my fault. It is not related to emotion recognition. I am now fixing it and will push a fix soon.
Sorry for your inconvenience :(

**Comment by miyazakieiji** [comment]
Thank you, sir, and I'll await your correction.

**Comment by leo19941227** [comment]
Hey thanks for the waiting.
I have pushed a fix for fbank.

**Comment by miyazakieiji** [comment]
Thanks for your quick fix．I'll try it.

**Comment by miyazakieiji** [comment]
I got the following Warning.
Should I be concerned about this?
Or is it not a problem?


[Runner] - Warning: If you are implementing a new task. This message should not appear. Please accept the epoch argument for your downstream's get_dataloader. Also, setting the epoch for DistributedSampler should be already done before returning the dataloader. Please refer to the latest downstream/example/expert.py:get_dataloader. This line is for backward compatibility only.


・The code I ran
 CUDA_VISIBLE_DEVICES=2 python3 run_downstream.py -n hubert_CNN -m train -u hubert -d emotion -c downstream/emotion/config.yaml -o "config.downstream_expert.datarc.test_fold='fold1',,config.downstream_expert.modelrc.select='DeepModel',,config.runner.total_steps=100"

**Comment by miyazakieiji** [comment]
I'm afraid I have one more question. How do I know the structure of the Uttelance level model?

**Comment by leo19941227** [comment]
> I got the following Warning.
> Should I be concerned about this?
> Or is it not a problem?
> 
> [Runner] - Warning: If you are implementing a new task. This message should not appear. Please accept the epoch argument for your downstream's get_dataloader. Also, setting the epoch for DistributedSampler should be already done before returning the dataloader. Please refer to the latest downstream/example/expert.py:get_dataloader. This line is for backward compatibility only.
> 
> ・The code I ran
> CUDA_VISIBLE_DEVICES=2 python3 run_downstream.py -n hubert_CNN -m train -u hubert -d emotion -c downstream/emotion/config.yaml -o "config.downstream_expert.datarc.test_fold='fold1',,config.downstream_expert.modelrc.select='DeepModel',,config.runner.total_steps=100"

Hi this message is just warning and is not an error.

**Comment by leo19941227** [comment]
> I'm afraid I have one more question. How do I know the structure of the Uttelance level model?

Here!
https://github.com/s3prl/s3prl/blob/ed9512709165bf4738817c04f5b529fc9bd7afc5/s3prl/downstream/model.py#L35-L44

**Comment by raotnameh** [comment]
@miyazakieiji The Data does not have metadata folder. How did you create it?

**Comment by bagustris** [comment]
@raotnameh 

The new version of s3prl has this `meta_data` folder inside `emotion`. You can also create it by yourself by running [IEMOCAP_preprocess.py](https://github.com/s3prl/s3prl/blob/main/s3prl/downstream/emotion/IEMOCAP_preprocess.py) inside `emotion` director with a path of your data.

**Comment by raotnameh** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/data/part4/superb/s3prl/s3prl/datasets/IEMOCAP_full_release/meta_data/Session1/train_meta_data.json'

@bagustris How do I create it?

**Comment by raotnameh** [comment]
@bagustris Thank you so much.
