### ISSUE TITLE
Installation issue with python 3.6, pytorch 1.7 in a conda env

### ISSUE THREAD

**Issue by j4sonzhao** [s3prl/s3prl#209]
Hi there,

I'm trying to run this codebase, but when I run this command 

`pip install -e ./`

in step 3 of installation, I get an error stating something about pytorch 1.7:

![image](https://user-images.githubusercontent.com/10427604/134827259-f7b058c8-b764-43ff-b33d-164e6bf6a514.png)

I had previously tried this command with a env with pytorch 1.5 as well, and ran into the same issue.

**Comment by leo19941227** [comment]
This is weird... The information is kind of not sufficient to diagnose the problem.
Could you try your installation process on colab to see the issue is reproducible?

**Comment by j4sonzhao** [comment]
Sorry, resolved! Turns out there was a problem with the pytorch install on the special machine that I'm running on.

**Comment by leo19941227** [comment]
Cool! Glad to know that!
