### ISSUE TITLE
Questions on pre-training with DDP

### ISSUE THREAD

**Issue by kaen2891** [s3prl/s3prl#210]
Hello, first of all, I would like to thank you for providing this great platform for us.

I got a question about using multi-GPU with DDP.

I would like to pre-train with multi-GPU using Pytorch DDP. Is the s3prl support the DDP in the pre-training process?

The reason why I ask this is: in the downstream task, instructions are provided in case when we want to use DDP.(https://github.com/s3prl/s3prl/tree/44973c991e010af48509f5c9ce36a15e9d33166e/s3prl/downstream)

As mentioned below:

```
python3 $distributed run_downstream.py -m train -n ExpName -u fbank -d example \
    -o config.runner.gradient_accumulate_steps=2
```

we have to insert the `distributed` in the command line.

However, in the Pre-training pages (https://github.com/s3prl/s3prl/tree/master/s3prl/pretrain), it is simply noted as `--multi-gpu` as below:
```
On multiple GPUs, add --multi_gpu
```
If we have 4 GPUs and type `--multi-gpu True`, is this pre-train Runner support the DDP? 

Further, do we have to change the gradient_accumulate_steps=4 as 1?

Thanks a lot.

**Comment by leo19941227** [comment]
Hi, thanks for your interest!
However it seems we will not support DDP for pretraining in the short run. You can refer to this issue https://github.com/s3prl/s3prl/issues/158

**Comment by kaen2891** [comment]
Thanks for the helpful comment
