### ISSUE TITLE
[BUG] import non-exist expert.py

### ISSUE THREAD

**Issue by KeiKinn** [s3prl/s3prl#225]
There is no expert.py to import. It should be a bug

https://github.com/s3prl/s3prl/blob/7ffac4b130fc9e7dcece30638f9e941740b2a03d/s3prl/downstream/runner.py#L129

**Comment by KeiKinn** [comment]
Hi, thank you for your quick reply. That makes sense.

If the feature is still in development, I suggest that maybe you could separate it in dev branch or dev/staging phase.

Nice work!

**Comment by leo19941227** [comment]
You are right. I should add the doc ASAP about the connection to huggingface's Hub.
Thanks again for the suggestion!
