### ISSUE TITLE
Cannot download the dataset Fluent Speech Commands

### ISSUE THREAD

**Issue by D-Keqi** [s3prl/s3prl#234]
I try to download the dataset Fluent Speech Commands for the 'IC: Intent Classification' task, but even after I use the command "wget http://140.112.21.28:9000/fluent.tar.gz". I still fail to download. I am wondering if there are some issues with this link? Can I get some suggestions?

**Comment by xiaoxue1117** [comment]
Hi I also cannot download the fluent Speech Commands from all the following links.

1.http://fluent.ai:2052/jf8398hf30f0381738rucj3828chfdnchs.tar.gz
2.wget http://140.112.21.28:9000/fluent.tar.gz

Could you please provide a new link? Thank you!

**Comment by nikvaessen** [comment]
For those looking for the dataset anno 2024, it seems it's available at https://www.kaggle.com/datasets/tommyngx/fluent-speech-corpus
