### ISSUE TITLE
Evaluation metric for Phoneme Recognition

### ISSUE THREAD

**Issue by WeiChen-Hsu-NTUEE** [s3prl/s3prl#239]
In [SUPERB](https://arxiv.org/abs/2105.01051), it says that the evaluation metric of Phoneme Recognition is phone error rate (PER), but the output of dev/test only have loss and WER.

@andi611

**Comment by andi611** [comment]
@leo19941227 I think our output log message for PR should say "PER" instead of "WER", is that correct?

**Comment by leo19941227** [comment]
Could @WeiChen-Hsu-NTUEE please help add a new metric `per` which simply calls `wer` in

https://github.com/s3prl/s3prl/blob/348b6612c11ca77c5f3a618a283e7d68bb65ce9e/s3prl/downstream/ctc/metric.py#L14-L22

and change the config file to use `per`?

https://github.com/s3prl/s3prl/blob/348b6612c11ca77c5f3a618a283e7d68bb65ce9e/s3prl/downstream/ctc/libriphone.yaml#L79-L80

I think these two changes are sufficient to fix the misleading wer information, but might need some effort to test it.
Thanks!

**Comment by WeiChen-Hsu-NTUEE** [comment]
@leo19941227 Sure! However I am kind of occupied these days. Please give me some time to finish my current work on hand, and then I'll try fix it asap!
