### ISSUE TITLE
ASR test result

### ISSUE THREAD

**Issue by liu-x-p** [s3prl/s3prl#243]
Hi, in the paper for SUPERB, WER of TERA is 18.45 without LM and 12.44 with LM. 
I used librispeech 960h to train TERA, and tested it with ASR task. The WER on test-clean was 18.61 without LM, but when I used LM with the default parameters, the WER was 85.98. I changed the parameters but WER was more than 80. I don't what's wrong with it, could you have some ideas?

**Comment by leo19941227** [comment]
In my experience, the reason behind this issue is mostly the incorrect installation of fairseq and flashlight. Can you share your flashlight and fairseq version? (commit hash)

**Comment by liu-x-p** [comment]
@leo19941227 I installed this two packages last month with the newest version that time. Should I revert to earlier version?
