### ISSUE TITLE
Speed up extracting audio lengths by torchaudio.info

### ISSUE THREAD

**Issue by nateanl** [s3prl/s3prl#244]
In https://github.com/s3prl/s3prl/blob/master/s3prl/preprocess/generate_len_for_bucket.py#L56 the length of the audio is extracted by loading the waveform and returning the size of it. It can be optimized by using ``torchaudio.info`` which reads the meta data and returns ``num_frames``.

**Comment by leo19941227** [comment]
Hi @nateanl !

You are right, I will do this.
Thanks for the suggestion.
