### ISSUE TITLE
Support of Distributed Pre-Training and more methods?

### ISSUE THREAD

**Issue by houwenxin** [s3prl/s3prl#251]
Hi, thanks for your efforts in this wonderful project! I have been enjoying it. I am curious about whether you have recent plans of supporting distributed pre-training for TERA, and MockingJay, etc.? And do you have plan integrate more pre-training methods in this project?

**Comment by andi611** [comment]
Hi, thanks for liking our project!

I'm currently working on improving the functionality of the pre-training part.
And we will definitely include more pre-training methods (In progress!!), 
starting with APC, VQ-APC, and NPC. 

The new changes will be on a new branch (`update_pretrain`), 
once they are fully tested we will merge them back to master.
Thanks for the wait.

**Comment by houwenxin** [comment]
Cool! Thanks so much for your efforts!
