### ISSUE TITLE
Why do you need the specfic version fairseq?

### ISSUE THREAD

**Issue by MingjieChen** [s3prl/s3prl#252]
Hello,

OS: Linux
Python:3.7.1
Env:Conda venv

I am trying to install fairseq using command
`pip install fairseq@git+https://github.com//pytorch/fairseq.git@f2146bdc7abf293186de9449bfa2272775e39e1d#egg=fairseq
`

Then here is the error:

Collecting fairseq@ git+https://github.com//pytorch/fairseq.git@f2146bdc7abf293186de9449bfa2272775e39e1d#egg=fairseq
Cloning https://github.com//pytorch/fairseq.git (to revision f2146bdc7abf293186de9449bfa2272775e39e1d) to /tmp/pip-install-1fohdccz/fairseq_dd59b7f3d0484253a690d1dcd5239186
Running command git clone -q https://github.com//pytorch/fairseq.git /tmp/pip-install-1fohdccz/fairseq_dd59b7f3d0484253a690d1dcd5239186
Running command git rev-parse -q --verify 'sha^f2146bdc7abf293186de9449bfa2272775e39e1d'
Running command git fetch -q https://github.com//pytorch/fairseq.git f2146bdc7abf293186de9449bfa2272775e39e1d
Running command git checkout -q f2146bdc7abf293186de9449bfa2272775e39e1d
Resolved https://github.com//pytorch/fairseq.git to commit f2146bdc7abf293186de9449bfa2272775e39e1d
Running command git submodule update --init --recursive -q
fatal: reference is not a tree: adb23324c222aad0aad89308e70302d996a5eaeb
Unable to checkout 'adb23324c222aad0aad89308e70302d996a5eaeb' in submodule path 'fairseq/model_parallel/megatron'
WARNING: Discarding git+https://github.com//pytorch/fairseq.git@f2146bdc7abf293186de9449bfa2272775e39e1d#egg=fairseq. 
Command errored out with exit status 1: git submodule update --init --recursive -q Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement fairseq (unavailable) (from versions: 0.6.1, 0.6.2, 0.7.1, 0.7.2, 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.10.2)
ERROR: No matching distribution found for fairseq (unavailable)

Any idea to solve this?

Thanks

**Comment by MingjieChen** [comment]
It seems to me the required specific version of fairseq can no be found through git.

**Comment by leo19941227** [comment]
Hi

I can't reproduce this issue, but I think actually you don't need this specific version of fairseq.
You just need the version after some specific bug-fixing commits and the current stable version of fairseq does not include those commits.
So, you can try to simply clone down the latest fairseq and install it locally.
