### ISSUE TITLE
pretrained inner layers

### ISSUE THREAD

**Issue by maziye-azad** [s3prl/s3prl#253]
hi,thank you for your work.

i have downloaded the pretrained mockingjay and i want to accsses the inner layers?

i want to choose some layers with weight for transfer learning.

what shoud i do?any help is appreciated!

**Comment by leo19941227** [comment]
Hi, 

If you feed a list for waveforms into the pretrained mockingjay, it should return a dictionary. Use `hidden_states` key to access all the hidden layer representations.
If this is not clear to you, please show an example on what did you download and I can see how to help.
Thanks!

**Comment by maziye-azad** [comment]
thank you for your answer. 
the mockingjay has 12 transformer layers and i want to make a student model with 4 transformer layers that are obtained from the teacher(mockingjay) .so from every 3 layers of mockingjay model i want to take one with the weights to use in my student model. i dont want their output but their model and weights.
the problem is that i dont know how  i can accsess these layers and their weights for distillation and using in another model.

**Comment by leo19941227** [comment]
Hi,

I think for the weights you can simply use the PyTorch API: model.named_paramaters(), and trace the Mockingjay's model source code (start from upstream/mockingjay/expert.py) to know how the input propagate through the model to the output.

**Comment by maziye-azad** [comment]
I will try that, thank you for your help!
