### ISSUE TITLE
Diarization online scoring problem of SUPERB leaderboard submission

### ISSUE THREAD

**Issue by Sanyuan-Chen** [s3prl/s3prl#254]
Hi,

When I finetune the pre-trained model with 320 upstream_rate on diarization task and submit the prediction files to the SUPERB leaderboard, the online results would be much worse than the results I got locally.
I find the submit.py script only copies the diarization prediction directory without the upstream_rate_file, so I guess the online system score the diarization task with the 160 upstream_rate by default, leading to inconsistent results.

**Comment by leo19941227** [comment]
Oh! You are right!
Thanks for pointing out.
I am fixing this.

**Comment by leo19941227** [comment]
Dear @Sanyuan-Chen ,

I have fixed the issue.
Please pull the latest master, re-inference the checkpoint, and re-submit the expdir :)
Previously while you submitted WavLM this `upstream_rate` (in the latest commit I change to the `frame_shift`) was not required. But after this PR (https://github.com/s3prl/s3prl/pull/202) it is required. So your latest trained downstream model will not this file to do the scoring properly. You can refer to the PR page for more info.
