### ISSUE TITLE
predicted emotion is from last checkpoint instead of dev-best?

### ISSUE THREAD

**Issue by bagustris** [s3prl/s3prl#259]
I am in doubt whether the following is bug or by-intention.

In the emotion task, where the prediction file will be submitted for benchmarking, the generated prediction is from the 
last steps instead of the dev-best step. Particularly this code:

https://github.com/s3prl/s3prl/blob/3854f33867f3136ab97f5389578f4355ef6c660e/s3prl/downstream/emotion/expert.py#L142-L145

If that part is by intention. Is it fair if we want to submit the prediction from dev-best or even from test-best?

**Comment by leo19941227** [comment]
Hi @bagustris ,

If you only run the training command, indeed you will get the incorrect prediction files generated from the last step. You can refer to the "Leaderboard submission" part in superb.md doc,  where you should submit the prediction files AFTER the testing command. Specifically, the testing command for emotion should be

python3 run_downstream.py -m evaluate -e expdir/dev-best.ckpt

**Comment by bagustris** [comment]
Ah, I see, thanks @leo19941227!

I think I can move that part of the code under the last best-dev.ckpt so I don't need to run the testing command.

**Comment by leo19941227** [comment]
Cool! Let me know if you have further question.
