### ISSUE TITLE
Error: a2a-vc-vctk training crash with internal argument error

### ISSUE THREAD

**Issue by tarepan** [s3prl/s3prl#260]
## Summary
a2a-vc-vctk training crash with default setup.  
Error message says that there is internal argument error in training loop.  
It seems to be caused by wrong tqdm arguments.  

## Config
master 3a90635e2ff546f2023813bf4b9ebaa576425023

## Situation
Execute training of a2a-vc-vctk as in the [README](https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/a2a-vc-vctk/README.md).  
When `./downstream/a2a-vc-vctk/vc_train.sh` run, it normally execute `train` and `dev` steps.  
Just after `dev` step (maybe test step starting), the training crash with error.  

## Error
```
dev:  99% 107/108 [02:37<00:00,  1.21it/s]

dev: 100% 108/108 [02:37<00:00,  1.46s/it]
train:   0% 0/7167 [02:46<?, ?it/s]
Traceback (most recent call last):
  File "run_downstream.py", line 219, in <module>
    main()
  File "run_downstream.py", line 215, in main
    eval(f'runner.{args.mode}')()
  File "/content/s3prl/s3prl/downstream/runner.py", line 362, in train
    save_names += self.evaluate(split, logger, global_step)
  File "/content/s3prl/s3prl/downstream/runner.py", line 465, in evaluate
    total_batch_num = len(dataloader),
  File "/content/s3prl/s3prl/downstream/a2a-vc-vctk/expert.py", line 196, in log_records
    for i, (wav_path, ref_spk_name) in enumerate(tqdm(list(zip(records["wav_paths"], records["ref_spk_names"]), dynamic_ncols=True, desc="Saving files"))):
TypeError: list() takes no keyword arguments
```

## Expected Cause
The error occurs here.  
https://github.com/s3prl/s3prl/blob/9798ce4f492b718b2aa42dc7d2516f2a296a153b/s3prl/downstream/a2a-vc-vctk/expert.py#L196

The tqdm part seems to be wrong (we can see it in below pretty-printed tqdm part).  
```python
enumerate(
    tqdm(
        list(
            zip(records["wav_paths"], records["ref_spk_names"]),
            dynamic_ncols=True, desc="Saving files"
        )
    )
)
```
`dynamic_ncols=True, desc="Saving files"` may be the arguments of tqdm, but it is with in `list` function.  
This seems to be cause the syntax error.  

## How to Fix
I made draft pull request #261.  
It totally fix the problem.  
Can I make it PR (from draft PR) ?  

## Others
It seems that @unilight is good as reviewer (original code comitter).

**Comment by unilight** [comment]
Hi @tarepan, thank you for reporting this! Yes, please make a PR for this!
