### ISSUE TITLE
Fluent Speech Commands data link all unavailable

### ISSUE THREAD

**Issue by nobel861017** [s3prl/s3prl#264]
Hi, 
I am currently trying to download the Fluent Speech Commands dataset.  However, all links provided are unavailable.
http://fluent.ai:2052/jf8398hf30f0381738rucj3828chfdnchs.tar.gz
http://140.112.21.28:9000/fluent.tar.gz

**Comment by leo19941227** [comment]
I have re-launched a multi-threaded python static server which avoids the hang when multiple requests come in the same time. I believe this issue is resolved, please feel free to reopen it if you find otherwise.

**Comment by nikvaessen** [comment]
For those looking for the dataset anno 2024, it seems it's available at https://www.kaggle.com/datasets/tommyngx/fluent-speech-corpus
