### ISSUE TITLE
cant use WavLM as upstream

### ISSUE THREAD

**Issue by OG-algo** [s3prl/s3prl#267]
using:
-m train -n WavLM_exp -u wavlm -d sv_voxceleb1 -s hidden_states -l -1

I get the following error:
AttributeError: module 's3prl.hub' has no attribute 'wavlm'

thanks

**Comment by leo19941227** [comment]
This is typically due to unsuccessful installation of S3PRL.
Could you please detail how you install it?

**Comment by OG-algo** [comment]
I'm working on windows so I am using the downloaded git and did pip install s3prl.

using Hubert is working fine: 
-m train -n HuBERT_exp -u hubert -d sv_voxceleb1 -s hidden_states -l -1

**Comment by leo19941227** [comment]
Cool! Then I guess the reason is that our uploaded Pypi version is out-of-date and most supported upstreams are in the master branch only.
Is it possible for you (Windows) to install the editable version?
```
pip install -e ./
```
