### ISSUE TITLE
Addition of cross-lingual model: XLS-R

### ISSUE THREAD

**Issue by tarun360** [s3prl/s3prl#269]
Hi!

I was wondering if you were planning to add XLS-R model was proposed in "XLS-R: Self-supervised Cross-lingual Speech Representation Learning at Scale"?

Thank you

**Comment by abnerLing** [comment]
It's pretty easy to add it yourself into the upstream/wav2vec2/hubconf.py file. For example 
```
def wav2vec2_xlsr_300m(refresh=False, *args, **kwargs):
    """
        The Large model
            refresh (bool): whether to download ckpt/config again if existed
    """
    kwargs['ckpt'] = 'https://dl.fbaipublicfiles.com/fairseq/wav2vec/xlsr2_300m.pt'
    return wav2vec2_url(refresh=refresh, *args, **kwargs)
```
I did it with my forked version and it works.
https://github.com/abnerLing/s3prl/blob/master/s3prl/upstream/wav2vec2/hubconf.py

```
import s3prl.hub as hub
import torchaudio

>>> audio, sr = torchaudio.load('test.wav')
>>> model = getattr(hub, 'wav2vec2_xlsr_300m')()
>>> reps = model(audio)["last_hidden_state"]
>>> print(reps.shape)
torch.Size([1, 1249, 1024])

>>> model = getattr(hub, 'wav2vec2_xlsr_1b')()
>>> reps = model(audio)["last_hidden_state"]
>>> print(reps.shape)
torch.Size([1, 1249, 1280])

>>> model = getattr(hub, 'wav2vec2_xlsr_2b')()
>>> reps = model(audio)["last_hidden_state"]
>>> print(reps.shape)
torch.Size([1, 1249, 1920])
```

**Comment by tarun360** [comment]
Thanks a lot for your reply! This does solve the problem. However, is there some way to do it without making changes in the s3prl code? I do not wish to first make a fork, then make changes in that, and then install it. 

In case it could be done without touching the internals of s3prl, that would be great.

**Comment by leo19941227** [comment]
Hi,

You can try to use `wav2vec2_url` by assigning the correct fairesq url.

**Comment by tarun360** [comment]
Thanks, that solves my issue.
