### ISSUE TITLE
Benchmark results for downstream tasks not in SUPERB

### ISSUE THREAD

**Issue by MingjieChen** [s3prl/s3prl#270]
Hello,

Is it possible to provide some benchmark results for downstream tasks that do not belong to SUPERB? 

For example, libri_phone, phone_linear, ...

Thanks

**Comment by andi611** [comment]
Hi, 
Benchmark results of:
`phone_linear,  phone_linear_concat, phone_1hidden, timit_phone_linear, ...` and
`speaker_linear_frame_libri, speaker_linear_utter_libri`
can be found in the [TERA paper](https://arxiv.org/abs/2007.06028) (Table II).
