### ISSUE TITLE
Inference support in downstream? (feature request)

### ISSUE THREAD

**Issue by TimothyTse1997** [s3prl/s3prl#272]
I am experimenting with the downstream task of a2a_vc_vctk, however, the current infrastructure doesn't have good support for creating inference modules from checkpoints, which will be a great feature for a) importing to other repositories b) general applications and deployments. 

Are there any plans for implementing similar features? Thanks

**Comment by unilight** [comment]
Hi @TimothyTse1997 , thank you for raising this issue. I understand the shortcoming of the current implementation since it is mainly for benchmarking the upstreams. However there are lots of ways to improve it, depending on the application. Can you be a more specific about what you would like to achieve?

**Comment by TimothyTse1997** [comment]
I was comparing different approaches (starganv2-VC, AutoVC etc.) in voice conversion in OOD intralingual settings

The biggest problem (or inconvenience, since it's not a bug) I had during inference (for MOS scores in my own datasets) is the upstream model's config was not logged, after a while, I would have to create a pipeline for each upstream model and load them manually for each experiment (partially due me not being familiar with the hub option), and managing them is not quite straight forward as I would also like to try out different settings in upstream. 

Although not being the purpose of the current implementation, I believe this feature could really help others using this repo for researches, especially people wanting to compare with approaches currently outside the scope of S3PRL. The most obvious improvement (in my view) would be storing all on-the-fly created objects/their configs (Featurizer, imported upstream models). A more general approach could be to create another object (similar to runner.py) which load the up + downstream module given all configs for inference purposes.

none-the-less, thanks for the quick reply

**Comment by unilight** [comment]
> the upstream model's config was not logged, after a while, I would have to create a pipeline for each upstream model and load them manually for each experiment

> as I would also like to try out different settings in upstream.

> The most obvious improvement (in my view) would be storing all on-the-fly created objects/their configs (Featurizer, imported upstream models).

Sorry, I do not quite understand the scenario you describe. I assume you have trained the downstream A2A VC models, right? Not sure if you are aware of this, but actually during training we run the inference process every 1000 steps (this interval can be configured) and save the generated acoustic feature files. In other words, we don’t need to rerun inference again after the training process is done. I guess this is enough if you want to benchmark the performance and compare with other methods that are not based on S3PRL, right? Or is there something you want to do that I am missing, such that loading the mode weights again is necessary?

**Comment by TimothyTse1997** [comment]
Yes, I want to do evaluation on other OOD (out of distribution) datasets. Yes, I can just convert my datasets in a format easy to process by the current pipeline, but I would rather have a more "agile" option, allowing users to use the model on their own. As I said, it is not a bug, but rather something I believe would improve other's experience using the codebase

**Comment by unilight** [comment]
This solution does not sound so common to me… In my experience of using other open source toolkits (ESPNet and fairseq), if you want to test on other datasets, I think it is natural to do a bit of coding by yourself. Or you can tell me what dataset you want to use and I can help you write the necessary files (mainly `dataset.py`

**Comment by unilight** [comment]
(Sorry I accidentally closed the issue… reopened it.)

**Comment by TimothyTse1997** [comment]
So, basically what happened to me is: I trained with a set of configs, but only then I was requested to evaluate some more out-of-scope datasets; to avoid retraining all the models, I tried to inference different models individually and found the implementation is not straightforward. If there are better approaches I'm all ears.

Sorry for being misleading

**Comment by unilight** [comment]
I've sent a PR (#284) to support custom decoding.

**Comment by TimothyTse1997** [comment]
Mr. Huang,

I appreciate that the dev team of s3prl decide to provide this new feature
even though it is not the initial purpose of the codebase. I hope more
people will recognize this repo as their goto for Pretraining benchmark.

For something that is not related, I suggested the codebase to others and
finally got a shout-out on the youtube channel YannicKilcher
https://www.youtube.com/watch?v=yVKiMh2vEWQ
(time: 15:50)

I myself am active in that channel for the mix-environment of academic and
industrial take on machine learning development; their discord channel has
a lot of active researchers/devs, including members from EleutherAI, which
host regular (paper) discussions and community projects (currently, they
are building MoE model in Jax I believe). Feel free to come by.

Best Regards,
Timothy Tse

Wen-Chin Huang (unilight) ***@***.***> 於 2022年1月27日 週四
下午5:55寫道：
