### ISSUE TITLE
MOS prediction

### ISSUE THREAD

**Issue by adrianastan** [s3prl/s3prl#273]
Hi,

I am trying to run the MOS prediction model using the sample code available here: https://github.com/s3prl/s3prl/tree/master/s3prl/upstream/mos_prediction , yet I keep getting the following error: 

`ImportError: cannot import name 'mos_wav2vec2' from 's3prl.hub' (/usr/local/lib/python3.7/dist-packages/s3prl/hub.py)`

Any ideas why this happens?

Thanks!

**Comment by leo19941227** [comment]
Can you provide the full list of `pip list`?
Thanks!

**Comment by adrianastan** [comment]
Sure, please see below:

Package                 Version        
----------------------- ---------------
absl-py                 1.0.0          
aiohttp                 3.8.1          
aiosignal               1.2.0          
antlr4-python3-runtime  4.8            
appdirs                 1.4.4          
asteroid                0.4.4          
asteroid-filterbanks    0.4.0          
async-timeout           4.0.2          
attrs                   21.4.0         
audioread               2.1.9          
beautifulsoup4          4.10.0         
cached-property         1.5.2          
cachetools              4.2.4          
catalyst                21.12          
certifi                 2021.10.8      
cffi                    1.15.0         
charset-normalizer      2.0.10         
click                   8.0.3          
colorama                0.4.4          
cycler                  0.11.0         
Cython                  0.29.26        
decorator               5.1.1          
dtw-python              1.1.6          
easydict                1.9            
editdistance            0.6.0          
einops                  0.3.2          
fairseq                 1.0.0a0+f2146bd
filelock                3.4.2          
fonttools               4.28.5         
frozenlist              1.2.0          
fsspec                  2021.11.1      
future                  0.18.2         
gdown                   4.2.0          
google-auth             2.3.3          
google-auth-oauthlib    0.4.6          
grpcio                  1.43.0         
h5py                    3.6.0          
huggingface-hub         0.2.1          
hydra-core              1.0.7          
hydra-slayer            0.4.0          
idna                    3.3            
importlib-metadata      4.10.0         
importlib-resources     5.4.0          
intervaltree            3.1.0          
joblib                  1.1.0          
julius                  0.2.6          
kaldi-io                0.9.4          
kiwisolver              1.3.2          
librosa                 0.8.1          
llvmlite                0.37.0         
lxml                    4.7.1          
Markdown                3.3.6          
matplotlib              3.5.1          
mir-eval                0.6            
multidict               5.2.0          
nltk                    3.6.7          
normalise               0.1.8          
numba                   0.54.1         
numpy                   1.20.0         
oauthlib                3.1.1          
omegaconf               2.0.6          
packaging               21.3           
pandas                  1.3.5          
pb-bss-eval             0.0.2          
pesq                    0.0.3          
Pillow                  9.0.0          
pip                     20.0.2         
pkg-resources           0.0.0          
pooch                   1.5.2          
portalocker             2.3.2          
protobuf                3.19.1         
pyasn1                  0.4.8          
pyasn1-modules          0.2.8          
pycparser               2.21           
pyDeprecate             0.3.1          
pyparsing               3.0.6          
pysndfx                 0.3.6          
PySocks                 1.7.1          
pystoi                  0.3.3          
python-dateutil         2.8.2          
pytorch-lightning       1.5.8          
pytorch-ranger          0.1.1          
pytz                    2021.3         
PyYAML                  6.0            
regex                   2021.11.10     
requests                2.27.1         
requests-oauthlib       1.3.0          
resampy                 0.2.2          
roman                   3.3            
rsa                     4.8            
s3prl                   0.3.1          
sacrebleu               2.0.0          
sacremoses              0.0.47         
scikit-learn            1.0.2          
scipy                   1.7.3          
setuptools              44.0.0         
six                     1.16.0         
sortedcontainers        2.4.0          
SoundFile               0.10.3.post1   
soupsieve               2.3.1          
sox                     1.4.1          
tabulate                0.8.9          
tensorboard             2.7.0          
tensorboard-data-server 0.6.1          
tensorboard-plugin-wit  1.8.1          
tensorboardX            2.1            
threadpoolctl           3.0.0          
tokenizers              0.10.3         
torch                   1.10.1         
torch-optimizer         0.3.0          
torch-stoi              0.1.2          
torchaudio              0.10.1         
torchmetrics            0.6.2          
torchvision             0.11.2         
tqdm                    4.62.3         
transformers            4.15.0         
typing-extensions       4.0.1          
urllib3                 1.26.8         
Werkzeug                2.0.2          
wheel                   0.37.1         
yarl                    1.7.2          
zipp                    3.7.0

**Comment by leo19941227** [comment]
How did you install s3prl?
Is it `pip install s3prl` or `pip install -e ./` from the local repo?
Our distributed PyPi package is out-of-date and does not contain mos-wav2vec2 yet.
For the latest support you can try to install the latest master.
Thanks!

**Comment by adrianastan** [comment]
Great! Thanks, it works now.

Best,
Adriana
