### ISSUE TITLE
DistilhHubert issue

### ISSUE THREAD

**Issue by levtelyatnikov** [s3prl/s3prl#274]
Error message:`ImportError: cannot import name 'distilhubert' from 's3prl.hub' (/usr/local/lib/python3.7/dist-packages/s3prl/hub.py)`

Colab notebook link: https://colab.research.google.com/drive/1ZOZtCir3LmzV7sgDLai79-YwCrxTR7UG?usp=sharing

**Comment by leo19941227** [comment]
Hi,

Please don't install our Pypi package via `pip install s3prl`.
Please clone the repo and install at loca
```
git clone https://github.com/s3prl/s3prl.git
cd s3prl
pip install -e ./

```
