### ISSUE TITLE
S3PRL-VC: Voice conversion inference

### ISSUE THREAD

**Issue by abnerLing** [s3prl/s3prl#276]
This might be a dumb question but how can I convert a voice given a pretrained model. For example, after training a model using the below code I have a few custom .wav files of a single speaker that I want to convert to TEF1.
```
python run_downstream.py -m train -n a2o_vc_vcc2020_taco2_ar_TEF1_wav2vec -u wav2vec -d a2o-vc-vcc2020 
```

**Comment by unilight** [comment]
@abnerLing I think you need to look into dataset.py and see how the testing data is loaded. I will consider this as a feature request, so let me know if you have problems. Thanks!

**Comment by unilight** [comment]
I've sent a PR (#284) to support custom decoding.

**Comment by abnerLing** [comment]
That's great! I've been manually modifying the dataset.py file and preparing the data separately which works fine, but having a custom feature sounds very convenient. Thank you very much!
