### ISSUE TITLE
Very long leading silence in synthesized speech in a2a-vc-vctk

### ISSUE THREAD

**Issue by seastar105** [s3prl/s3prl#278]
Hi, I'm trying to use any-to-any voice conversion in this repo.

First, I trained successfully with vq_wav2vec upstream. Then tried with unseen speaker for both target and source. Both speakers are not in vctk, not in vcc2020.

Here's some result with hifigan. 

![image](https://user-images.githubusercontent.com/30820469/149938581-77b15a41-541a-4de0-b66e-e3edb15ab7ee.png)

It's waveform image opened in audacity. As you see there's long leading silence. Fortunately, voice at end is audible. It takes too long in taco2 because of leading silence.

Why does it happen and how can i resolve it?

**Comment by unilight** [comment]
Hi @seastar105 , can you show me the source waveform visualizations? Does the source waveform has a long leading silence? Also, what is the sampling rate of the source waveform? Is it in 24kHz?

**Comment by seastar105** [comment]
@unilight

Yes, source wave has leading silence. I didn't notice that, it works properly with trimmed source wave. sorry for dumb question.. 

also it has been downsampled from lossy audio with 48kHz to 24kHz.
