### ISSUE TITLE
Error in using FMLLR features for ASR

### ISSUE THREAD

**Issue by Sindhu-Hegde** [s3prl/s3prl#279]
Hi, 
Thank you so much for the wonderful code.
I am trying a few ASR experiments using TERA. I was able to pre-train TERA on LibriSpeech and also fine-tune for ASR task and replicate the SUPERB paper scores (~**18** without LM and ~**12** with LM).
Now, the TERA paper says that using **FMLLR features** works the best for ASR. I am trying to use these features but I am facing some issues. Here are the details:
1) I downloaded the LibriSpeech FMLLR data from the drive (https://drive.google.com/file/d/1sWWR-N4z6hAs1ktxFXyFCYkc67DOXrBH/view?usp=sharing)
2) I downloaded the FMLLR pre-trained TERA checkpoint along with the config file (https://drive.google.com/drive/folders/1e_5OqeDUtTVh--gePkqpafKiqKtJ1avZ?usp=sharing)
3) However, now when I try to use this pre-trained model and train the downstream ASR task, it throws error while loading the model. This config file is different from that of the config file released in the repo. 

Code I am running:
`python3 run_downstream.py -m train -n asr_tera_fmllr -u tera_local -k states-1000000.ckpt -d asr -g libri_fmllrBase.yaml
`

Error:
```
[Runner] - Start a new experiment
[UpstreamExpert] - Using upstream expert config file from: ../libri_fmllrBase.yaml
Traceback (most recent call last):
  File "run_downstream.py", line 219, in <module>
    main()
  File "run_downstream.py", line 214, in main
    runner = Runner(args, config)
  File "/opt/sindhu/exp3/s3prl/s3prl/downstream/runner.py", line 94, in __init__
    self.upstream = self._get_upstream()
  File "/opt/sindhu/exp3/s3prl/s3prl/downstream/runner.py", line 153, in _get_upstream
    refresh = upstream_refresh,
  File "/opt/sindhu/s3prl_repo/s3prl/upstream/tera/hubconf.py", line 27, in tera_local
    return _UpstreamExpert(ckpt, *args, **kwargs)
  File "/opt/sindhu/s3prl_repo/s3prl/upstream/interfaces.py", line 30, in __call__
    instance = super().__call__(*args, **kwargs)
  File "/opt/sindhu/s3prl_repo/s3prl/upstream/mockingjay/expert.py", line 51, in __init__
    self.transformer = PretrainedTransformer(options, inp_dim=-1)
  File "/opt/sindhu/s3prl_repo/s3prl/upstream/mockingjay/builder.py", line 265, in __init__
    super(PretrainedTransformer, self).__init__(options, inp_dim, config, online_config, verbose)
  File "/opt/sindhu/s3prl_repo/s3prl/upstream/mockingjay/builder.py", line 51, in __init__
    self.all_states = torch.load(options["ckpt_file"], map_location='cpu')
  File "/opt/sindhu/s3prl/lib/python3.6/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/sindhu/s3prl/lib/python3.6/site-packages/torch/serialization.py", line 787, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'transformer'
```

Any help would be greatly appreciated.

**Comment by andi611** [comment]
Hi, 
I don't think `run_downstream.py`, and the wrapper (s3prl/upstream/mockingjay/expert.py) supports the "fmllr" feature atm.

The reason is, "fmllr" features need to be pre-computed over the whole dataset, 
therefore we won't be able to do on-the-fly feature extraction for "fmllr".
(the downstream runner requires "on-the-fly feature extraction" to work)

I hope this explanation helps.

**Comment by Sindhu-Hegde** [comment]
Hi, 
Thank you for the response.
So, can you help me out in explaining which file do I need to run if I want to use FMLLR features? I want to run a downstream ASR model using the pre-trained FMLLR TERA model on LibriSpeech data (I have downloaded the data with FMLLR features).

**Comment by andi611** [comment]
Hi! Sorry for the delay,

I believe you will need the legacy version of our code,
which you can download here:
https://github.com/s3prl/s3prl/releases/tag/v0.1.0
The instructions are still available in our wiki page:
https://github.com/s3prl/s3prl/wiki/ASR-with-PyTorch-Kaldi

Let me know if you have any questions!
Andy

**Comment by leo19941227** [comment]
Feel free to re-open it!
