### ISSUE TITLE
Error in mos_prediction (for finding file `system_mos_all_trackwise.csv`)

### ISSUE THREAD

**Issue by bagustris** [s3prl/s3prl#281]
Hi there, 

I got an error while trying to execute `mos_prediction` downstream. The error said, 

~~~
FileNotFoundError: [Errno 2] No such file or directory: '/groups/gac50538/VCC/VCC_2018/VCC2018_Results/system_mos_all_trackwise.csv'
~~~
After inspecting, the error is caused by the following lines in `expert` file.

https://github.com/s3prl/s3prl/blob/2bfd8485c2ba84654c993abf689621200acc6060/s3prl/downstream/mos_prediction/expert.py#L47-L51
 
That file (`system_mos_all_trackwise.csv`) is not given in the original dataset. So, I thought the authors make a script to generate that csv file from the data in the VCC 2018 dataset.

Also, the README in the mos_prediction is not complete and it differs from the current downloaded VCC databases for both 2016 and 2018 versions. The unzipped folder names are not the same per README. In the future, it will be better to provide a `py` file for preprocessing the dataset in the given path as in other downstream folders.

Any help will be highly appreciated, @RayTzeng ?

**Comment by leo19941227** [comment]
Hi,

Just to keep you updated.
@RayTzeng is now working on preparing the csv file, and will push new commits to fix this soon. Thanks for reporting!

**Comment by epriwahyu** [comment]
Thanks!

**Comment by bagustris** [comment]
Thanks @leo19941227, @RayTzeng 

Please ask him to update the README file too.  I would like to propose a data preparation section similar to this (please check).
~~~
cd /path/to/VCC

mkdir VCC_2018
cd VCC_2018
wget https://datashare.ed.ac.uk/bitstream/handle/10283/3061/vcc2018_submitted_systems_converted_speech.tar.gz
wget https://datashare.ed.ac.uk/bitstream/handle/10283/3061/vcc2018_evaluation_results.zip
tar -zxvf vcc2018_submitted_systems_converted_speech.tar.gz
mv mnt/sysope/test_files/testVCC2 .
mv testVCC2 Converted_speech_of_submitted_systems
unzip vcc2018_evaluation_results.zip
mv 'VCC2018 Results (Updated release version v3)' VCC2018_Results
cp /path/to/s3prl/sprl/downstream/mos_prediction/data/VCC2018/*.csv .
cd ..

mkdir VCC_2016
cd VCC_2016
wget https://datashare.ed.ac.uk/bitstream/handle/10283/2211/participant_submissions.zip
unzip participant_submissions.zip
cd participant_submissions
unzip '*.zip'
cd  ..
mv participant_submissions unified_speech
cp /path/to/s3prl/sprl/downstream/mos_prediction/data/VCC2016/*.csv .

~~~

What I am confusing now is for each dir. For VCC_2018, I have 20871 wav files under `mnt/sysope/test_files/testVCC2/` subdir (extracted from tar.gz file). Do I need to move all wav files to the new directory `Converted_speech_of_submitted_systems`? If yes, then the preparation section above is valid.

For `VCC_2016` subdir is similar. In the directory (as shown in the data preparation and `expert` file) there is a new directory called `unified_speech`. I assumed this directory is an extraction from `participant_submissions.zip` and renamed it from the extracted dir (`participant_submissions`) to ` unified_speech` (containing folder A, B, ... Q). Hence,  the proposed data preparation above is also valid.

**Comment by RayTzeng** [comment]
Hi @bagustris !

I really appreciate your kind assistance for informing me these issues and providing the potential solution.

Given the incomplete README file under the `mos_prediction` folder, I temporarily packed the dataset(VCC_2016 and VCC_2018) along with their .csv files into one .tar.gz file, making the preprocess step simpler as following:
```bash
# install gdown package if you don't have one
# pip install gdown

cd /path/to/data

# downloading VCC_2018 dataset
gdown "https://drive.google.com/u/0/uc?id=1C3LyUnEd4frtxr0By26_WobkpG12ajyH&export=download"
tar -zxvf VCC_2018.tar.gz

# downloading VCC_2016 dataset
gdown "https://drive.google.com/u/0/uc?id=1WUFnLZ_wkKY_WGat8cc4eNiVkAy2BvnQ&export=download"
tar -zxvf VCC_2016.tar.gz

```

I'll soon make a pull request for updating the README file.

**Comment by bagustris** [comment]
Thanks @RayTzeng for the fix!

I am confirming now `mos_prediction` downstream works without any issues after PR #287. The only specific requirement is it needs to be run on `python3.8` (or maybe higher, but not lower, due to `initial` argument in itertools's `accumulate`, the error happens in lower python version if this argument is skipped).

I will close this issue.

**Comment by leo19941227** [comment]
Thanks for reporting!

**Comment by MingjieChen** [comment]
Hello,

I am trying to download the VCC2018 and the VCC2016 datasets as instructions in  @RayTzeng 's [comment](https://github.com/s3prl/s3prl/issues/281#issuecomment-1026594290)

but got this error.

```Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	 https://drive.google.com/u/0/uc?id=1C3LyUnEd4frtxr0By26_WobkpG12ajyH&export=download
```

Then I tried @bagustris's scripts in [comment](https://github.com/s3prl/s3prl/issues/281#issuecomment-1022837177) but the `system_mos_all_trackwise.csv` file is still missing. 


Thanks for help.
