### ISSUE TITLE
Where can I find a detail introduction to these pre-training models?

### ISSUE THREAD

**Issue by finquick** [s3prl/s3prl#290]
Hi, when I  use these pre-training models, where can I find an introduction to these pre-training models?  I want to know the details of the differences between them so that I can compare them experimentally. Thank you very much!
```python
'cpc_local', 'cpc_url',

'audio_albert', 'audio_albert_960hr', 'audio_albert_gdriveid', 'audio_albert_local', 'audio_albert_logMelBase_T_share_AdamW_b32_1m_960hr_drop1', 'audio_albert_url', 

'mockingjay', 'mockingjay_100hr', 'mockingjay_960hr', 'mockingjay_gdriveid', 'mockingjay_local', 'mockingjay_logMelBase_T_AdamW_b32_1m_960hr', 'mockingjay_logMelBase_T_AdamW_b32_1m_960hr_drop1', 'mockingjay_logMelBase_T_AdamW_b32_1m_960hr_seq3k', 'mockingjay_logMelBase_T_AdamW_b32_200k_100hr', 'mockingjay_logMelLinearLarge_T_AdamW_b32_500k_360hr_drop1', 'mockingjay_origin', 'mockingjay_url', 
'modified_cpc', 

'tera', 'tera_100hr', 'tera_960hr', 'tera_fbankBase_T_F_AdamW_b32_200k_100hr', 'tera_gdriveid', 'tera_local', 'tera_logMelBase_T_F_AdamW_b32_1m_960hr', 'tera_logMelBase_T_F_AdamW_b32_1m_960hr_drop1', 'tera_logMelBase_T_F_AdamW_b32_1m_960hr_seq3k', 'tera_logMelBase_T_F_AdamW_b32_200k_100hr', 'tera_logMelBase_T_F_M_AdamW_b32_1m_960hr_drop1', 'tera_logMelBase_T_F_M_AdamW_b32_200k_100hr', 'tera_url',
```
Specifically xxx_url、xxx_local、xxx_gdriveid.
Thanks!

**Comment by leo19941227** [comment]
Hi,

Thanks for the suggestion!
Unfortunately, current we not yet have detailed documentation about this part.
We are preparing the official online documentation website which will be released in the middle of May.
Sorry for the current inconvenient.

The upstream models you list are pre-trained by @andi611 and perhaps he can give more information about the naming convention. Most of them are just different between the amount of pre-training data with LibriSpeech.

For the xxx_url, xxx_local, xxx_gdriveid, these entries need to be initialized with a `ckpt` argument which specifies the **source** of the checkpoint, like a URL, a local PATH, or a Google Drive id (gdown jargon). If you are using `run_downstream.py`, then you can specify --upstream_ckpt to pass this `ckpt` argument.

E.g.
```
python3 run_downstream.py -u tera_local -k your_own_tera_path
```

**Comment by finquick** [comment]
OK, thanks!
```python
In comparison with the training data number, right is longer than left, right? 
'audio_albert'< 'audio_albert_960hr',
'mockingjay'< 'mockingjay_100hr', 'mockingjay_960hr',
'tera'< 'tera_100hr'< 'tera_960hr'
```
I will find further information in andi611's GitHub and his other papers!
