### ISSUE TITLE
AttributeError: module 's3prl.downstream' has no attribute 'experts'

### ISSUE THREAD

**Issue by TCL606** [s3prl/s3prl#292]
When I tried to run run_downstream.py to start a downstream task, it reported that "module 's3prl.downstream' has no attribute 'experts'" at line 48. 
![1645862793(1)](https://user-images.githubusercontent.com/84725343/155835523-c6278a55-cc8c-42d8-9410-f6016d078395.png)
![1645862879(1)](https://user-images.githubusercontent.com/84725343/155835564-d8f4679c-dfa2-4d4f-9a0c-a55cb87f5c97.png)

I installed s3prl by pip, but it seems something missed in the s3prl. 

What might be the problem?

**Comment by leo19941227** [comment]
Hi, did you install by `pip install -e ./` for `pip install s3prl`?
The later won't work since our PyPi package is out-of-date.

**Comment by TCL606** [comment]
OK，thanks a lot
