### ISSUE TITLE
'initial' is an invalid keyword argument for accumulate()

### ISSUE THREAD

**Issue by speakstone** [s3prl/s3prl#295]
import torch
  from s3prl.hub import mos_wav2vec2

  mos_predictor = mos_wav2vec2().cuda()
  wavs = [torch.zeros(160000, dtype=torch.float).to(device) for _ in
          range(16)]  # list of unpadded wavs `[wav1, wav2, ...]`, each wav is in `torch.FloatTensor`

  with torch.no_grad():
      print(mos_predictor(wavs))

Traceback (most recent call last):
  File "/home/lee/s3prl/eval.py", line 44, in <module>
    print(mos_predictor(wavs))
  File "/home/lee/s3prl/s3prl-master/s3prl/upstream/interfaces.py", line 103, in __call__
    result = super().__call__(wavs, *args, **kwargs) or {}
  File "/opt/conda/envs/python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lee/s3prl/s3prl-master/s3prl/upstream/mos_prediction/expert.py", line 59, in forward
    prefix_sums = list(accumulate(wav_segments_lengths, initial=0))
TypeError: 'initial' is an invalid keyword argument for accumulate()

**Comment by speakstone** [comment]
s3prl-master\s3prl\upstream\mos_prediction\expert.py
第59
  prefix_sums = list(accumulate(wav_segments_lengths))
  # prefix_sums =list(accumulate(wav_segments_lengths, initial=0))

**Comment by leo19941227** [comment]
Hey @RayTzeng!

I believe someone is trying to use your MOS model, are you available to help?

**Comment by RayTzeng** [comment]
Hi,

Thanks for reporting this issue.
The "accumulate" function we used here requires **Python>=3.8**.
I'll modify the README file to include the description of this requirement ASAP.
