### ISSUE TITLE
mos_tera 默认模型存在参数不匹配问题

### ISSUE THREAD

**Issue by speakstone** [s3prl/s3prl#296]
size mismatch for transformer.extracter._melscale.fb: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([201, 80]).

**Comment by RayTzeng** [comment]
Hi,

It seems that this issue is duplicate with #197 .
Hope this information can help!

**Comment by leo19941227** [comment]
I am closing this. Feel free to reopen if you still encounter problems
