### ISSUE TITLE
Why is such a large memory cost on gpu

### ISSUE THREAD

**Issue by TCL606** [s3prl/s3prl#297]
Hello! I was tring to run an experiment of "Hubert + PR" using single gpu. I have noticed it that the task cost nearly 40+G memory on gpu when I start training. After training for some time, it has reported "cuda out of memory" and I have to stop the task. I encountered similar situation when I run the experiment of "Wavlm + ASR", which cost about 30G memory. Such a large memory cost didn't appear in other downstream tasks such as KS, IC. I ran all the experiments with a default config.yaml. So why does the task  use so much memory? Is it normal?

**Comment by leo19941227** [comment]
Hi!

Thanks for reporting. This is not normal. In our typically use case we always train with a single V100 GPU in 16GB. So it is weird you get 40+G mem with Hubert + PR. Let me verify this a get back to you.

**Comment by TCL606** [comment]
Thanks a lot. And I have done some test on this problem. I used the default config, with a batch size 16. The test is on "hubert_base + pr". 
I have found that no matter what the length of utterances in a batch are, they will be all put into one batch, and this leads to a large memory cost. In other words, the total sample number is determined by batchsize, but not batchsize * nsample which is used in wav2vec. You can see the picture below. In this case, batch size=16, and total sample is 16*231000=3.7M. There might be some problems here.

![image](https://user-images.githubusercontent.com/84725343/158067091-9af60b53-96ea-478b-a735-14a5baf014a0.png)

**Comment by leo19941227** [comment]
Hey!

This is my GPU utility:

![image](https://user-images.githubusercontent.com/33196053/158162879-abc2dabd-0758-4654-bab3-70636c353c62.png)

when running the command with the `master`'s `downstream/ctc/libriphone.yaml` :

```
python3 run_downstream.py -m train -u hubert -d ctc --config downstream/ctc/libriphone.yaml -n test
```

So I am still curious about your environment. Do you finetune the hubert base by `--upstream_trainable`?

**Comment by leo19941227** [comment]
That is, our configs are guaranteed to run smoothly when freezing the hubert, but must be adjusted to finetune the hubert.
Since we do not adopt dynamic timestamp batching like in fairseq, so the batch_size in our config is not generally applicable to all training settings.
About why we don't adopt dynamic batching, this is because pretrained models have different stride in 10ms and 20ms or 40ms, if we do not regularize the batch size with the number of utterance (transcriptions), and instead optimize the training pipeline by regularizing the maximum timestamps, then 20ms representations get 2x batch size (in utterance) compared to 10ms, and 40ms get even more utterances for a single training step. It is hard to determine which way is more fair, but we try to eliminate the effects from different training pipeline and fairly compare all representations as the frozen numerical tensors, so we do not use the batching mechanism as done in fairseq.

**Comment by TCL606** [comment]
Yes, I finetuned the hubert by "--upstream_trainable". My original command is " python3 run_downstream.py -n PRhubert_base -m train -u hubert_base -d ctc -c downstream/ctc/libriphone_hubert.yaml -f -s last_hidden_state". I had tried to run command without "-f" yesterday, which is your command, and I got into an error.
![1647258349(1)](https://user-images.githubusercontent.com/84725343/158165575-74903327-b3dc-47d2-b1eb-5b05fad04639.png)
The error leads me to upstream/interfaces.py, line 233:
![1647258431(1)](https://user-images.githubusercontent.com/84725343/158165774-73a0ccd6-362e-45fe-8a71-e7327fb8edcd.png)
The annotation suggests me to run with "-f -s last_hidden_state"

**Comment by leo19941227** [comment]
Cool,

Could you provide the detailed command *without* `--upstream_trainable` and the config file (with Github gist) you used which led to this interface error? I can check them now.

**Comment by TCL606** [comment]
The config file is the default one in the master branch. Only librispeech path changed

**Comment by leo19941227** [comment]
How about the original command?
It is the same as the following?
```
python3 run_downstream.py -m train -u hubert -d ctc --config downstream/ctc/libriphone.yaml -n test
```

**Comment by TCL606** [comment]
I use the command
```python3 run_downstream.py -n PRhubert_base -m train -u hubert_base -d ctc -c downstream/ctc/libriphone.yaml```

**Comment by TCL606** [comment]
yes

**Comment by leo19941227** [comment]
This is weird... I am now using this command but does not run into the interface error.
Can you please try again? If you still run into the same interface error, please provide your `pip list`

**Comment by TCL606** [comment]
![1647259401(1)](https://user-images.githubusercontent.com/84725343/158168290-8502da08-5bc3-4de8-b031-d420faf4f296.png)
![1647259426(1)](https://user-images.githubusercontent.com/84725343/158168360-dadb2e9b-f78b-4bae-a6bf-701fb82011ec.png)
![1647259462(1)](https://user-images.githubusercontent.com/84725343/158168437-e91a68d1-bb93-4e9d-af7f-8d0745257db8.png)
![1647259483(1)](https://user-images.githubusercontent.com/84725343/158168480-36327a58-7f26-4b4b-860f-d5b3773aa041.png)

**Comment by leo19941227** [comment]
Hey,

I can locate the problem. You are using the latest fairseq, but fairseq API is very unstable and this is why we fix to a specific commit hash for installing fairseq in the main README as you can see there:

```
pip install fairseq@git+https://github.com//pytorch/fairseq.git@f2146bdc7abf293186de9449bfa2272775e39e1d#egg=fairseq
```

Installing by other commits are not guaranteed to work with the current S3PRL codebase, if you install with this command I believe you are good to go.

**Comment by leo19941227** [comment]
I believe this will fix the issue so I am closing the issue. Please feel free to re-open it if you still encounter problems.
