### ISSUE TITLE
Unable to reach the results on the leaderboard

### ISSUE THREAD

**Issue by YangHao97** [s3prl/s3prl#299]
Hi, I am trying to use wav2vec 2.0 Large to replicate the results on the leaderboard. I completely followed your instructions and training parameters, but the results are not good enough.
![image](https://user-images.githubusercontent.com/71253402/158528680-6c0de922-fcbb-4708-980c-05b37ec80c4f.png)
I can't find what is causing this result

**Comment by andi611** [comment]
Hi,

I think the gap is caused by different learning rates used.
In the SUPERB paper, we tune the learning rate for each "upstream-downstream" pair and report the optimal result.
@leo19941227 can we share the learning rates that we used for wav2vec 2.0 Large?

**Comment by leo19941227** [comment]
Did you use the training learning rate as released in the SUPERB artifacts page?

**Comment by YangHao97** [comment]
> Did you use the training learning rate as released in the SUPERB artifacts page?

![image](https://user-images.githubusercontent.com/71253402/158756896-cb77bc6b-03d5-4f08-b869-a3614db1ec90.png)
So I should apply lr=1.0e-5 for all the downstream tasks? I am not sure where is SUPERB artifacts page.

**Comment by leo19941227** [comment]
Oh I believe this is the problem. You can know the best learning rate here:

https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/docs/superb_artifacts.md

In our artifact server, each checkpoint folder name indicates the best learning rate we found for reporting the final number.

**Comment by YangHao97** [comment]
Thank you so much! But take IC as an example, the learning rate is the same as the default learning rate. And the result still does not achieve the goal. Am I missing something else?
![image](https://user-images.githubusercontent.com/71253402/158759065-9e02dea8-356b-4fd5-9872-3ed8d68900cf.png)
![image](https://user-images.githubusercontent.com/71253402/158759101-30a5915b-048a-471d-a70b-81a4a6bf63bd.png)

**Comment by leo19941227** [comment]
Oh! Really sorry about this. I find that the actual best lr for wav2vec2_large_ll60k is lr 1e-3, and the 1e-4 result aligns well with your. The reason I did not release the 1e-3 one is because it was trained by Meta Inc. during our cooperation, however there is some difficulty to release it publicly.

![image](https://user-images.githubusercontent.com/33196053/158924795-ed8f735b-bb68-48f6-83c5-535118b5f640.png)

However, for wav2vec2_large_ll60k on the other tasks, this is not the case and I believe you can get the same results after following the reported lr.

Please let me know if you still can't reproduce the results. Thanks!

**Comment by YangHao97** [comment]
> Oh! Really sorry about this. I find that the actual best lr for wav2vec2_large_ll60k is lr 1e-3, and the 1e-4 result aligns well with your. The reason I did not release the 1e-3 one is because it was trained by Meta Inc. during our cooperation, however there is some difficulty to release it publicly.
> 
> LR	IC acc
> 1e-3	0.9528077841
> 1e-4	0.9322435
> 1e-5	0.9116793871
> However, for wav2vec2_large_ll60k on the other tasks, this is not the case and I believe you can get the same results after following the reported lr.
> 
> Please let me know if you still can't reproduce the results. Thanks!

**Comment by YangHao97** [comment]
> > Oh! Really sorry about this. I find that the actual best lr for wav2vec2_large_ll60k is lr 1e-3, and the 1e-4 result aligns well with your. The reason I did not release the 1e-3 one is because it was trained by Meta Inc. during our cooperation, however there is some difficulty to release it publicly.
> > LR	IC acc
> > 1e-3	0.9528077841
> > 1e-4	0.9322435
> > 1e-5	0.9116793871
> > However, for wav2vec2_large_ll60k on the other tasks, this is not the case and I believe you can get the same results after following the reported lr.
> > Please let me know if you still can't reproduce the results. Thanks!

Thank you very much! I'll try this.
