### ISSUE TITLE
confusing upstream names 

### ISSUE THREAD

**Issue by B06901052** [s3prl/s3prl#300]
Hello, the model names of cpc and modified_cpc in [upstream README.md](https://github.com/s3prl/s3prl/blob/master/s3prl/upstream/README.md) seem to be reverse, or are there some reasons behind them? 
![image](https://user-images.githubusercontent.com/31962865/158812521-5fc301f3-d41e-4288-8f65-439e49a5d57d.png)

**Comment by leo19941227** [comment]
You are right, I will fix this
