### ISSUE TITLE
Query on pretraining with librispeech and other custom datasets

### ISSUE THREAD

**Issue by rimitalahiri92** [s3prl/s3prl#306]
Hi,

Is it possible to pretrain already existing pretrained models on custom datasets? If so, some help is appreciated.
Are there pretraining options for wave2vec2, hubert and so on on custom datasets? Any help is highly appreciated.

**Comment by andi611** [comment]
> Is it possible to pretrain already existing pretrained models on custom datasets? If so, some help is appreciated. 

Yes its totally possible, follow the instructions [here](https://github.com/s3prl/s3prl/tree/master/s3prl/pretrain#readme) and slightly modify the code in `generate_len_for_bucket.py` to fit your custom dataset. You only need to take care of these [lines](https://github.com/s3prl/s3prl/blob/841416d9b92170ea28a983ec2154cc2026947fa3/s3prl/preprocess/generate_len_for_bucket.py#L89-L100) of code, then everything else follows.

> Are there pretraining options for wave2vec2, hubert and so on on custom datasets? Any help is highly appreciated.

For now, we do not support this. Pre-training these models will take a lot of computational resources thus we are not able to verify the correctness even if we implement them. You will have to use their official implementation.

**Comment by rimitalahiri92** [comment]
Thanks a lot for the help....appreciate this...:)
