### ISSUE TITLE
Using pytorch lightning for training

### ISSUE THREAD

**Issue by xixihahaggg** [s3prl/s3prl#310]
Hi, there.
Have you considered adapting the training process to pytorch lightning instead of a custom-built runner? Because pytorch lightning provides a more friendly way to use multi-GPU. 
I've adapted an example: pretraning step using APC based pytorch lightning as it supports DDP.

**Comment by leo19941227** [comment]
Hi,

This is what we are doing internally now, and we do not aim to adapt it only for lightning (as it has frequent API changes and not suitable to directly depend on) but for many general training packages including SpeechBrain and Huggingface Trainer.
Please stay tune, and thanks for the suggestion!
