### ISSUE TITLE
運行下游任務時候發生錯誤

### ISSUE THREAD

**Issue by rainssun** [s3prl/s3prl#311]
你好：
我在執行下游任務時，出現錯誤但是不知道怎麽解決。我的pytorch版本為1.8.0，我下的指令為
`python3 run_downstream.py -m evaluate  -t "test" -e /home/user/s3prl/s3prl/fmllrBase960-T-libri/states-1000000.ckpt`
error message：
`[Runner] - Resume from /home/user/s3prl/s3prl/fmllrBase960-T-libri/states-1000000.ckpt`
`Traceback (most recent call last):`
  `File "run_downstream.py", line 220, in <module>`
   ` main()`
  `File "run_downstream.py", line 162, in main`
    `args, config, backup_files = get_downstream_args()`
  `File "run_downstream.py", line 116, in get_downstream_args`
    `ckpt = torch.load(ckpt_pth, map_location='cpu')`
  `File "/home/user/anaconda3/envs/pyka/lib/python3.8/site-packages/torch/serialization.py", line 593, in load`
    `return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)`
  `File "/home/user/anaconda3/envs/pyka/lib/python3.8/site-packages/torch/serialization.py", line 772, in _legacy_load
    result = unpickler.load()`
`ModuleNotFoundError: No module named 'transformer'`

**Comment by andi611** [comment]
You are using the wrong command (使用指令的方式錯誤).
`/home/user/s3prl/s3prl/fmllrBase960-T-libri/states-1000000.ckpt` ---> This is a pre-trained **upstream** model.
It should **NOT** be used with `run_downstream.py -m evaluate -t "test"` alone.

Rather, `-m evaluate -t "test"` are used to evaluate trained **upstream+downstream** ckpts.

**Comment by rainssun** [comment]
謝謝你的回復，我還有另一個問題想請教。特定的下游任務能夠生成類似的kaldi lattice嗎？

**Comment by andi611** [comment]
我們目前的下游任務均不支援生成kaldi lattice唷

**Comment by andi611** [comment]
> 

抱歉晚回覆了，是的，是把768 dim的hidden states作爲features進行kaldi的訓練的意思。目前只有舊版的code有cover，這邊可以下載: https://github.com/s3prl/s3prl/releases/tag/v0.1.0
說明請見這邊: https://github.com/s3prl/s3prl/wiki/ASR-with-PyTorch-Kaldi
