### ISSUE TITLE
is there a wavlm config?

### ISSUE THREAD

**Issue by Cescfangs** [s3prl/s3prl#312]
Hi
I'm new to s3prl, I wanna use wavlm as upstream task but there's no such config dir under `s3prl/pretrain`, is there any example I can follow to train a wavlm upstream? 
thanks

**Comment by leo19941227** [comment]
Hi,

To pretrain a wavlm model you would need to use their repo: https://github.com/microsoft/UniSpeech/tree/main/WavLM

**Comment by Cescfangs** [comment]
thx
