### ISSUE TITLE
How to run emotion classification on other dataset ?

### ISSUE THREAD

**Issue by TinaChen95** [s3prl/s3prl#317]

**Comment by leo19941227** [comment]
Hi,

We only support IEMOCAP for now.

**Comment by TinaChen95** [comment]
Then maybe we can develop data preprocess scripts by our own. 
Could you kindly give us some information on data structure?
Thanks!

**Comment by leo19941227** [comment]
Hi,

Here are some preprocessed metadata file in the JSON format for the emotion downstream task.
Please have a look. If you preprocess your dataset into this format I think it can be used for the emotion downstream.
https://drive.google.com/drive/folders/1Sud-7BpjtD6qcGLpEb0oJ9jWLOTG1b2l?usp=sharing

**Comment by TinaChen95** [comment]
Thanks a lot! This is very helpful.
