### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [1, 50, 768] at entry 0 and [1, 49, 768] at entry 12

### ISSUE THREAD

**Issue by zds-potato** [s3prl/s3prl#318]
when use hubert or wav2vec on downstream tasks,like this:
`python3 run_downstream.py -m train -n ExpName -u hubert -d example`

then,there a error:
`RuntimeError: stack expects each tensor to be equal size, but got [1, 50, 768] at entry 0 and [1, 49, 768] at entry 12`

**Comment by leo19941227** [comment]
I remember someone report this issue before, and it seems to turn out to be a fairseq version problem.
Could you confirm if your fairesq version aligns with our main README?

**Comment by PeterGuoRuc** [comment]
@leo19941227  Hi, I have the same problem `RuntimeError: stack expects each tensor to be equal size, but got [1, 50, 768] at entry 0 and [1, 49, 768] at entry 12`, when using hubert model.  Do you mean reinstall the fairseq like this?  `pip install fairseq@git+https://github.com//pytorch/fairseq.git@f2146bdc7abf293186de9449bfa2272775e39e1d#egg=fairseq`

**Comment by leo19941227** [comment]
Yes, I think so.
Do you still encounter the same problem with this specific fairseq version?

**Comment by PeterGuoRuc** [comment]
Thanks, Problem solved !
