### ISSUE TITLE
Arabic Emotion Recognition

### ISSUE THREAD

**Issue by ihaya94** [s3prl/s3prl#320]
Thank you for the great effort in making this amazing open-source tool.

I want to ask what model you advise me to use for Arabic emotion recognition?

**Comment by bagustris** [comment]
Go for the default model in `emotion` downstream (`Deepmodel`). Then try some model available in `model.py` inside `emotion` downstream. If you wan to try Transformer, take a look at `mosei` downstream README. All of these models resulted in competitive result compared to current SOTA.

**Comment by ihaya94** [comment]
Thanks a lot!
