### ISSUE TITLE
Bug in MOSEI 3-class sentiment

### ISSUE THREAD

**Issue by bagustris** [s3prl/s3prl#321]
I think there is a bug in `mosei` downstream with three classes as shown below.
https://github.com/s3prl/s3prl/blob/bdc835b848066745b0e97cf14564875730af0e4f/s3prl/downstream/mosei/utility/convert_label.py#L32-L38

It should be:
```python
def label2b(a):	# negative / positive: <0 or >0 (used in some papers) 
 	if a < 0: 
 		return -1 
 	if a > 0: 
 		return 1 
 	return 0
```

Found this when inspecting a strange number of samples between two-class and three-class.
Will work on this and make a PR soon.

**Comment by leo19941227** [comment]
Cool, thanks @bagustris for finding this.
