### ISSUE TITLE
ER training on a new dataset

### ISSUE THREAD

**Issue by sciai-ai** [s3prl/s3prl#325]
Hi, I am training wavlm upstream for ER on a custom dataset. I am getting the following error while training 

`python3 run_downstream.py -n ExpName -m train -u wavlm -d emotion -c downstream/emotion/config.yaml -o "config.downstream_expert.datarc.test_fold='fold1'"`

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/52277510/165700117-69214eed-d47e-4325-876f-ef18cdee732f.png">

I am not sure about the wav files lengths in IEMPCAP as I don't have access to it. Here is the distribution of the wav file length in seconds for my dataset

![image](https://user-images.githubusercontent.com/52277510/165700369-496692d4-73cb-4713-96d6-cbe9535335c2.png)

**Comment by shahadbakhsh** [comment]
Hello 
Can you please explain how the data_root is supposed to insert?
I tried this format, but it does not work.
![image](https://user-images.githubusercontent.com/104463603/165861424-78f47784-926d-454d-833f-36c2495fec8e.png)
here is the code:
![image](https://user-images.githubusercontent.com/104463603/165861537-01f45a94-3ff1-48b8-a1e6-860f48a43c7e.png)
