### ISSUE TITLE
How to do inference in downstream task ER

### ISSUE THREAD

**Issue by sciai-ai** [s3prl/s3prl#326]
I have trained a downstream ER task where a checkpoint has been saved. Can you please share the inference code that can be used to check the emotion for a given wav file.

1. I know there is this code to test but this assumes the data to be in the format for IEMOCAP rather than simply a wav file

`data="your IEMOCAP root"

python3 run_downstream.py -m evaluate -t test \
    -e checkpoint_fold1.ckpt \
    -o args.expdir=tgt_dir/er/fold1,,config.downstream_expert.datarc.root=$data`

2. What is the difference between `-m evaluate` vs `-m infer`.

3. Can we use the saved checkpoint to something along the lines of the code below from HF

<img width="625" alt="image" src="https://user-images.githubusercontent.com/52277510/165874011-3f9e9184-e926-4c5c-a9ff-c24af333b9eb.png">

**Comment by leo19941227** [comment]
You are correct... This is the limitation of the current codebase. Yes it is not naturally supported for new data and will need to modify the existing code to enable this.

**Comment by sciai-ai** [comment]
Can you please point me to the code that needs to be changed?
