### ISSUE TITLE
specaugment ER 

### ISSUE THREAD

**Issue by sciai-ai** [s3prl/s3prl#327]
Is there any option to use specaugment when running the downstream ER task using wavlm/wav2vec2?

**Comment by leo19941227** [comment]
Yes this is possible, you can add the specaug-related block to the config file you use for emotion recognition. See ASR config for an example.

https://github.com/s3prl/s3prl/blob/2ceead07d9f4f5c149e88663680b1e32c5f1a4b9/s3prl/downstream/asr/config.yaml#L25-L37

**Comment by leo19941227** [comment]
Currently no.

**Comment by sciai-ai** [comment]
@leo19941227 I am just wondering at what stage specaugment takes places in the downstream task? My understanding is that we are directly extracting features from the wavform using the upstream model, then tuning the downstream for ER using the weighted sum. Specaugment is applied in the spectogram so by copying the code in the yaml aapp  what stage  does specaugment gets applied?
