### ISSUE TITLE
-f / --upstream_trainable not working in ER run_downstram

### ISSUE THREAD

**Issue by sciai-ai** [s3prl/s3prl#328]
I tried using the `-f`/ `--upstream_trainable`  option during the downstream training ER task, however i get the error below

<img width="891" alt="image" src="https://user-images.githubusercontent.com/52277510/166097223-c8334b98-e9eb-49fc-a47f-5d2f9aaa292c.png">

I would like to use this finetuned upstream to do inference

**Comment by penisola** [comment]
I got the same error, sir. How did you solve this problem?
