### ISSUE TITLE
about distilhubert

### ISSUE THREAD

**Issue by c976237222** [s3prl/s3prl#331]
when I run "python run_pretrain.py -u distiller -g pretrain/distiller/config_model.yaml -n distilhubert";

I got error _" File "/home/wangsiyuan/kaldi-wavlm/s3prl-test/s3prl/pretrain/distiller/pretrain_expert.py", line 278, in forward
    teacher_hiddens = torch.stack(teacher_hiddens, dim=1)  # B x N x T x D
RuntimeError: stack expects each tensor to be equal size, but got [18, 302, 768] at entry 0 and [18, 301, 768] at entry 1"_

**Tests have shown that,The teacher model has 12 blocks, the 12th block is one frame away from the other blocks；**

After Padding，another error occur , the compute loss denote that student model output  is one frame away from the output of teacher model........

Other error: when I use multi GPU ,I got "IndexError: Caught IndexError in replica 0 on device 0." I use torch 1.9.0 or 1.10.1 +cu111,can not fix it

**Comment by c976237222** [comment]
maybe version of fairseq cause the first error

**Comment by leo19941227** [comment]
Hi,

This is an fairseq version problem. Please switch to the fairseq commit described in our setup.py

**Comment by leo19941227** [comment]
Yes cool

**Comment by c976237222** [comment]
ok nice! thank you ,and What should I do about the second error

**Comment by leo19941227** [comment]
I think the second error is related to the first error. Do you still encounter the second error after installing the correct fairseq version?

**Comment by c976237222** [comment]
Wait for me to try, I will timely feedback here

**Comment by c976237222** [comment]
i cant install fairseq follow the setup.py.....
my service is offline，it can not pip install 
"fairseq @ git+https://github.com//pytorch/fairseq.git@f2146bdc7abf293186de9449bfa2272775e39e1d#egg=fairseq"

i git clone https://github.com/pytorch/fairseq.git and the vision of fairseq is 
"fairseq                   1.0.0a0+0835da9           dev_0    <develop>"
but not work .....(｡•́︿•̀｡) error“AssertionError: Please install the fairseq master branch.”

**Comment by c976237222** [comment]
按照fairseq版本安装以后  还是会在多gpu处出现问题 error"IndexError: Caught IndexError in replica 0 on device 0."

**Comment by leo19941227** [comment]
@vectominist is the expert of this. Maybe he can provide some help if convenient, or I can also dive into this later.

**Comment by vectominist** [comment]
I haven't seen this error before, but I guess this might be caused by using multiple GPUs.

**Comment by c976237222** [comment]
yes，this error occur when i use --multi_gpu ,does distilhubert supports multiple GPUs

**Comment by leo19941227** [comment]
I think the --multi-gpu is for DataParallel, which is our old distributed method. However, nowadays it is always more recommended to use Distributed DataParallel, which is launched by python3 -m torch.distributed.launch --nproc_per_node gpu_num run_pretrain.py ...

**Comment by leo19941227** [comment]
Also, I remember DataParallel (DP) requires the data input to fulfill some constraints since it split a batch into several parts (num of gpu), forward with different gpu in different thread, and then combine the output of each part together. This constraint can break of the code is not specifically designed to compatible with DP. Distilhubrrt is only ran with DDP, so I guess it does not support DP and the --multi_gpu flag, but it can use multiple gpus with DDP. You can refer to our downstream/README to see how to use DDP for any python script
