### ISSUE TITLE
resume pretrain

### ISSUE THREAD

**Issue by rainssun** [s3prl/s3prl#332]
hello，excuse me
I want to run the pre-trained model but it is interrupted in the middle, I want to continue running but the following error occurs
`[Runner] - Resume from /usr/pretrain/tera/states-1000.ckpt
Traceback (most recent call last):
  File "run_pretrain.py", line 156, in <module>
    main()
  File "run_pretrain.py", line 150, in main
    runner = Runner(args, config)
  File "/usr/s3prl/s3prl/pretrain/runner.py", line 44, in __init__
    self.upstream = self._get_upstream()
  File "/usr/s3prl/s3prl/pretrain/runner.py", line 53, in _get_upstream
    upstream = Upstream(self.config['pretrain_expert']['datarc'], 
KeyError: 'pretrain_expert'`
my command is
`python run_pretrain.py -u tera -c /usr/pretrain/tera/config_runner.yaml -g /usr/pretrain/terat/config_model.yaml  -p /usr/pretrain -n tera -e /usr/pretrain/tera/`
can you help me ? sincere gratitude

**Comment by andi611** [comment]
Hi @rainssun,

I tried to reproduce it but I did not get any errors.

Can you print out your `self.config` right before this line:
https://github.com/s3prl/s3prl/blob/e52439edaeb1a443e82960e6401ae6ab4241def6/s3prl/pretrain/runner.py#L53

This is what I get when I print my `self.config`, you should get something similar to this:
![image](https://user-images.githubusercontent.com/25531495/167647895-d95d589e-8b5a-48b1-b13b-c63b2866c26a.png)

As you can see, `'pretrain_expert'` is in `self.config` so you shouldn't be getting the `KeyError: 'pretrain_expert'`

**Comment by duj12** [comment]
@rainssun I meet the same issue when i resume Distiller training, can you please tell me how to sovle this problem?

**Comment by duj12** [comment]
I finally refine the run_pretrain.py, add the following code:
```
        with open(args.config, 'r') as file:
            ori_config = yaml.load(file, Loader=yaml.FullLoader)
            if 'pretrain_expert' not in config:
                config['pretrain_expert'] = ori_config['pretrain_expert']
            if 'runner' not in config:
                config['runner'] = ori_config['runner']
            if 'optimizer' not in config:
                config['optimizer'] = ori_config['optimizer']

```
which use the yaml file to fill the missing config keys.
