### ISSUE TITLE
what mean of the pretrain model outputs?

### ISSUE THREAD

**Issue by myhrbeu** [s3prl/s3prl#333]
Hi, thanks for your great work!
Even though I got a perfect result in the pre-train model of AALBERT, I have no idea of the meaning of the results.
Just like，['hidden_states'] and ['last_hidden_state'], what the relations of them?
There are three transformer layers of the pre-train model, but the length of ['hidden_states'] is 4, which is the output of the first transformer layer?

**Comment by leo19941227** [comment]
Hi,

hidden_states[-1] == last_hidden_state
hidden_states[0] == FBANK adding positional encoding + some affine transform
hidden_states[1] == first iteration output
hidden_states[2] == second iteration output
hidden_states[3] == third iteration output

Note that AALBERT shares a single transformer block so every iteration gets the output from the same nn.Module.

**Comment by myhrbeu** [comment]
I have another question, AALBERT just has 3 self_attntion layers, and I want to extend it to 7 or more layers in my experiment.
In VGG and other CNN models it is easy, but in AALBERT I found it's hard. I tried several methods by debugging codes to extend layers, but all failed！ 
It's because I can't get every layer out in the first several layers, and the self_attention layers need pos_enc and attn_mask.
Do you have an easy way or suggest  to solve this problem？Thanks a lot!
