### ISSUE TITLE
Downstream ASR Custom dataset

### ISSUE THREAD

**Issue by ana-kuznetsova** [s3prl/s3prl#340]
Hi all,

I would like to adapt SUPERB downstream ASR for Common Voice dataset. 
Are there any guidelines to follow in order to convert the dataset into expected format?

Thanks!

**Comment by andi611** [comment]
Hello,

I believe you can fit Common Voice to our downstream ASR dataset by satisfying this requirement:
https://github.com/s3prl/s3prl/blob/540a4f86e9f099b240c314a56ff80b069e91d4cd/s3prl/downstream/asr/dataset.py#L46-L47

The usage is pretty straightforward, you just have to define the sub-directory names (`SETS`) under your dataset folder, for example:
https://github.com/s3prl/s3prl/blob/540a4f86e9f099b240c314a56ff80b069e91d4cd/s3prl/preprocess/generate_len_for_bucket.py#L89-L100

And finally, you need to modify this part for reading the ASR transcripts to fit the Common Voice dataset path/naming structure:
https://github.com/s3prl/s3prl/blob/540a4f86e9f099b240c314a56ff80b069e91d4cd/s3prl/downstream/asr/dataset.py#L116-L117

**Comment by leo19941227** [comment]
Hi,

This is now possible with the new versions of S3PRL, see:

1. https://s3prl.github.io/s3prl/tutorial/problem.html
2. https://s3prl.github.io/s3prl/_autosummary/s3prl.problem.asr.html#s3prl.problem.asr.SuperbASR.prepare_data
