### ISSUE TITLE
Problems from "mask_label.sum()>0" in mockingjay/pretrain_expert.py

### ISSUE THREAD

**Issue by kaen2891** [s3prl/s3prl#342]
Hello,

I got some errors from ```s3prl/pretrain/mockingjay/pretrain_expert.py``` (I tried to pre-train tera)

![image](https://user-images.githubusercontent.com/46586785/169945839-0d496460-7e3c-4800-af49-0f62443cdef4.png)

I tried to find the utility/mam.py, but I couldn't find that code in this project.

The dataset I am using is not LibriSpeech, but a speech dataset published in Korean. Occasionally, there are short utterances, but they consist of the speech data which are longer than 3 seconds. Further, I set the max length to 2000. How can I solve this problem?

**Comment by kaen2891** [comment]
Also, the following problem occurred. I will be very thankful if you tell me how to fix it.

![image](https://user-images.githubusercontent.com/46586785/169955035-aacecbb4-e306-453f-b3d3-2e446ee5968f.png)

**Comment by kaen2891** [comment]
Dear @andi611,

Deeply thank you for your kind answers. I will deeply check your suggestions and will provide the information ASAP. 

Thanks!

**Comment by andi611** [comment]
From issue https://github.com/s3prl/s3prl/issues/346, it looks like this issue has been resolved.
Feel free to reopen it if not.

**Comment by kaen2891** [comment]
Dear @andi611,

To solve issue #346 and this, I re-installed the s3prl framework yesterday in the three servers.

The respective three servers are a little different; 
1) `Server1` has A100 GPUs, Cuda 11.3, Nvidia driver version 470.103,
2) `Server2` has A6000 GPUs, Cuda 11.3, Nvidia driver version 510, 
3) `Server3` has NVIDIA TITAN RTX, Cuda 11.3, Nvidia driver version 470.103.

The s3prl framework that I installed is all the same setting (changed Pytorch 1.10 --> PyTorch 1.9.1+cu111, protobuf 3.19.0). 

Here is the procedure that I did:
Firstly, I have installed the s3prl framework (2 days ago version).

Secondly, I have run the `preprocess/generate_len_for_bucket.py` with my dataset (same dataset in all servers). 

Finally, I have run `python3 run_pretrain.py -u tera -c pretrain/tera/config_runner_mine.yaml -g pretrain/tera_config_model.yaml -n tera_mine --multigpu` with the bucketting files.
 
I have run this code (`run_pretrain.py`) which is not modified any part on the respective three servers. Also, the datasets are in the same setting.

Only `Server1` has occurred an error as following figures: (Server2 and Server3 are still working.)

![image](https://user-images.githubusercontent.com/46586785/170975538-8299d28e-8d66-4ca8-acf8-82dd313eeb6c.png)

In this regard, this error seems to be related to the environment? Did you ever run this framework in the A100 setting? If yes, could you let me know more details about the server setting?

**Comment by kaen2891** [comment]
To add,

The reason why I didn't analyze the `mask_label.sum() > 0` is because I set all the code and the datasets as the same. The s3prl framework I set up is also only a 2 day ago version.

If you request this part, I will do it ASAP.

**Comment by andi611** [comment]
> The reason why I didn't analyze the `mask_label.sum() > 0` 
> If you request this part, I will do it ASAP.

Sorry, what do you mean by "didn't analyze"?

Sometimes cuda might cause python to throw an error that is not actually the real error.
For Server1, some good ways to debug:
1) Disable GPU, use: 
`CUDA_VISIBLE_DEVICES="" python3 run_pretrain.py -u tera -c pretrain/tera/config_runner_mine.yaml -g pretrain/tera_config_model.yaml -n tera_mine`
2) try not to use `--multigpu` and see if the error still occurs:
`python3 run_pretrain.py -u tera -c pretrain/tera/config_runner_mine.yaml -g pretrain/tera_config_model.yaml -n tera_mine`
3) In your screen shot, the last line suggests:
"for debugging consider passing cuda_launch_blocking=1"

For debug purposes, you can set small batch size to avoid OOM but allow the process to run till the "errored" sample.

**Comment by andi611** [comment]
By searching "CUDA error: uncorrectable ECC error encountered",
this error looks like a "Cuda / hardware / environment" related issue on your server: https://stackoverflow.com/questions/11839555/cuda-uncorrectable-ecc-error-encountered
Should have nothing to do with the code, that's why the other two servers can run the training without any issue.

**Comment by kaen2891** [comment]
Dear @andi611,

I tried to debug with your suggestions and here are the results:

1. Disable GPU,
I couldn't check the aforementioned errors with this way.
2. try not to use --multi_gpu
When I tried not to use `--multi_gpu`, it works! No errors have occurred!
3. cuda_launch_blocking=1
When I typed ``import``
```
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
```
in the `run_pretrain.py` and `mockingjay/task.py` files, respectively, data is loaded on the GPU in parallel (DataParallel), but it did not run. Just stopped without any errors.
4.  [https://stackoverflow.com/questions/11839555/cuda-uncorrectable-ecc-error-encountered](url)
I don't know this correctly....

As a result, this seems to be CUDA or some server problems. 

By the way, Do you have any experience that is any problem occurring using DataParallel (not Distributed Data Parallel) with `DGX station A100?`
