### ISSUE TITLE
Clicking on superbbenchmark.org in README redirected to GitHub 404 Page not found

### ISSUE THREAD

**Issue by yistLin** [s3prl/s3prl#347]
In README, under section "Announcement", if you click on the url superbbenchmark.org , it redirects you https://github.com/s3prl/s3prl/blob/master/www.superbbenchmark.org , and shows 404 Page not found. Same for the url 140.112.21.28

**Comment by leo19941227** [comment]
Thanks @yistLin daddy for reporting the bug OAQ
Will fix this soon
