### ISSUE TITLE
Missing hidden layers

### ISSUE THREAD

**Issue by Lazypanda278** [s3prl/s3prl#350]
Hello.
I'm trying to get wav2vec 2 features using s3prl upstream. I'm playing around with all the hidden layer outputs, and not interested only in encoder output.
I notice that in some of the outputs, some hidden states are missing from the output. 
Such as below(I wrote a small script to display the hidden state info  when length of hidden states returned is less  than 13)

('self.model.encoder.layers[0]', 'self.model.encoder.layers[1]', 'self.model.encoder.layers[2]', 'self.model.encoder.layers[3]', 'self.model.encoder.layers[4]', 'self.model.encoder.layers[5]', 'self.model.encoder.layers[7]', 'self.model.encoder.layers[8]', 'self.model.encoder.layers[10]', 'self.model.encoder.layers[11]', 'self.model.encoder')

  0%|▏                                                                                                                                 | 3/2620 [00:00<06:48,  6.40it/s]

('self.model.encoder.layers[0]', 'self.model.encoder.layers[1]', 'self.model.encoder.layers[2]', 'self.model.encoder.layers[3]', 'self.model.encoder.layers[4]', 'self.model.encoder.layers[5]', 'self.model.encoder.layers[6]', 'self.model.encoder.layers[7]', 'self.model.encoder.layers[8]', 'self.model.encoder.layers[10]', 'self.model.encoder.layers[11]', 'self.model.encoder')

  0%|▎                                                                                                                                 | 6/2620 [00:00<06:16,  6.95it/s]

('self.model.encoder.layers[0]', 'self.model.encoder.layers[1]', 'self.model.encoder.layers[2]', 'self.model.encoder.layers[3]', 'self.model.encoder.layers[5]', 'self.model.encoder.layers[6]', 'self.model.encoder.layers[7]', 'self.model.encoder.layers[8]', 'self.model.encoder.layers[9]', 'self.model.encoder.layers[10]', 'self.model.encoder.layers[11]', 'self.model.encoder')

  0%|▌                                                                                                                                | 12/2620 [00:01<06:58,  6.23it/s]

('self.model.encoder.layers[0]', 'self.model.encoder.layers[1]', 'self.model.encoder.layers[2]', 'self.model.encoder.layers[3]', 'self.model.encoder.layers[4]', 'self.model.encoder.layers[5]', 'self.model.encoder.layers[7]', 'self.model.encoder.layers[9]', 'self.model.encoder.layers[10]', 'self.model.encoder.layers[11]', 'self.model.encoder')

  0%|▋                                                                                                                                | 13/2620 [00:02<07:20,  5.92it/s]

('self.model.encoder.layers[0]', 'self.model.encoder.layers[1]', 'self.model.encoder.layers[2]', 'self.model.encoder.layers[3]', 'self.model.encoder.layers[4]', 'self.model.encoder.layers[5]', 'self.model.encoder.layers[6]', 'self.model.encoder.layers[7]', 'self.model.encoder.layers[9]', 'self.model.encoder.layers[10]', 'self.model.encoder.layers[11]', 'self.model.encoder')

  1%|▋                                                                                                                                | 14/2620 [00:02<07:04,  6.14it/s]

('self.model.encoder.layers[0]', 'self.model.encoder.layers[1]', 'self.model.encoder.layers[2]', 'self.model.encoder.layers[3]', 'self.model.encoder.layers[4]', 'self.model.encoder.layers[5]', 'self.model.encoder.layers[6]', 'self.model.encoder.layers[8]', 'self.model.encoder.layers[9]', 'self.model.encoder.layers[10]', 'self.model.encoder.layers[11]', 'self.model.encoder')

Is this normal behaviour ? If yes, I will be grateful if someone explains why it is so.
Thanks in advance.

**Comment by leo19941227** [comment]
Hi, 

Yes, this is normal.
Since the default mode of wav2vec2 (training mode) enables the layer-drop, hence you should set `wav2vec2.eval()` to make it output all hidden layers consistently
