### ISSUE TITLE
How to update the MACs and (1)~(4) in the SUPERB Benchborad?

### ISSUE THREAD

**Issue by mechanicalsea** [s3prl/s3prl#356]
In the SUPERB Benchborad, I found these LightHuBERT models did not report the MACs and (1)~(4). And I want to report as the [official profiling tool](https://superbbenchmark.org/challenge-slt2022/submission#Profiling-Tool).

How can I update the MACs and (1)~(4)? Resubmit the results with these metrics?

Thanks.

**Comment by leo19941227** [comment]
Hi! This is the profiling tool used int the SUPERB Challenge 

https://github.com/B06901052/DeepSpeed/tree/superb-challenge

**Comment by mechanicalsea** [comment]
Thanks. I have submitted the results of LightHuBERT on the SUPERB Benchboard to facilitate future research.
