### ISSUE TITLE
Use of downstream tasks of WavLM ASV Testing

### ISSUE THREAD

**Issue by leijue222** [s3prl/s3prl#361]
I refer to the documentation [here](https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/docs/superb.md#asv-automatic-speaker-verification).
I can successfully run the training of wavlm_large by:
`python3 run_downstream.py -m train -u wavlm_large -d sv_voxceleb1 -n wavlm_large `
Then I from [here](https://github.com/microsoft/UniSpeech/tree/main/downstreams/speaker_verification) download WavLM large model for SV ([wavlm_large_finetune.pth](https://drive.google.com/file/d/18rekjal9NPo0VquVtali-80yy63252RX/view)) to `s3prl/result/downstream/`
Then I run:
` python3 run_downstream.py -m evaluate -e result/downstream/wavlm_large_finetune.pth`
But I failed with error:
```
[Runner] - Resume from result/downstream/wavlm_large_finetune.pth
Traceback (most recent call last):
  File "run_downstream.py", line 220, in <module>
    main()
  File "run_downstream.py", line 162, in main
    args, config, backup_files = get_downstream_args()
  File "run_downstream.py", line 132, in get_downstream_args
    args = update_args(args, ckpt['Args'], preserve_list=cannot_overwrite_args)
KeyError: 'Args'
```
How to solve it? 
It seems like I have to load the s3prl trained ckpt to run, because not sure if the fintune model officially ([wavlm_large_finetune.pth](https://drive.google.com/file/d/18rekjal9NPo0VquVtali-80yy63252RX/view)) provided by WavLM is trained with s3prl and the structure is consistent.

**Comment by leo19941227** [comment]
Oh, I think the checkpoint you pointed out in the UniSpeech repository is not trained by S3PRL. It was trained by their own pipeline so we can not successfully load it in S3PRL.
