### ISSUE TITLE
Here may be a mistake while calculating FLOPs and MACs using the recommended profiling tool

### ISSUE THREAD

**Issue by mechanicalsea** [s3prl/s3prl#366]
Hi! This is the profiling tool used int the SUPERB Challenge 

https://github.com/B06901052/DeepSpeed/tree/superb-challenge

_Originally posted by @leo19941227 in https://github.com/s3prl/s3prl/issues/356#issuecomment-1153733835_

The issue occurs when we apply the profiling tool to calculate the FLOPs and MACs of an upstream model, e.g., the FOLPs of **shared** parameters or modules would be cumulated repeated.

The possible reason comes from
https://github.com/B06901052/DeepSpeed/blob/superb-challenge/flops_profiler/profiler.py#L252-L256

**Comment by leo19941227** [comment]
Hi! Thanks for the comment. I think it would be better to open an issue on the profiling tool's repo, so that 子軒 can have the direct support for you!

**Comment by mechanicalsea** [comment]
Thanks for your suggestions.

It seems to be available to post an issue in the repo of the profiling tool since there is no `Issues` box on the [profiling tool's repo](https://github.com/B06901052/DeepSpeed/tree/superb-challenge).

**Comment by leo19941227** [comment]
Hey @mechanicalsea , the profiling tool's issue page is now available.
You can ask there if you still encounter problems. Thanks!
