### ISSUE TITLE
More detailed usage of SV tasks

### ISSUE THREAD

**Issue by leijue222** [s3prl/s3prl#368]
I refer to the README for SV task training using Wavlm as the upstream.
The usage of this [Demo](https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/docs/superb.md#asv-automatic-speaker-verification) is to train on vox1's Dev and test it on vox1's Test.
I would like to ask what if I want to train on VOX2 and test the results of ERR on VOX1?

**Comment by leo19941227** [comment]
Hi,

For the old codebase in `s3prl/downstream`, this is not possible.
However, recently we release the new codebase and its [documentation](https://s3prl.github.io/s3prl/index.html).
In the new codebase I believe you can easily change the data for a task, so you can follow [the doc here](https://s3prl.github.io/s3prl/_autosummary/s3prl.problem.asv.superb_asv.html#s3prl.problem.asv.superb_asv.SuperbASV.prepare_data) and prepare your own csv files (train/test).
Also see [here](https://s3prl.github.io/s3prl/tutorial/problem.html) for how to customize this behavior.

**Comment by leo19941227** [comment]
We just released this new version and not yet sure about how clear our doc is. Feel free to let us know if anything is unclear or contributing the doc via PR. Thanks!
