### ISSUE TITLE
Could you explain the difference of several downstream tasks

### ISSUE THREAD

**Issue by leijue222** [s3prl/s3prl#371]
```
${POSE_ROOT}/downstream/
|-- sv_lxt
|-- sv_lxt_ge2e
|-- sv_voxceleb1
|-- voxceleb1
|-- voxceleb1_framelevel
|-- voxceleb2_amsoftmax_segment_eval
|-- voxceleb2_ge2e
```

**Comment by leo19941227** [comment]
Only the folders documented in README are ready for public use.

**Comment by leijue222** [comment]
Thanks，I got it. Only [sv_voxceleb1](https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/docs/superb.md#asv-automatic-speaker-verification) is ready for public use.
I will try to adapt the processing of voxceleb2.
