### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by weedwind** [s3prl/s3prl#386]
Hi, I encountered an issue during installation. Does anyone know how to solve it?

Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [57 lines of output]
  running egg_info
  creating /tmp/pip-pip-egg-info-9_hyyjga/s3prl.egg-info
  writing /tmp/pip-pip-egg-info-9_hyyjga/s3prl.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-9_hyyjga/s3prl.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-9_hyyjga/s3prl.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-9_hyyjga/s3prl.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-9_hyyjga/s3prl.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-9_hyyjga/s3prl.egg-info/SOURCES.txt'
  writing manifest file '/tmp/pip-pip-egg-info-9_hyyjga/s3prl.egg-info/SOURCES.txt'
  Collecting fairseq@ git+https://github.com//pytorch/fairseq.git@b5a039c292facba9c73f59ff34621ec131d82341#egg=fairseq
    Cloning https://github.com//pytorch/fairseq.git (to revision b5a039c292facba9c73f59ff34621ec131d82341) to /tmp/pip-install-9hwg6krr/fairseq_d73da71d6d51418b82702f3d5ccabc03
    Running command git clone --quiet https://github.com//pytorch/fairseq.git /tmp/pip-install-9hwg6krr/fairseq_d73da71d6d51418b82702f3d5ccabc03
    Running command git rev-parse -q --verify 'sha^b5a039c292facba9c73f59ff34621ec131d82341'
    Running command git fetch -q https://github.com//pytorch/fairseq.git b5a039c292facba9c73f59ff34621ec131d82341
    Running command git checkout -q b5a039c292facba9c73f59ff34621ec131d82341
    Resolved https://github.com//pytorch/fairseq.git to commit b5a039c292facba9c73f59ff34621ec131d82341
    Running command git submodule update --init --recursive -q
    fatal: reference is not a tree: adb23324c222aad0aad89308e70302d996a5eaeb
    Unable to checkout 'adb23324c222aad0aad89308e70302d996a5eaeb' in submodule path 'fairseq/model_parallel/megatron'
    error: subprocess-exited-with-error

    git submodule update --init --recursive -q did not run successfully.
    exit code: 1

    See above for output.

**Comment by leo19941227** [comment]
Hi, could you try the latest master again?

**Comment by weedwind** [comment]
The installation worked. But I found that the last hidden state of the wav2vec2 base model is different under this vs. previous installation. Previously, I removed the broken submodule that caused the issue above and the installation was successful.

**Comment by weedwind** [comment]
The installation worked. Thank you so much.
