### ISSUE TITLE
TypeError: 'builtin_function_or_method' object does not support item assignment

### ISSUE THREAD

**Issue by maziye-azad** [s3prl/s3prl#389]
hi 
while loading my model with code below:
import torch
model = torch.hub.load('s3prl/s3prl','hubert_large_ll60k')
i face this error:
TypeError: 'builtin_function_or_method' object does not support item assignment
it didn't give this error before.
can anyone help?

**Comment by leo19941227** [comment]
Hi, can you try the latest way of using S3PRL features?
https://s3prl.github.io/s3prl/tutorial/upstream_collection.html
