### ISSUE TITLE
Incorrect encoding detected in ./downstream/asr/char.dict, please rebuild the dataset

### ISSUE THREAD

**Issue by benam2** [s3prl/s3prl#395]
Hi,

Could you please help on how can I fix this error? I have installed all the dependencies including flashlight on condo environment successfully. But I keep getting this error.

I appreciate if you can share your idea on this error with me.

```
Traceback (most recent call last):
  File "/home/ai-labs/Desktop/ASR/fairseq/fairseq/data/dictionary.py", line 236, in add_from_file
    self.add_from_file(fd)
  File "/home/ai-labs/Desktop/ASR/fairseq/fairseq/data/dictionary.py", line 246, in add_from_file
    lines = f.readlines()
  File "/home/ai-labs/.conda/envs/asr3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_downstream.py", line 203, in <module>
    main()
  File "run_downstream.py", line 198, in main
    runner = Runner(args, config)
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/runner.py", line 52, in __init__
    self.downstream = self._get_downstream()
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/runner.py", line 133, in _get_downstream
    **vars(self.args)
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/asr/expert.py", line 82, in __init__
    self.dictionary = Dictionary.load(self.datarc.get("dict_path", str(Path(__file__).parent / "char.dict")))
  File "/home/ai-labs/Desktop/ASR/fairseq/fairseq/data/dictionary.py", line 225, in load
    d.add_from_file(f)
  File "/home/ai-labs/Desktop/ASR/fairseq/fairseq/data/dictionary.py", line 242, in add_from_file
    "rebuild the dataset".format(f)
Exception: Incorrect encoding detected in ./downstream/asr/char.dict, please rebuild the dataset
```

**Comment by benam2** [comment]
I still have this error. Anyone can help please???

**Comment by benam2** [comment]
Any help on this pleaseeee>?

**Comment by leo19941227** [comment]
Could you try to re-install fairseq with `fairseq@git+https://github.com//pytorch/fairseq.git@b5a039c292facba9c73f59ff34621ec131d82341#egg=fairseq`

**Comment by leo19941227** [comment]
I find the latest master occasionally remove the fairseq dependency information, might lead you to install the latest fairseq which might not be compatible.

**Comment by benam2** [comment]
@leo19941227 thanks for replying on this issue.
When I do `git clone https://github.com//pytorch/fairseq.git@b5a039c292facba9c73f59ff34621ec131d82341#egg=fairseq`

It raises `remote: Not Found` error. 

Could you give me the step by step of which branch you want me to check out?
Thanks for taking the time.

**Comment by leo19941227** [comment]
Oh, just check out the `b5a039c292facba9c73f59ff34621ec131d82341 ` commit, and maybe run the `pip install -e ./` again.

**Comment by benam2** [comment]
I can't find a branch name with the one you specified.

Is that what you mean?
`git clone https://github.com/facebookresearch/fairseq.git`

`git checkout -b @b5a039c292facba9c73f59ff34621ec131d82341#egg=fairseq`

Thanks again.

**Comment by leo19941227** [comment]
git checkout b5a039c292facba9c73f59ff34621ec131d82341

**Comment by benam2** [comment]
@leo19941227 thanks so much. I did try to checkout this branch and reinstall the fairseq. But the error still persist.
Is there anything else that I can check?


Again, thanks for taking the time, I appreciate it.

**Comment by leo19941227** [comment]
Hmm... I still can not reproduce.
Did you try the solutions on other places? (like https://stackoverflow.com/questions/38518023/unicodedecodeerror-utf8-codec-cant-decode-byte-0x80-in-position-3131-invali)
I guess this might be an env-specific issue.
