### ISSUE TITLE
Flashlight Decoder --> Flashlight Text

### ISSUE THREAD

**Issue by jacobkahn** [s3prl/s3prl#407]
Hey all — I maintain the Flashlight beam search decoder. Wanted to flag that it has been moved from the Flashlight repo to [Flashlight Text](https://github.com/flashlight/text). I'm working on getting wheels shipped to PyPI so it can be depended on directly by other libs.

A few users have been confused/have opened issues in Flashlight re installing the decoder bindings; if you want to link to the Flashlight Text quickstart [here](https://github.com/flashlight/text#quickstart) and list that as a dependency, that might help. Let me know if you have any questions.

**Comment by leo19941227** [comment]
Cool! Thanks for the information, we will take a look into it.
