### ISSUE TITLE
Add variants of HuBERT and wav2vec2

### ISSUE THREAD

**Issue by ftshijt** [s3prl/s3prl#434]
# Feature request

**Is your feature request related to a problem? Please describe.**
There are some recent HuBERT/wav2vec2 version on other languages. It would be great if they could also be included in the SSL family from s3prl.

**Describe the solution you'd like**
Following is the list from my knowledge:
- [multilingual hubert trained with En, Es, Fr with Voxpopuli](https://dl.fbaipublicfiles.com/hubert/mhubert_base_vp_en_es_fr_it3.pt) ([Reference page](https://github.com/facebookresearch/fairseq/blob/main/examples/speech_to_speech/docs/textless_s2st_real_data.md))
- [wav2vec2-base trained on ES with Voxpopuli](https://dl.fbaipublicfiles.com/fairseq/speech_to_speech/s2st_finetuning/w2v2/es/transformer_B.pt) ([Reference page](https://github.com/facebookresearch/fairseq/blob/main/examples/speech_to_speech/docs/enhanced_direct_s2st_discrete_units.md))
- [wav2vec2-large trained on ES with Voxpopuli](https://dl.fbaipublicfiles.com/fairseq/speech_to_speech/s2st_finetuning/w2v2/es/transformer_L.pt)([Reference page](https://github.com/facebookresearch/fairseq/blob/main/examples/speech_to_speech/docs/enhanced_direct_s2st_discrete_units.md))
- [wav2vec2-large+conformer trained on ES with Voxpopuli](https://dl.fbaipublicfiles.com/fairseq/speech_to_speech/s2st_finetuning/w2v2/es/conformer_L.pt)([Reference page](https://github.com/facebookresearch/fairseq/blob/main/examples/speech_to_speech/docs/enhanced_direct_s2st_discrete_units.md))
- [wav2vec2-base trained on EN with librilight](https://dl.fbaipublicfiles.com/fairseq/speech_to_speech/s2st_finetuning/w2v2/en/transformer_B.pt)([Reference page](https://github.com/facebookresearch/fairseq/blob/main/examples/speech_to_speech/docs/enhanced_direct_s2st_discrete_units.md))
- [wav2vec2-large+conformer trained on EN with librilight](https://dl.fbaipublicfiles.com/fairseq/speech_to_speech/s2st_finetuning/w2v2/en/conformer_L.pt)([Reference page](https://github.com/facebookresearch/fairseq/blob/main/examples/speech_to_speech/docs/enhanced_direct_s2st_discrete_units.md))

**Comment by leo19941227** [comment]
Sure! I would be nice to have them.
We will work on these model in a week or so.

**Comment by leo19941227** [comment]
- Andy: 2, 3
- Haibin: 4
- Harry: 5
- Leo: 1, 6

**Comment by andi611** [comment]
The link for 3) [wav2vec2-large trained on ES with Voxpopuli](https://dl.fbaipublicfiles.com/fairseq/speech_to_speech/s2st_finetuning/w2v2/es/transformer_L.pt) ([Reference page](https://github.com/facebookresearch/fairseq/blob/main/examples/speech_to_speech/docs/enhanced_direct_s2st_discrete_units.md)) is currently down.

**Comment by leo19941227** [comment]
Hi @ftshijt ,

The models are updated, and you can use those models with the version >= `v0.4.8`.
Let us know if anything does not work!
