### ISSUE TITLE
Commonvoice version 7.0 is not easily accessible. 

### ISSUE THREAD

**Issue by raotnameh** [s3prl/s3prl#442]
For the OOD task. In README.md,  it is stated to use version 7.0. 
Using the link provided, we are not able to download the same.

**Comment by leo19941227** [comment]
OOD-ASR is handled by @vectominist , @vectominist are you available to help with this issue recently? Or, I can also take a look on it if you are too busy.

**Comment by raotnameh** [comment]
@vectominist But then the format is changed. What is the format for the input: corpus/preprocess_cv.sh?

**Comment by vectominist** [comment]
I guess following https://huggingface.co/datasets/mozilla-foundation/common_voice_7_0/blob/main/common_voice_7_0.py can download the dataset in the original format so that it is possible to be processed via `corpus/preprocess_cv.sh`.
