### ISSUE TITLE
distill hubert GPU Memory-Usage  is so big

### ISSUE THREAD

**Issue by mujizi** [s3prl/s3prl#444]
Thank you for developing the tool library.
I find distilhubert model used about 1400m gpu memory usage when i use distilhubert model.
The original hubert used about 1700M memory usage.
Distilhubert model use 2 transformers encoder block. It should not occupy so much space. 
Is this a question of how I use it？
Best wish

**Comment by vectominist** [comment]
DistilHuBERT training has a teacher and a student model. This implementation extracts the teacher's representations online. Hence, in each step, we have to forward both the teacher and the student model and backpropagate through the student model, resulting in higher memory usage for only forwarding the student model.

**Comment by mujizi** [comment]
Hi, thank for you reply.

I use this demo code in inference stage.

***
import torch
from s3prl.hub import distilhubert

wavs = [torch.randn(16000) for _ in range(4)]
pretrained_model = distilhubert()
results = pretrained_model(wavs)

# The representation used in the paper
representation = results["paper"]

# All hidden states
hidden_states = results["hidden_states"]

***

It will load teacher model in gpu?
I find distilhubert().model.model is student model (7 cnn + 2 transformer encoder block + split layer),  i don't know why it 
occupy so big memory.  Specifically, it just smaller than origin hubert about 300M. If i want to use student model in inference 
stage. What should I do?
Best wish

**Comment by vectominist** [comment]
Hi loading the student model during inference does not include the teacher model, so it shouldn't occupy too much memory. You can compare with `from s3prl.hub import hubert` and see the difference.

**Comment by mujizi** [comment]
你好
   我刚做了实验，hubert 占了1700M显存，distill hubert 大约是 1300M。
   少了10层的encoder block，只少了400M显存，论文上上显存应该减少70%额。有点疑惑了

**Comment by vectominist** [comment]
The paper only mentioned that the "number of parameters" reduced by 70%, not GPU memory

**Comment by mujizi** [comment]
你好
抱歉，之前测试显存方法有问题。使用 [torch.cuda.memory_allocated] 证明 显存上也减少了 70%。
祝好
