### ISSUE TITLE
unspecifed upstream models

### ISSUE THREAD

**Issue by marziye-A** [s3prl/s3prl#451]
hello
there are several unspecified upstream models in s3prl hub like:
passt_base
ssast_frame_base
wav2vec2_base_s2st_en_librilight
wav2vec2_conformer_large_s2st_en_librilight
,...
can you provide an explanation for these models?
is there a place for all the upstream models details?

**Comment by Baiiiiiiiiii** [comment]
Hello,

for all the upstream models details, you can check here: https://s3prl.github.io/s3prl/tutorial/upstream_collection.html#

you can find Model Architecture or related paper about
all the above listed models:
    passt_base
    ssast_frame_base
    wav2vec2_base_s2st_en_librilight
    wav2vec2_conformer_large_s2st_en_librilight
in that website.


hope it helps :)

@andi611

**Comment by marziye-A** [comment]
thanks! it helped me a lot.

**Comment by leo19941227** [comment]
Hi!

I am closing this issue.
Feel free to re-open it if there is any further question.
