### ISSUE TITLE
Add "device" to cannot_overwrite_args

### ISSUE THREAD

**Issue by pabloriera** [s3prl/s3prl#459]
# Feature request

**Is your feature request related to a problem? Please describe.**
Currently, you cannot change the device when doing an evaluation of a past experiment

**Describe the solution you'd like**
Accept command line --device value

**Describe alternatives you've considered**

Adding this works ok
```        cannot_overwrite_args = [
            'mode', 'evaluate_split', 'override', 'device',
            'backend', 'local_rank', 'past_exp',
        ]```

**Additional context**
I think there is no counter-example to favor this behavior.

Thanks

**Comment by leo19941227** [comment]
Hello,

Cool! Feel free to submit an PR for this and I can merge it immediately.
Or I can also upgrade later. Thanks!

**Comment by pabloriera** [comment]
Excelente, thanks, 2u. I will send the PR
