### ISSUE TITLE
`ref` and `hyp` in `Speech2TextCTCTask`

### ISSUE THREAD

**Issue by vectominist** [s3prl/s3prl#467]
# Bug report

`ref` and `hyp` should be swapped, else `ref` saves the hypotheses and `hyp` saves the references.
https://github.com/s3prl/s3prl/blob/610fe98214e77b84e05d17c716280e326abb61ec/s3prl/task/speech2text_ctc_task.py#L204-L211

**Comment by leo19941227** [comment]
Wow, how did this happen...
Thanks for reporting, I can fix that today. (Or you can also send a PR if you want.)
