### ISSUE TITLE
FileNotFoundError when trying to asquire .lock file in multiprocess run

### ISSUE THREAD

**Issue by medbar** [s3prl/s3prl#468]
Hello! 
I am trying to run code that initializes model in many (256) parallel processes. Some of processes ended with Error ```FileNotFoundError: [Errno 2] No such file or directory: 'hub/f2d5200177fd6a33b278b7b76b454f25cd8ee866d55c122e69fccf6c7467d37d.wavlm_large.pt.lock'```

I found that if I commented [download.py:182-185](https://github.com/s3prl/s3prl/blob/7a2a265d998fadbd0881fc28e2c7a192e0587a08/s3prl/util/download.py#L182) lines this bug is gone. I think it is because one process is deleting .lock file in this lines, while another process is trying to lock the same file. 

Is it really nessesary to delete .lock file? 
Or maybe there are better ways to fix this problem?

**Comment by leo19941227** [comment]
Hi!

Thanks for reporting!
I thought this is already handled by the try-except block, but it seems unfortunately not...
Could you provide your S3PRL version?

Yeah you are right it is not necessary to delete it. I just thought that I already handled this multiprocess situation (but not...)
You can first comment out those lines, I should come out with another way to delete the lock file safely (If I can't come out with a good solution maybe I would just leave the file there...)
Is it convenient for you to provide an reproducible example so I can debug on this later?
Thanks!

**Comment by medbar** [comment]
Thanks for the quick response! 
I use s3prl==0.4.10. 
It is hard to create the test that would reproduce this problem on any hardware. But I think [this code](https://colab.research.google.com/drive/1314iKKTXp39PBFlPxtIovfca_myaFK9Q?usp=sharing) can be used for debugging.

**Comment by leo19941227** [comment]
Thanks! I would take a look after this weekend.

**Comment by leo19941227** [comment]
@472 Fix this.
I will reflect the change on PyPi later.
