### ISSUE TITLE
Problem with install requirements of pyTorch

### ISSUE THREAD

**Issue by Eskartur** [s3prl/s3prl#471]
# Bug report

**Describe the bug**
the requirement of pyTorch is `torch >=1.8.0,!=1.10.0`, running `pip install s3prl` installs the recently released 2.0 version of pyTorch which is not compatible.

**To Reproduce**
pip install s3prl

**Expected behavior**
pip should install the compatible versions.

**Screenshots**
the requirement:
![image](https://user-images.githubusercontent.com/91512127/226534284-0d9bc6a5-647f-40c1-9507-36cea787e566.png)

torch 2.0.0 is not compatible:
![image](https://user-images.githubusercontent.com/91512127/226534371-233d689d-f580-42ab-ab14-24bc561597e7.png)

**Environment**
Ubuntu 20.04.5 LTS
Python 3.8.10
pip 21.2.4

**Comment by andi611** [comment]
For the record, the problem appears to be dependency conflicts in the users' pip packages and not an S3PRL issue.
And it has been tested that S3PRL works with torch 2.0.0
