### ISSUE TITLE
Wav2vec2: understanding the hidden_states index

### ISSUE THREAD

**Issue by spandandey21** [s3prl/s3prl#482]
In wav2vec2_xlsr, I use the code 
model_3(wavs)["hidden_states"][index] 
to extract different hidden layer representations. There are 24 transformer encoders, but the hidden states has 25 valid indicies. Does the index "-1" layer means the final transformer and the idex "0" means convolution layer's output?

I want the first and last transformer's outputs. Kindly suggest the necessary syntax.

**Comment by leo19941227** [comment]
Yes. You are correct.
