### ISSUE TITLE
Add ESPnet pretrained models to S3PRL

### ISSUE THREAD

**Issue by ftshijt** [s3prl/s3prl#488]
Hi, recently, our lab is actively working on self-supervised pre-training for various scenarios within ESPnet. As it supports various settings additional to the current upstream list, I'm wondering if the team is interested in supporting those for the s3prl upstream collection.

I think a possible solution is to add another entry along with `custom` or `hf_custom` to be as `espnet_custom` etc. If the team thinks that would be a good idea, we can try to create the entry with a PR to yours.

**Comment by leo19941227** [comment]
Sounds good! I have a quick question. Where will the model definition of the espnet pretrained ssl models be? Does it depend on the transformer library or the espnet package (I guess it is not in fairseq version ), or you plan to copy the model definition files to an espnet-dedicated upstream folder?

**Comment by ftshijt** [comment]
Thanks for the question, I guess we need a bit more discussion to get back to you. soon back

**Comment by ftshijt** [comment]
As given our internal discussion, we prefer to add a dependency to ESPnet package if possible. Basically, for the following reasons:
- there are some internal dependencies in ESPnet (e.g., hubert layers in torchaudio), which might be easier to organize (otherwise, we would have to add introduce those distinct dependencies to s3prl). 
- ESPnet can also act as a error filter at here in the case of Ci filling because of issues in those dependencies as we would probably find those issues in our CI as soon as the issues come out.
- it would be easier for us to maintain updates just in ESPnet instead of maintain both codebases

However, I do understand that introducing another dependency might be a "heavy" decision. In that case, one option I'm thinking is to make the dependency optional and only raise when we want to use ESPnet pre-trained model (we are using similar style in ESPnet). Definitely depends on your preferences~

**Comment by leo19941227** [comment]
Cool! Actually I have the similar preference: optionally depends on the espnet package and raises when the user is using the ESPnet pre-trained model.
Personally I think this new function will be cool that people can easily leverage the ESPnet SSL models for SUPERB downstreams without any coding, while I am wondering whether @andi611 have other concerns?

**Comment by andi611** [comment]
Hi @ftshijt and @leo19941227, the above discussion looks good to me. Let's move forward with the PR 😄

**Comment by leo19941227** [comment]
Cool thanks @andi611 !
I guess from @ftshijt 's side, you want to work on this function yourselves and send the PR for us to review and update the PyPi package.
Just let you know that if there is anything we can help, @andi611 and I are happy to be involved in (we like to code actually). So just let us know when you need us so we can make this PR work smoothly.

**Comment by ftshijt** [comment]
Sure thing, we already have a draft implementation so far, will start a PR and do the discussion there then

**Comment by ftshijt** [comment]
Close it as done~ Thanks for the support from @leo19941227
