### ISSUE TITLE
readme of ASR has expired

### ISSUE THREAD

**Issue by CheeEn-Yu** [s3prl/s3prl#504]
# Bug report
@dlion168
**Describe the bug**
When I try to test my ASR model by using kenLM and try to install python bindings, I discover that link in s3prl/s3prl/downstream/docs/superb.md flashlight python bindings has expired
![image](https://github.com/s3prl/s3prl/assets/91773970/f8b8c5f0-00cf-4615-82cc-190e68584397)

**After click  [flashlight python bindings](https://github.com/flashlight/flashlight/blob/master/bindings/python/README.md)**
![image](https://github.com/s3prl/s3prl/assets/91773970/c5b341d1-d387-4f07-b6b1-3690468b9fe9)

**Expected behavior**
The original repo has already update and thus can't install python bindings alone

**Comment by leo19941227** [comment]
Thanks for reporting. Since the ASR performance in SUPERB is saturating hence people tend to skip the results with LM nowadays. I would look into this later.

**Comment by leo19941227** [comment]
This issue is fixed via #505
