### ISSUE TITLE
Feature request for Language Identification on ML-SUPERB dataset 

### ISSUE THREAD

**Issue by nervjack2** [s3prl/s3prl#514]
# Feature request for Language Identification downstream on ML-SUPERB dataset 

The evaluation of language identification on speech SSL models has been proposed in [ML-SUPERB](https://arxiv.org/abs/2305.10615). 
Their implementation of Language Identification (LID) is based on [espnet](https://github.com/espnet/espnet/tree/master/egs2/ml_superb/asr1), treating LID as an ASR task. They use the language tag as if it were a transcription and perform an ASR task with a target length of 1. This approach could not fairly evaluate the performance of models that directly extract utterance-level representations (e.g., BYOL for audio). Therefore, I believe that implementing a classification-based LID task on s3prl could be beneficial for the speech community.

ML-SUPERB has curated 14 multilingual datasets, spanning over 140 languages in total. I believe it would be possible to leverage their datasets and reference the existing SID downstream tasks on s3prl to implement a classification-based LID downstream task.

A implementation is now located at [https://github.com/nervjack2/Language-Identification-for-Speech-SSL-Models/tree/main](https://github.com/nervjack2/Language-Identification-for-Speech-SSL-Models/tree/main),
I am wondering if there is a chance to merge it into the s3prl repository.

Thanks!

**Comment by leo19941227** [comment]
Hi @nervjack2 ,

Sounds good. However, we might need more time for reproducing your pipeline. (Probably several weeks later.)
Also, since the results will be hugely different for all the upstreams compared to that in the ML-SUPERB paper (due to the different downstream model), I am wondering will there be any paper documenting the LID performance for the newly added codes? If not, could you run some representative upstreams (the ones in ML-SUPERB especially with the multilingual support) and compare to the numbers in the ML-SUPERB paper? This way, when people are using the codebase they know the expected performance and the gap between the reported results in ML-SUPERB.

**Comment by ftshijt** [comment]
Hi @nervjack2 , interesting point of view. 

May I ask more details why do you think it is not fair to evaluate the model in the ASR-style LID modeling for utterance-level features?

As per my understanding, the ASR formulation of the problem (by encoder + CTC) is still valid for utterance-level representation (or even better, as the alignment is no longer noisy to learn with).

**Comment by nervjack2** [comment]
Hi @ftshijt , first of all, I sincerely thank for your dedication to ML-SUPERB. Your work has been a great help for me. 

I have tried duplicating the uttr-level representation in current ASR formulation, but could not get a reasonable performance (under 10% ACC). Same representation got over 50% ACC in classification-based formulation. My speculation is that the time-variant information (in frame-wise representation) would give considerable advantage in the ASR formulation, which uttr-level representations don't have.

Thank you once again for your response! 
I am not sure whether my speculation is correct, please don't hesitate to correct me if I made any mistake, thanks!

**Comment by ftshijt** [comment]
I see. Thanks for your empirical analysis! It would be an interesting direction to add on to our current benchmarks as well.

One additional question is how about the encoder-decoder setting, where the decoder could formulate as a attentive pooling for the prediction. In that case, does the issue could be mitigated?

**Comment by nervjack2** [comment]
Yes, it probably would be better I guess?

I can definitely put this feature request aside, and wait for the development of ML-SUPERB first. 
Thank you so much for your respond.
