### ISSUE TITLE
Multiresolution HuBERT as a new upstream

### ISSUE THREAD

**Issue by ftshijt** [s3prl/s3prl#515]
# Feature request

We have been recently working on multiresolution HuBERT (https://openreview.net/forum?id=kUuKFW7DIF) which could get better performance than original HuBERT with faster speed. As we released a range of pre-trained models from the fairseq (https://github.com/facebookresearch/fairseq/pull/5363) in PR, it would be great if the related models can be added to S3PRL upstream collection.

**Describe the solution you'd like**
We would like to add the model to s3prl upstream collection.
Similar to other fairseq models (e.g., wav2vec2, hubert, and data2vec), I will provide the `convert.py` to limit the dependency of fairseq. But would need your guys help in holding some of them in the s3prl huggingface model space. 

**Describe alternatives you've considered**
Another option is to directly supporting them at the s3prl huggingface model space by uploading all my converted model checkpoints there

**Additional context**

- Arxiv paper: https://arxiv.org/abs/2310.02720

**Comment by leo19941227** [comment]
Hi @ftshijt ,

Cool thanks, and congratulation to the high scores of the ICLR reviews!
However I am quite busy with the midterm recently and will be available after two weeks. We can proceed with the review after I am available then. However, I think this would be a nice function overall and you can move on with the implementation first. If you want, you can directly join the [S3PRL huggingface model space](https://huggingface.co/s3prl) and upload checkpoints there with a new MR-HuBERT repo (I guess this will be the most convenient approach).
What do you think?

**Comment by ftshijt** [comment]
Hi @leo19941227 , I sent the request to join s3prl huggingface space. Could you please let me in so that I can proceed to upload the converted ckpt?

**Comment by leo19941227** [comment]
Hello, I have approved it.

**Comment by raotnameh** [comment]
@ftshijt Hi, I was wondering, if you could share your third iteration HuBERT base training tensorboard logs.

**Comment by ftshijt** [comment]
> @ftshijt Hi, I was wondering, if you could share your third iteration HuBERT base training tensorboard logs.

Sure. I would unlikely to share it in the public space (as I do not have a place to keep it in a good format), feel free to drop me an email for that.

**Comment by raotnameh** [comment]
@ftshijt Thank you. I have dropped you an email.

**Comment by Liujingxiu23** [comment]
Is there any public codes for  Multiresolution HuBERT ?

**Comment by ftshijt** [comment]
@Liujingxiu23  Hi, you can check https://github.com/facebookresearch/fairseq/tree/main/examples/mr_hubert for training mr hubert. The training procedure is the same as Hubert.
