### ISSUE TITLE
No module named 's3prl.superb'

### ISSUE THREAD

**Issue by moodeerf** [s3prl/s3prl#518]
# Bug report

when I run 's3prl/example/superb_asr/train.py',Here's the error I encountered：
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
ModuleNotFoundError: No module named 's3prl.superb'

**Comment by leo19941227** [comment]
Hi,

Sorry for the confusing. The `example/superb_asr` is a deprecated example.
Please follow our [doc](https://s3prl.github.io/s3prl/tutorial/problem.html) for the S3PRL modularized usage.
Or follow our [README](https://github.com/s3prl/s3prl/blob/main/s3prl/downstream/docs/superb.md#asr-automatic-speech-recognition) for the ASR training.
Thanks for reporting. I will find time to remove the deprecated files.
