### ISSUE TITLE
Not able to submit the results. 

### ISSUE THREAD

**Issue by raotnameh** [s3prl/s3prl#523]
Hi, 

I am trying to submit the results for the SUPERB benchmark. 

1. https://[superbbenchmark.org](https://superbbenchmark.org/)/ is not working. 
                  (base) tnameh@hemants-MacBook-Air ~ % ping www.superbbenchmark.org
                  PING superbbenchmark.org (140.112.21.28): 56 data bytes
                  Request timeout for icmp_seq 0
                  Request timeout for icmp_seq 1
                  Request timeout for icmp_seq 2
                  Request timeout for icmp_seq 3
                  Request timeout for icmp_seq 4

2. https://superbbenchmark.github.io/#/login is not working also. 
![Uploading Screenshot 2023-12-25 at 5.21.14 PM.png…]()

**Comment by leo19941227** [comment]
Thanks for reporting. Will fix that tomorrow.

**Comment by raotnameh** [comment]
Thanks.

**Comment by leo19941227** [comment]
Hi,

The website is back.

**Comment by raotnameh** [comment]
@leo19941227 Thanks. 

There was a issue with the speaker verification submission. I have created a pull request. please give it a read.
