### ISSUE TITLE
a question about two-stage downstream task

### ISSUE THREAD

**Issue by lth456321** [s3prl/s3prl#531]
Hi Researchers,
Thanks for building this framework. I want to implement a two-stage downstream task, so I have to freeze some layers and unfreeze layers in specific steps. Can you tell me if it is supported in this framework? 
Thank you

**Comment by leo19941227** [comment]
We are only responsible for maintaining the weighted-sum framework in SUPERB. For the other usage, you will need to trace the code or implement it yourself.
