### ISSUE TITLE
ASVspoof Dateset Support

### ISSUE THREAD

**Issue by poyu39** [s3prl/s3prl#532]
Hello, I am a beginner to ASV problems, and I try to understand by starting from the sv_voxceleb1 downstream task. However, the example uses the VoxCeleb dataset. Can the dataset be changed to the ASVspoof dataset?

I noticed that the upstream models mostly use 16000hz wav for training, but ASVspoof is flac, so I wonder if this is feasible?

**Comment by poyu39** [comment]
[ASVspoof 2021](https://www.asvspoof.org/index2021.html)

**Comment by leo19941227** [comment]
Hi,

I think our downstream evaluation codebase is quite dataset dependent. So I do not think you can easily change to use the ASVspoof dataset. But adding new tasks based on the current framework is quite straightforward. You can follow the instruction here: https://github.com/s3prl/s3prl/tree/main/s3prl/downstream#add-new-downstream-tasks

**Comment by poyu39** [comment]
I found this function that can process data sets in the documentation, but the link is dead. I don’t know if the documentation has expired.
https://s3prl.github.io/s3prl/_autosummary/s3prl.problem.asv.superb_asv.html#prepare-voxceleb1-for-sv
