### ISSUE TITLE
Cannot submit my results in the leaderboard

### ISSUE THREAD

**Issue by sausage-333** [s3prl/s3prl#535]
SUPERB leaderboard is not working, so I cannot submit my results.
I cannot submit my results with IP-based link since the google does not permit to login due to the safety issue.

Can you fix it?

Thanks,

**Comment by leo19941227** [comment]
Sure, I will work on this tonight. Thanks for reporting.

**Comment by leo19941227** [comment]
Hi,

The website is back. Please try it and let us know if it is not working. Thanks!

**Comment by leo19941227** [comment]
Oh I suddenly realize the issue here is for the expired https certification. The website domain happened to also expire yesterday so I only fixed the domain name issue. I am working on the https part.

**Comment by leo19941227** [comment]
Hi @sausage-333 , the http issue is fixed. I think the submission pipeline is working now. Let us know if it is not. Thanks!
