### ISSUE TITLE
Document link broken

### ISSUE THREAD

**Issue by poyu39** [s3prl/s3prl#537]
I found this function that can process datasets in the documentation, but the link is dead. I don’t know if the documentation has expired.
https://s3prl.github.io/s3prl/_autosummary/s3prl.problem.asv.superb_asv.html#prepare-voxceleb1-for-sv

**Comment by leo19941227** [comment]
Hi,

The original link on official VoxCeleb1 website is dead.
You can use the following link to access the dataset:

https://huggingface.co/datasets/ProgramComputer/voxceleb/tree/main
