### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by PeiwenSun2000** [s3prl/s3prl#538]
It seems that every link related to IP `140.112.21.28:9000` is broken.
Such as: `http://140.112.21.28:9000/fluent.tar.gz`

Is there any chance you can help me out?

**Comment by leo19941227** [comment]
The website is currently down. We will put it back in a week. Sorry for the inconvenience.

**Comment by Miamoto** [comment]
> The website is currently down. We will put it back in a week. Sorry for the inconvenience.

It passed already more than a week... Will this link be working again? 

Thanks a lot! 
Carlos

**Comment by leo19941227** [comment]
We fix the doc to use another link (hosted on HuggingFace) which will be more robust.
Thanks for reporting!

**Comment by Miamoto** [comment]
Thanks a lot!
