### ISSUE TITLE
QbE downstream

### ISSUE THREAD

**Issue by Miamoto** [s3prl/s3prl#543]
When I run this command: python3 run_downstream.py -m evaluate -t "dev" -u fbank -l -1 -d quesst14_dtw -n fbank_-1_dev_NEW, at some point it gets stuck forever and it doesn't finish.  

Anyone knows why this might happen? 

Thanks, 
Carlos

**Comment by wenjie-p** [comment]
Hi Miatomo, which python version are you using? I recently also encounterred this problem and I found my Python3.10 seems to have some issues with concurrent processing, it worked after I downgraded the python version to 3.8.

**Comment by Miamoto** [comment]
Hello, Wenjie! 

Thanks a lot. I was also using 3.10, but moving to 3.8 solved the problem. 

Thanks

**Comment by leo19941227** [comment]
Glad that 3.8 is working.
