### ISSUE TITLE
Adding MS-HuBERT: Mitigating Pre-training and Inference Mismatch in Masked Language Modelling methods for learning Speech Representations (https://arxiv.org/pdf/2406.05661)

### ISSUE THREAD

**Issue by raotnameh** [s3prl/s3prl#547]
Hi @leo19941227, 

Please guide me how to add the weights to official s3prl repo of my new model?
MS-HuBERT: Mitigating Pre-training and Inference Mismatch in Masked Language Modelling methods for learning Speech Representations [[paper](https://arxiv.org/pdf/2406.05661)]

Hubert codebase can be used as it is. The proposed model changes the pre-training strategy only.  

Thanks

**Comment by leo19941227** [comment]
Hi @raotnameh ,

Sure! Please join the [S3PRL huggingface organization](https://huggingface.co/s3prl) here, and submit the PR with the related huggingface model link.
Thanks!
