### ISSUE TITLE
Segmentation core fault for version >0.4.10 

### ISSUE THREAD

**Issue by Fhrozen** [s3prl/s3prl#562]
# Bug report

**Describe the bug**
Installing version newer than 0.4.10 generates a segmentation core fault on the combination of tensorboard and wandb (ESPnet) because the use of protobuf 3.20.3.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. git clone https://github.com/espnet/espnet
2. `cd tools && make`
3. `./ci/test_integration_espnet2.sh`

**Expected behavior**
Segmentation core fault during S2ST collect feats.

**Environment**
s3prl=0.4.16

version higher than 3.20.3 did not show this issue. Tested with protobuf 4.21.1

**Comment by leo19941227** [comment]
Thanks, I am fixing it.

**Comment by leo19941227** [comment]
Hi,

We have updated the dependency to require `protobuf >= 4.21.1` in `s3prl >= 0.4.17`
The package is now on Pypi: https://pypi.org/project/s3prl/#history
Please consider using the latest version.
Thanks!
