### ISSUE TITLE
Cannot find run_upstream.py file

### ISSUE THREAD

**Issue by zyzpower** [s3prl/s3prl#62]
Where is run_upstream.py file when training upstream models?

**Comment by andi611** [comment]
Hi,

we have updated most of our codes, we will update README soon.
For now, you can run the pre-training of upstreams through the following command:
```
python run_pretrain.py -u mockingjay -c pretrain/mockingjay/config_runner.py -g pretrain/mockingjay/config_model.py -n NameOfExp
python run_pretrain.py -u tera -c pretrain/tera/config_runner.py -g pretrain/tera/config_model.py -n NameOfExp
```
Please change the path in `pretrain/mockingjay/config_runner.py`  and `pretrain/tera/config_runner.py` to your own.

**Comment by leo19941227** [comment]
If you wish to use the previous scripts, you can switch to the tag `git checkout v0.1.0`
Thank you!
