### ISSUE TITLE
mode = args.mode

### ISSUE THREAD

**Issue by zyzpower** [s3prl/s3prl#66]
Hi, I am running run_pretrain.py from the previous checkpoint, the command is:
python run_pretrain.py -u mockingjay -c pretrain/mockingjay/config_runner.py -g pretrain/mockingjay/config_model.py -n NameOfExp -e ./result/pretrain/NameOfExp
Then it shows an error of:
File "run_pretrain.py", line 78, in get_pretrain_args
mode = args.mode
AttributeError: 'Namespace' object has no attribute 'mode'

May I ask what is the "mode" attribute?

**Comment by andi611** [comment]
You don't need the `-e` attribute when starting a new training, it is meant for resuming a paused experiment from a checkpoint.
When `-e` is given, other arguments are ignored.

The mode is not relevant, I've updated the code and removed it, please pull again.

**Comment by zyzpower** [comment]
Thanks. Yes I am resuming from previous expt because machine was down. After rerun, there is below error:

Traceback (most recent call last):
  File "run_pretrain.py", line 127, in <module>
    main()
  File "run_pretrain.py", line 121, in main
    runner = Runner(args, config)
  File "s3prl-master/pretrain/runner.py", line 44, in __init__
    self.upstream = self._get_upstream()
  File "s3prl-master/pretrain/runner.py", line 50, in _get_upstream
    upstream = Upstream(self.config['pretrain_expert']['datarc'],
KeyError: 'pretrain_expert'

Is there retrain_expert in config?

**Comment by andi611** [comment]
Hi,

Sorry I didn't have time to fully test the resume function.
However, I fixed it just now.
Can you `git pull` and try again now?
