### ISSUE TITLE
Audio parameters (hop_length or shift ms, rate, etc) for pre-trained models

### ISSUE THREAD

**Issue by SolomidHero** [s3prl/s3prl#67]
Hi! Thank you for the recent readme update and convenient in-python interface! I am asking docs update request. For feature extracting using any of upstream model it is crucial to know not only input data type (wav, mel, mfcc and others), but also which data type should be used for best performance with corresponding pre-trained models.

For example, as wav2vec2 model applies to wav, decreases sequence dimension by 320, in the paper authors say it corresponds to 20 ms of raw wave. Training was made on LibriSpeech dataset (sample rate is 16kHz). If I use this model to get representations for future pipelines or something, it is better to have the same sampling rate audio and use output vectors as 20ms frame representation. I wouldn't use it with 22.05kHz (or others) with corresponding frame shift of 14.5ms.

Thus, it would be nice to understand: on which data model was pre-trained just to make acceptable plug-in of certain model into pipeline/etc.

Same notice about spectrogram features, which use `hop_length`, `window_length` and other parameters

**Comment by andi611** [comment]
Hi,

> 
> Thus, it would be nice to understand: on which data model was pre-trained just to make acceptable plug-in of certain model into pipeline/etc.

In the [Upstream README](https://github.com/s3prl/s3prl/blob/master/upstream/README.md), the pre-trained data has already been listed. This link is also on the main README.
> 
> Same notice about spectrogram features, which use `hop_length`, `window_length` and other parameters

For baseline features, please see the config files [here](https://github.com/s3prl/s3prl/tree/master/upstream/baseline), I will add them to our documentations soon.
The default values of hop and window are 10ms and 25ms, respectively.


FYI, currently, all the pre-trained models from all papers use a sample rate of 16kHz, to the best of my knowledge no other sample rate has been used yet.

I hope I've answered your questions.

Andy

**Comment by leo19941227** [comment]
Hi,

For the pretrained methods listed in our [upstream READEME](https://github.com/s3prl/s3prl/blob/master/upstream/README.md) which take `mel` as input, all of their frames correspond to 10ms of raw waveform. For methods which take `wave` as input, we will detail their sample rate in the doc recently. Also, I will add a function for upstream interface to handle this like `self.get_sample_rate()`, which might help plugin s3prl into your pipeline without manually `if ... else ...` just to take care of different sample rates from different pretrained methods.

Thank you for pointing out this critical issue, I will resolve this as soon as possible. Hopefully two or three days later.

Sincerly,
Leo

**Comment by SolomidHero** [comment]
Thank you for really fast reply and creating new interface feature!

> For baseline features, please see the config files here, I will add them to our documentations soon.
The default values of hop and window are 10ms and 25ms, respectively.

> For the pretrained methods listed in our upstream READEME which take mel as input, all of their frames correspond to 10ms of raw waveform. For methods which take wave as input, we will detail their sample rate in the doc recently.

It is definitely the answer for this issue and information that should be included within the upstream readme.

**Comment by andi611** [comment]
Hi,

I've made a major update on the [Upstream README](https://github.com/s3prl/s3prl/blob/master/upstream/README.md),
including the information that you asked for.

Let me know if there is anything else you think would be nice to have :)

Andy

**Comment by leo19941227** [comment]
Hi @SolomidHero ,

Just to keep you updated, I have already added a new function for all the pretrained upstream termed `get_downsample_rate`.
You can refer to the code [here](https://github.com/s3prl/s3prl/blob/a2d93553e39334c1dc24e60f1d2869476e2e4265/downstream/runner.py#L59) to see how this can be used.

Sincerely,
Leo

**Comment by trangham283** [comment]
Hello,

Piggybacking on this thread, I hope it's okay -- I also have a question on audio files with different sampling rates, but in this case with a lower sampling rate. Specifically, I'm working with Switchboard, which is sampled at 8K Hz and I'm not sure if it's a good idea to upsample. I wonder if you know of a better standard solution, or how I could specify this at the feature extraction stage. 

Thank you for the great codebase!

**Comment by leo19941227** [comment]
Hi,

I am sorry that I also have not much insight about which approach might work better. If let me try, I will also try up-sample with several available options in `torchaudio.transform.Resample`, but I will not be surprised if the results are bad...

**Comment by SolomidHero** [comment]
@trangham283, commonly, upsampling from 8kHz to 16kHz won't lower quality (theoretically) of initial audio. Hence, I think it is OK to first up sample and then extract representations. So they would correspond to 10ms shift of initial audio
