### ISSUE TITLE
"NotImplementedError" with Audio Albert

### ISSUE THREAD

**Issue by aayushsingla** [s3prl/s3prl#68]
Hi! I am trying to use Audio Albert as my upstream model. However, the following line raises "NotImplementationError" whenever I try to import the model. Is Audio Albert implemented yet and if yes, please guide me on how to use it?

`model = torch.hub.load('s3prl/s3prl', 'audio_albert')
`

**Comment by andi611** [comment]
Hi, 

Audio Albert has been implemented, however, pre-trained checkpoints are not available yet.
Would you like to try `mockingjay` or `tera` instead?

**Comment by aayushsingla** [comment]
Thanks for your real quick reply, sir.  I am more interested in Audio Albert as of now. If possible, can you help me with where I can find the implementation and train it myself?

**Comment by andi611** [comment]
Hi,

Yes, please see [here](https://github.com/s3prl/s3prl/tree/master/pretrain) for the documentations about pre-train.

Andy

**Comment by aayushsingla** [comment]
Oh, Thanks for making the changes, sir. I'm leaving this issue open as this might help those who face similar issues until checkpoints as available for AALBERT. you can close this issue if you want.

**Comment by andi611** [comment]
Hi, 

I've just released the newly trained `audio_albert` checkpoint in `upstream/audio_albert/hubconf.py`.
Now you can import it with:
```python
import torch
model = torch.hub.load('s3prl/s3prl', 'audio_albert')
```
