### ISSUE TITLE
Data preprocessing errors and typos

### ISSUE THREAD

**Issue by SolomidHero** [s3prl/s3prl#71]
Hi! I was working with `timit_phone_linear` downstream fine-tuning and found some errors and typos:

- [x] Direct use of `preprocess/preprocess_timit.py` or `preprocess/preprocess_libri.py` causes error, based on undefined `args.cmvn`:
https://github.com/s3prl/s3prl/blob/4fc7d9ff73c961c704d9aecd976fbd1d9bf00ddf/preprocess/preprocess_timit.py#L102
Maybe, `args.apply_cmvn` should be mentioned:
https://github.com/s3prl/s3prl/blob/4fc7d9ff73c961c704d9aecd976fbd1d9bf00ddf/preprocess/preprocess_timit.py#L48
- [x] Also `preprocess/preprocess_timit.py` from timit datafolder (which contains TRAIN and TEST) creates preprocessed files folder (which contains train, dev, test). I think this is some inconsistent behaviour (because of next checkbox)
- [x] Either `preprocess/preprocess_timit.py` or `preprocess/preprocess_libri.py` are not used for `run_downstream.py` finetuning, because `preprocess/generate_len_for_bucket.py` + "on the fly processing" is used. I mean, should they even be used?
- [x] `--audio_extention` -> `--audio_extension` typo (`preprocess/generate_len_for_bucket.py` script)
- [x] Same description for arguments:
https://github.com/s3prl/s3prl/blob/4fc7d9ff73c961c704d9aecd976fbd1d9bf00ddf/preprocess/generate_len_for_bucket.py#L48-L49

Sorry for bothering you with such simple questions.

**Comment by andi611** [comment]
Hi, 

I've fixed the `args.apply_cmvn` typo, `--audio_extention` typo, and the duplicated descriptions in this [commit](https://github.com/s3prl/s3prl/commit/251f5310e3045904d68212ce5a2e87578af62f2e).

Both `preprocess/preprocess_timit.py` or `preprocess/preprocess_libri.py` is legacy code, we haven't decided what to do with them at the moment. The only preprocessing used by the `timit_phone_linear` task is `preprocess/generate_len_for_bucket.py`.

You can run it with the following command:
```bash
python preprocess/generate_len_for_bucket.py -i your_path_to/TIMIT -a .WAV -n len_for_bucket_timit
```

Sorry for the limited documentation, we will add documentation ASAP (we are still developing and testing).

Andy

**Comment by SolomidHero** [comment]
I found also typos in comment sections of configs:
https://github.com/s3prl/s3prl/blob/a2d93553e39334c1dc24e60f1d2869476e2e4265/downstream/timit_phone_1hidden/config.yaml#L25

Since arguments changed (`input_data` instead of `data_root` and others) it should be changed in all related configs

**Comment by andi611** [comment]
Thanks for the heads up, the configs have been updated!
