### ISSUE TITLE
Models in torch hub

### ISSUE THREAD

**Issue by Sreyan88** [s3prl/s3prl#78]
Hi there,

Currently I run:

`python run_downstream.py -m train -u mockingjay --upstream_trainable --downstream mosei --expname first`

I wanted to know the difference between the above vs:

`python run_downstream.py -m train -u mockingjay_960hr --upstream_trainable --downstream mosei --expname first`

since they seem to be using the same cached model.

If both of them use mockingjay pre-trained librispeech 960 hours checkpoint can you please let me know how to not use a pre-trained model with downstream.py and finetune the transformer on a downstream task from scratch?

Also, the link to mockingjay pre-trained checkpoint as listed on https://github.com/s3prl/s3prl/blob/master/upstream/README.md doesn't work. Please let me know where I can find it.

Thank You

Thank You

**Comment by andi611** [comment]
Hi, 

'mockingjay' and 'mockingjay_960hr' are the same. 

'mockingjay' is the default model, and 'mockingjay_960hr' is an alias.
Here 'mockingjay_960hr' is set as the default ckpt, hence they are the same.

Their relationship (and also the relationship between other checkpoints) are clearly stated in 'upstream/mockingjay/hubconf.py'

I'm having trouble locating the link you say that is not working, can you point it out for me?

Thanks!

Andy

**Comment by Sreyan88** [comment]
Hi Andi,

Thank You for your reply. Found the same in hubconf.py :) 

Also about the link, apologies for that mention, I thought either links would lead me to the downloadable model but I notice now they are not originally supposed to.

Thank You for all the help.
