### ISSUE TITLE
Save best checkpoints

### ISSUE THREAD

**Issue by Sreyan88** [s3prl/s3prl#79]
Hi there,

I have started finetuning pre-trained mockingjay on downstream mosei. However I only see "states-somenumber.ckpt" in my results folder. Wanted to know if run_downstream.py supports saving best models with checkpoints.

Currently I run:

`python run_downstream.py -m train -u mockingjay --upstream_trainable --downstream mosei --expname first`

Thank You

**Comment by leo19941227** [comment]
Hi, 

Yes, you can pass a list of filenames in `log_records`, and the runner will save those filenames into the `expdir` for you.
Whether to pass those filenames is decided by you. if nothing is returned, then only those `states-somenumber.ckpt` are saved.

Sincerely,
Leo

**Comment by Sreyan88** [comment]
Hi Andi,
Thank you for your response. Could you give me a lead to log_records where I need to add this?

Thank You

**Comment by leo19941227** [comment]
Hi,

You can refer to the implementation of [emotion recognition](https://github.com/s3prl/s3prl/blob/master/downstream/emotion_prob/expert.py)

**Comment by leo19941227** [comment]
Hi,

You can refer to the implementation of [phoneme classification](https://github.com/s3prl/s3prl/blob/master/downstream/phone_linear/expert.py)
