### ISSUE TITLE
Question about reconstructing only masked part

### ISSUE THREAD

**Issue by toco2270853** [s3prl/s3prl#89]
Hi, thanks for the great repo.
I have read your paper and another paper: BERTPhone
(https://www.isca-speech.org/archive/Odyssey_2020/pdfs/93.pdf).

I have noticed that MockingJay only reconstruct masked input, but 
BERTPhone reconstruct the whole sequence(autoencoding).

Is there any evidence to show which method is better?

**Comment by andi611** [comment]
Hi,

Mockingjay reconstructing only the masked input,
 is just like [BERT](https://arxiv.org/abs/1810.04805) predicting only the masked tokens.
This makes training more efficient, 
as the loss will not be overwhelmed by the unimportant part (reconstructing the not masked part).

However, we do not have experimental data to support which one is better.

Andy

**Comment by toco2270853** [comment]
Ok, thanks for the quick reply.
