### ISSUE TITLE
Suggestion to edit readme to solve cuda running out of memory error

### ISSUE THREAD

**Issue by swarajdalmia** [s3prl/s3prl#92]
In the readme for upstream task, i was using an aws gpu instance, however cuda was running out of memory very soon. It took me a while to realise that the activations for the entire computational graph were being stored. Maybe it makes sense to edit the simple starting script in upstream readme as below. Would save a lot of time for others.

```
import torch
device = 'cuda' # or cpu
upstream = torch.hub.load('s3prl/s3prl', 'tera').to(device)
wavs = [torch.zeros(160000, dtype=torch.float).to(device) for _ in range(16)] `
with torch.no_grad():
    reps = upstream(wavs)
```

**Comment by andi611** [comment]
Hi, 
Thanks for the constructive suggestion!
We've adopted your suggestion and updated the example codes in this commit: https://github.com/s3prl/s3prl/commit/40bb68948a4c698e6b25ef645577b316fd1de795
