### ISSUE TITLE
Training specific mockingjay variant

### ISSUE THREAD

**Issue by Sreyan88** [s3prl/s3prl#93]
Hi there,

Thank You for this great repository.

I try to fintune pre-trained mockingjay for downstream mosei task using:

`python run_downstream.py -m train -u mockingjay --upstream_trainable --downstream mosei --expname first`

My question is, when I use this command , since it uses mockingjay_960hr as upstream form torch hub, which specific version of mockingjay am I using? Base or Large?

Also, which setting for transformer output is being used by default? weighted sum or just last encoder layer? (as mentioned in the paper in experimental setup), I would like to use weighted sum from my experiments as they have been reported to give best results. Please let me know on how I could achieve the same.

Thank You in advance!

**Comment by andi611** [comment]
Hi, 

> My question is, when I use this command , since it uses mockingjay_960hr as upstream form torch hub, which specific version of mockingjay am I using? Base or Large?

That would be the Base model.

> Also, which setting for transformer output is being used by default? weighted sum or just last encoder layer? (as mentioned in the paper in experimental setup), I would like to use weighted sum from my experiments as they have been reported to give best results. Please let me know on how I could achieve the same.

By default, you are using the last encoder layer's output. You can change to weighted sum by modifying this [line](https://github.com/s3prl/s3prl/blob/40bb68948a4c698e6b25ef645577b316fd1de795/upstream/mockingjay/expert.py#L35).

Let me know if you encounter any problems :)

Andy

**Comment by Sreyan88** [comment]
Hi Andy,

Thank you for your answer, as always. :) Will surely try out the weighted sum  thing and update it here.

Could you let me know what would I have to do if I want to train the Large variant of the model?

**Comment by andi611** [comment]
Hi,

please see this [README](https://github.com/s3prl/s3prl/blob/master/pretrain/README.md).
After following the steps in the above link, you can run pre-train with:
```bash
python run_pretrain.py -u mockingjay -g pretrain/mockingjay/config_model_large.yaml -n Mockingjay-360hr-large --multi_gpu
```

**Comment by Sreyan88** [comment]
Thank You for your reply, very helpful as always, will do the same. :)
