### ISSUE TITLE
Tutorial for using models not available via torch.hub.list('s3prl/s3prl')

### ISSUE THREAD

**Issue by happypanda5** [s3prl/s3prl#95]
Hi, many thanks for this brilliant toolkit.

I note that some models are not available by default. For example, I do not see wav2vec2 when I typed `print(torch.hub.list('s3prl/s3prl'))`.

**Is there a guide for using models these models?** 

I have tried:

###############
import torch
import importlib
import os
os.chdir("/content/s3prl/upstream/wav2vec2")
Upstream = getattr(importlib.import_module('hubconf'), 'wav2vec2')
###############

but I get the error `AttributeError: module 'hubconf' has no attribute 'wav2vec2'`
Note that I changed the path to the wav2vec2 folder

Thanks

**Comment by andi611** [comment]
Hi,
> I note that some models are not available by default. For example, I do not see wav2vec2 when I typed print(torch.hub.list('s3prl/s3prl')).
> Is there a guide for using models these models?

The reason you are not seeing the wav2vec2 model (and other wav2vec series) is that you haven't installed the `fairseq` toolkit.

You should see a message with something like this:
`[hubconf] can not import upstream.wav2vec2.hubconf: No module named `fairseq`... Pass.`
The above message will disappear after you install `fairseq`, and you will see the wav2vec models.

Note that you can find `requirements.txt` under every upstream folder, 
please check them out if you are having issues during install.

Andy
