### ISSUE TITLE
how to use local pretrained models with downstream tasks

### ISSUE THREAD

**Issue by favrei** [s3prl/s3prl#97]
Hi Researchers,

Thanks for building this convenient framework.

After I pretrained my upstream from scratch, I am trying to run the downstream task.
From downstream/README.md, it suggests
`python run_downstream.py -m train -u baseline -d example -n NameOfExp`

But I can't find how to fine-tune or pretrain the downstream linear layers and eventually verify with test data.
I've tried 
`python run_downstream.py -m train -u mockingjay -d phone_linear -n d1 -e result/pretrain/p1`

And it failed, pretty much because I didn't load the correct config files, when it complains I didn't pass the "downstream_expert" parameter.

Can you kindly tell me what did I miss?

Thank You,

**Comment by leo19941227** [comment]
Hi,

Are you now trying to train on phone_linear downstream task, or you have already trained a checkpoint and now fail to load that checkpoint for the testing stage?

**Comment by favrei** [comment]
Hi,
I've pretrained an upstream checkpoint.
Now I am going to train the phone_linear downstream without an associated checkpoint, only the pretrained one for upstream.

**Comment by andi611** [comment]
Hi, 

you don't need the `-e`.
If you are loading your pre-trained model, use `-u mockingjay_local -k path_to_pretrain/states-1000000.ckpt`
If you want to fine-tune your upstream, use `-f` instead.
So the eniter command would be something like:
```
python run_downstream.py -m train -u mockingjay_local -k path_to_pretrain/states-1000000.ckpt -d phone_linear -n ExpName -f
```

**Comment by favrei** [comment]
It works, thank you!

Will this information added to the README in the future? It can be helpful when example commands are given so users won't need to worry about if they are training in an unexpected setup.

Or just list them in Makefile/shell will do it, too.

Again, thank you guys for this work.

**Comment by andi611** [comment]
> It works, thank you!
> 
> Will this information added to the README in the future? It can be helpful when example commands are given so users won't need to worry about if they are training in an unexpected setup.
> 
> Or just list them in Makefile/shell will do it, too.
> 
> Again, thank you guys for this work.

Hi,

yes, I've added this information to the README.
The fine-tune information in this commit: https://github.com/s3prl/s3prl/commit/e0f93626200db3c5f71385b99d7ea150b0b0afca
The loading method in this commit: https://github.com/s3prl/s3prl/commit/6d2327bc6c6ccdd3e21c9c2e7b932b2952667a8e

Sorry for the lack of documentation, we will complete our documentations in the near future.
