### ISSUE TITLE
Exact phone label for phone linear task

### ISSUE THREAD

**Issue by toco2270853** [s3prl/s3prl#98]
Hi, I have used the script to run downstream phone linear task. But the data only provide phone label number instead of what phone does the label map to. How can I get the phone and label mapping? I want to use exact phone label to perform other task other than simply classification.

**Comment by andi611** [comment]
Hi,

The data (phone label number) are from the [CPC literature](https://arxiv.org/pdf/1807.03748.pdf), which they obtained from the [ Kaldi toolkit](http://www.kaldi-asr.org/downloads/build/6/trunk/egs/librispeech/). 

We do not have the phone and label mapping.
However, I believe you can get the mapping from Kaldi.

**Comment by carlosfranzreb** [comment]
Here is the list of 41 phone used by SUPERB: https://www.kaldi-asr.org/downloads/build/6/trunk/egs/librispeech/s5/data/lang/phones/sets.txt
