### ISSUE TITLE
importlib error on Windows

### ISSUE THREAD

**Issue by Drzwioddomu** [s3prl/s3prl#99]
Hi all,

I stumbled upon an error while running `torch.hub.list('s3prl/s3prl')` on Windows 10. The `importlib.import_module` call raises a series of following errors:
`[hubconf] can not import upstream\XXX\hubconf: No module named 'upstream\\XXX\\hubconf'... Pass.`
which is I believe due to the fact that Windows uses backslashes in its paths. 

Changing
`module_name = '.'.join(str(hubconf).split('.')[:-1]).replace('/', '.')`
into
`module_name = '.'.join(str(hubconf).split('.')[:-1]).replace('/', '.').replace('\\', '.')`
in the main `hubconf.py` seems to resolve the issue. 

Cheers!

**Comment by leo19941227** [comment]
Hi,

Sorry that this repo is now still strict to use Linux-like OS. (not only the issue you mention here)
We hope to resolve this soon, and thank you for your suggestion.

**Comment by xiaoyiming** [comment]
I have also encountered this  problem in the ububtu system

**Comment by leo19941227** [comment]
Hey sorry for the late reply.
It's weird for Linux-like systems to fail. Can you paste the screenshot for the error message?

**Comment by leo19941227** [comment]
Recently we are migrating to use pathlib for cross platform path handling.
I think the hubconf-related issue is resolved. Please feel free to re-open it if it is not.
